### ISSUE TITLE
How to to use USB Network Inerface card ?

### ISSUE THREAD

**Issue by falling12** [meefik/linuxdeploy#1009]
I want to use aircrack-ng , but the phone's NIC can not be monitered. So I choose a USB Network Inerface card, but the linux deploy can not recognize it. I really want to know the way to solve the problem. and forgave my poor English. Really Thanks!

**Comment by Danct12** [comment]
I'm not sure about this, but I guess is that you need to compile the USB network module on Linux and load it.

**Comment by emirace** [comment]
I am having the same problem, using USB wireless adapter. 
Pls any fix to this isue

**Comment by WilsonBradley** [comment]
As I understand it, your Android device would need to recognize the USB adapter first, then driver support within the Linux distro running in Linux Deploy. Would this be correct? 
How to check if phone recognizes and supports wireless USB card?
How to check if Linux distro recognizes and has drivers the USB Wireless card
Then how specifically to compile the drivers?
Wanting to use standard 
USB Ralink 3070 chipset

**Comment by falling12** [comment]
I have found  a way to to ckeck if phone recognizes the USB card , and  it truely recognize the card. So I found the driver on GitHub, Saidly it can not be compiled on my device , it shows some error that I can not solve it. Then I decide to buy a RaspberryPi to solve this problem. Thanks for yours attention !
