### ISSUE TITLE
Perferences GUI: Fedora settings [feature request]

### ISSUE THREAD

**Issue by cbm755** [meefik/linuxdeploy#101]
Not urgent but useful for new users.

Would be good if the preferences GUI could show different choices for $ARCH and $MIRROR based on the $SUITE setting.  For reference, here are the settings:
### Fedora 18 (and below)

ARCH: both arm and armhfp are possible.
MIRROR: http://dl.fedoraproject.org/pub/fedora-secondary/releases/
### Fedora 19

ARCH: only armhfp
MIRROR: http://dl.fedoraproject.org/pub/fedora-secondary/releases/
### Fedora 20

ARCH: only armhfp
MIRROR: http://dl.fedoraproject.org/pub/fedora/linux/releases/

(As I said, not urgent, just posting here so its documented somewhere!)

**Comment by kxra** [comment]
should this be closed since those versions of fedora are no longer supported?

**Comment by cbm755** [comment]
thanks!
