### ISSUE TITLE
Making file system (ext4) ... fail

### ISSUE THREAD

**Issue by Shubhamvis98** [meefik/linuxdeploy#1011]
![screenshot_2018-10-14-12-43-26](https://user-images.githubusercontent.com/43336210/46913735-5e6a0400-cfb0-11e8-864c-59723e45e010.png)

When I create a larger img file like 4gb then after creating blank file it fails to make it to ext4 partition
Please solve this problem
If anyone have any alternative then please post it
Thanks...

**Comment by zhy65401** [comment]
Did you solve this problem? I got the same thing...

**Comment by Shubhamvis98** [comment]
Yes, I fixed it
It was the environment problem

**Comment by Shubhamvis98** [comment]
**SOLUTION 1:** Set the path variables in your Linux deploy app to solve this problem

**SOLUTION 2:** The fat32 filesystem doesn't allow you to create more than 4gb files in your external sdcard so format it to exFAT if your phone supports exFAT filesystem
