### ISSUE TITLE
Blender not working 

### ISSUE THREAD

**Issue by anonimo82** [meefik/linuxdeploy#1015]
Hello everyone.

I can't use Blender on my Debian with Linux Deploy, I get an error message about missing GLX extension.

Please, help.

**Comment by anonimo82** [comment]
P.S.: I have a SM-G900F with CyanoGenMod 14.1 (Nougat) and I'm using XSDL.

**Comment by anonimo82** [comment]
Oh, and thanks to who'll help.

**Comment by Danct12** [comment]
Install libgl1-mesa-swx11.

```
apt-get install libgl1-mesa-swx11
```

**Comment by anonimo82** [comment]
There are no installation candidate for that package. I'm using Debian
stretch

Il giorno mer 7 nov 2018, 13:06 Danct12 <notifications@github.com> ha
scritto:

**Comment by Danct12** [comment]
Try backporting this package from jessie.

**Comment by Danct12** [comment]
Try port this package from jessie: https://packages.debian.org/jessie/libgl1-mesa-swx11
If you need to know how to backport/port a Debian package: https://wiki.debian.org/SimpleBackportCreation

**Comment by pattex16** [comment]
> Install libgl1-mesa-swx11.
> 
> ```
> apt-get install libgl1-mesa-swx11
> ```
So you've managed out how to make blender work properly in linux deploy?

**Comment by anonimo82** [comment]
Works very fine
