### ISSUE TITLE
cannot  start mysql service recently. 

### ISSUE THREAD

**Issue by ltkun** [meefik/linuxdeploy#1035]
I have tried reinstalled the system several times. But failed to start MySQL under debian or Ubuntu. Any other services are OK except MySQL or mariadb. What's wrong

**Comment by zixijian** [comment]
usermod -aG aid_inet mysql

**Comment by supersojo** [comment]
great

**Comment by marianomd** [comment]
To persist it and start at boot, I had to add that line to the beginning of /etc/init.d/mysql
