### ISSUE TITLE
Unable to use multiple commands

### ISSUE THREAD

**Issue by lunix33** [meefik/linuxdeploy#1036]
Each time I'm trying to login into my root user within the terminal I'm getting "Killed" as a message and continue as my regular user.
Therefore it's impossible to install any applications or modify any system files.

I'm using a Samsung Galaxy Tab A w/ S-Pen (SM-P580)

**Comment by lunix33** [comment]
When I'm trying to use root, there's the following error in the dmesg log.
![smartselect_20190112-015803_xserver xsdl](https://user-images.githubusercontent.com/9218179/51070354-e393a200-160d-11e9-85c1-d83620f58c77.jpg)
I use Magick on my device and I've get the mount namespace to global.

**Comment by lunix33** [comment]
Ok after testing other commands, it seem commands like `ping` also give out the same error while trying to execute them in chroot.

**Comment by Faxendo** [comment]
Got the same behaviour with a Samsung Galaxy Tab A without S-Pen (SM-T580)
