### ISSUE TITLE
Remove an installation

### ISSUE THREAD

**Issue by johhnry** [meefik/linuxdeploy#1039]
Hello guys,

I recently installed Kali Linux with chroot on Linux Deploy but it took too much disk space on my phone, so I want to remove it completely. Where are all the files situated? In fact I deleted the `linux.img` file which is 4GB, is this the only file ?

Thanks

**Comment by meefik** [comment]
@johhnry yes, just delete this file

**Comment by johhnry** [comment]
OK thanks for your quick answer.
Have a great day !
