### ISSUE TITLE
Non working stuff

### ISSUE THREAD

**Issue by anonimo82** [meefik/linuxdeploy#1051]
Hello everyone.
I have troubles running FireFox and ThunderBird, they won't run at all.
I also face device reboot when launching LMMS and Audacity.

My device is SM-G900F, LineageOS 15.1, Debian stable, XFCE, installed as folder, using XSDL, chroot container, I mounted storage folders for local and sd memory and I use pulseaudio.

Please, help.

**Comment by anonimo82** [comment]
I know it's not the best way to do, but I installed KMail and Epiphany and both work.

Still having issues with LMMS and Audacity.

**Comment by Danct12** [comment]
Have you tried to run firefox and thunderbird through a terminal? It might show more on what really happened when you tried to launch.

**Comment by anonimo82** [comment]
Yes, I did.
Nothing happens

Il giorno mer 13 feb 2019, 06:54 Danct12 <notifications@github.com> ha
scritto:

**Comment by shaquibimdad** [comment]
I am also facing this issue while opening chromium

**Comment by shaquibimdad** [comment]
Finally i got a fix
Just reconfigure with pulseaudio enabled from the linux deploy app

**Comment by anonimo82** [comment]
Do you mean tapping on 'configure' after installation of the packages?

**Comment by anonimo82** [comment]
Can you describe steps followed?

**Comment by anonimo82** [comment]
I can now use LMMS and Audacity, but now my device is ZE551ML, Lollipop stock, Debian stable, XFCE, installed as folder, using XSDL, chroot container, I mounted storage folders for local and sd memory and I use pulseaudio.

I'm using SeaMonkey for both (email and browsing)
