### ISSUE TITLE
Arch installation fails at libsystemd

### ISSUE THREAD

**Issue by richardMeggyes** [meefik/linuxdeploy#1055]
Hi,
My arch installation fails at libsystemd, and debugging is turned on, but there is no additional output. Where should i start troubleshooting this?

Edit: Forgot to mention, LD is freshly installed and tried on android 6.0, 7.1, installed with file and partition mode too. Same thing happend.

Thank you.

**Comment by jypma** [comment]
Same problem here. Possibly it's because libsystemd no (longer ?) exists in [archlinuxarm](https://archlinuxarm.org/packages/arm/libsystemd).

**Comment by jypma** [comment]
@meefik Perhaps it should be removed from [base_packages](https://github.com/meefik/linuxdeploy-cli/blob/c5b0ec7de870f4ba47ae73e058a6afb767b11c62/include/bootstrap/archlinux/deploy.sh#L58) and replaced with [systemd-libs](https://archlinuxarm.org/packages/arm/systemd-libs) ? It seems to say [here](https://www.archlinux.org/packages/testing/x86_64/libsystemd/) that that's the replacement.

**Comment by jypma** [comment]
Got it working by putting the above replacement into `/data/data/ru.meefik.linuxdeploy/files/include/bootstrap/archlinux/deploy.sh`, and then re-running "Install" from the app.

**Comment by maoxuner** [comment]
Package `libsystemd` is renamed to `systemd-libs`.
[libsystemd/systemd-libs change log](https://archlinuxarm.org/packages/arm/systemd-libs/log?id=ecd5714ec72f4bb43b17b216bdc4a7b9ef550b0e)
