### ISSUE TITLE
Cant connect to vnc or visit my apache time after some time.

### ISSUE THREAD

**Issue by tenye2003** [meefik/linuxdeploy#1074]
Hi. Everything works fine for some time but after like 2-3 hours i cant acces my apache server or vnc or telnet. I feel like android is putting linux deploy in sleep or something like that becaus if i press home button and screen goes on everything goes well again. Im running android 6.0.1 on an s5. What can i do to keep linux deploy alive all the time?

**Comment by neoiso** [comment]
设置里的cpu唤醒和锁定wifi。
如果可能的话还应该在你的手机节能设置里将它设置为无限制。

**Comment by tenye2003** [comment]
I dont understand chinese but if u say i need to have to keep cpu and wifi activity on from app i already did that. I made a macro which turn screen on auto every 30 mins and it seems ok for now...

**Comment by tenye2003** [comment]
solution found : activate developer tools and then screen never sleep when plugged in. closed.
