### ISSUE TITLE
PowerVR G6430 + Asus ZenFone 2 + Linux Deploy

### ISSUE THREAD

**Issue by anonimo82** [meefik/linuxdeploy#1084]
Hello everyone. I installed Linux Deploy on an Asus ZenFone 2,

my device is ZE551ML, Lollipop stock, Debian stable, XFCE, installed as folder, using XSDL, chroot container, I mounted storage folders for local and sd memory and I use PulseAudio.

I found on the web this device has a PowerVR G6430, I'm obtaining GLX through libgl1-mesa-swx11, from the Jessie repository. I guess this is not good, because, despite a reasonable 60 FPS with GLXGears, I get horrible performance with Blender, just rotating the default cube is choppy.

So, is it there any graphic driver I can install? If so, which?

Note this specific model is Intel architecture, so anything working in regular Linux also works here.

Thanks in advance for any help.

**Comment by anonimo82** [comment]
I guess, since the ChRoot container has its own Linux Kernel (the Android one), the Video Card should use that Kernel's Driver, and that just a wrapper around it should be available.
I can't guess, anyhow, if the "competence" is from Linux Deploy or from XSDL.

Any help greatly appreciated.

**Comment by anonimo82** [comment]
P.S.: I read I could use VirtualGL, since my device is Intel based, it should be compatible and should send accelerated graphics to XSDL from Android's Kernel under Linux Deploy.
Is this true?

**Comment by anonimo82** [comment]
INFO: No, the driver for the video card is already loaded (module pvrsrvkm), but that uses the libgles2-mesa library, which is not compatible with VirtualGL.
So, the only chance is if XSDL supports GLX.

**Comment by AxelJust** [comment]
Hey,
Do you remember if LTE 4g and WiFi worked out of the box? I consider recycling my old ZenFone 2 to a OpenWRT LTE router.
Currently I have a old ROM on it. Hardware wise the battery has no capacity anymore as it was flat for quite some time and the touchscreen has some defect with dead points and falls inputs, why I want to disable it.
Greatings
