### ISSUE TITLE
system deep sleeping when lock screen.

### ISSUE THREAD

**Issue by mlacker** [meefik/linuxdeploy#1092]
I have same problem like issue #645, but i'm using android 6.0.1 system, and Lock WIFI & CPU wakelock is enabled, when lock screen state, response of ssh to container slows down on local network, also cannot ping any address. I don't want to keep screen up, so is there an option to prevent this ? thanks for the help

**Comment by foolishqi** [comment]
![image](https://user-images.githubusercontent.com/9708411/58726323-06cfba00-8414-11e9-98e4-0a727914a41a.png)
![image](https://user-images.githubusercontent.com/9708411/58726369-2535b580-8414-11e9-8888-5abaed0f3493.png)
nexus5

**Comment by eromoe** [comment]
In my situation,I can access ssh, but it would be very  slow after lock screen for a long time. I think it is the  same  problem. Do you have a solution ?

**Comment by foolishqi** [comment]
keep power

**Comment by khimaros** [comment]
I'm also experiencing this problem with a Pixel running the AOSP (Pie) GSI builds.

**Comment by khimaros** [comment]
It seems Termux had this same issue and they were able to work around with https://github.com/termux/termux-app/pull/1216/

However, even with this fix, the Wi-Fi interface will occasionally sleep *even with the screen on*, which causes SSH interactivity and latency sensitive network applications to suffer.

See https://github.com/termux/termux-packages/issues/1193 and https://github.com/termux/termux-packages/issues/491

**Comment by khimaros** [comment]
I've identified a workaround for the Wi-Fi sleep issue. This resolves all performance issues I experienced with LinuxDeploy but **requires root** and the config resets any time power state changes.

1) Install the **iw** package for your distribution (eg. `sudo apt install iw`)
2) run `sudo iw wlan0 set power_save on; sudo iw wlan0 set power_save off`

Repeat step 2 when power state changes; phone (un-)plugged, screen on/off, etc.

It may be possible for LinuxDeploy to trigger this in an intent receiver for `android.intent.action.SCREEN_ON` and `android.intent.action.SCREEN_OFF` actions.

WARNING: this will almost certainly drain your battery.

**Comment by foolishqi** [comment]
Nice guy, I will try, thank you!

**Comment by mlacker** [comment]
Thanks khimaros, fixed my problem.

**Comment by fjh1997** [comment]
execute `dumpsys deviceidle disable` in termux su mode also works. see #1229

**Comment by kubalobo** [comment]
For me, using an additional app was necessary to completely get rid of deep sleep.
https://play.google.com/store/apps/details?id=com.dambara.wakelocker

**Comment by TobiaszCudnik** [comment]
The only way to get similar Geekbench results from both linux and apk apps was to use the "Wake Lock - CPU Awake" app with the screen set to DIM.

If not it was about 50%. Quite a waste of the battery for a screen you dont use...

**Comment by seb-pau** [comment]
Sorry for reviving this old thread, but I'm encountering this issue. I'm using a Galaxy Note 8 and have tried custom ROMs with Android 9, Android 13 and Android 14, and all of them exhibit the issue where the SSH connection slows down considerably when the screen is off, regardless of the wake locks. Ping increases to ~500ms from 5ms. 
`iw wlan0 set power_save off` works great, the ping goes down to 5ms and SSH is fast again, BUT: it only lasts for around 15s, then the WIFI power_save mode is automatically enabled again and everything is slow again. 

Has anyone experienced this behavior, and knows a solution to permanently disable the WIFI power_save feature?
