### ISSUE TITLE
TUN interface inside Linux Deploy not transfering any packets. Please help!!!

### ISSUE THREAD

**Issue by UralZima** [meefik/linuxdeploy#1130]
Hello. I have very strange problem and can't resolve it. Please help.
I am linux admin and did this many times, but can't do it inside linux deploy.

Have: Android 5.0, no any software installed! clean setup. Linux deploy latest version with Debian buster.

I am trying to run openvpn server inside linux deploy. I did it million times on linux servers and I know how to make it working, but here some mystic happens.
I have a working openvpn server.conf and client.conf copied from another server.

The connection establishes, but I can't ping openvpn server at 10.8.0.1, can't ping client from openvpn server, tun0 on android shows no any packets transfered! Logs for server and client are fine and no ping-restarts! It is connected!

ccmni0: flags=193<UP,RUNNING,NOARP>  mtu 1500
        inet 10.35.129.111  netmask 255.0.0.0
        ether 2a:0b:11:37:11:32  txqueuelen 1000  (Ethernet)
        RX packets 24359  bytes 16550683 (15.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 33045  bytes 5107637 (4.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 26081  bytes 4561024 (4.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 26081  bytes 4561024 (4.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.8.0.1  netmask 255.255.255.255  destination 10.8.0.2
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 100  (UNSPEC)
        RX packets 14  bytes 840 (840.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

I have nulled the firewall (just iptables not working, only iptables-legacy)
iptables-legacy -X
iptables-legacy -t raw -X
iptables-legacy -t nat -X
itpables-legacy -t mangle -X
iptables-legacy -t raw -F
iptables-legacy -t nat -F
itpables-legacy -t mangle -F
iptables-legacy -F

put needed rules

echo 1 > /proc/sys/net/ipv4/ip_forward
DEVETH=ccmni0
iptables-legacy -I FORWARD -i $DEVETH -o tun0 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables-legacy -I FORWARD -s 10.8.0.0/24 -o $DEVETH -j ACCEPT
iptables-legacy -t nat -A POSTROUTING -s 10.8.0.0/24 -o $DEVETH -j MASQUERADE

but I can't ping openvpn server from client. I put apache to linuxdeploy and also can't access it from openvpn client at 10.8.0.1:80
Why tun0 on android have 0 transfered packets? even if I try to ping the client...

The ssh -D socks proxy works. The internet on linux deploy works from android and root user.

route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.8.0.0        10.8.0.2        255.255.255.0   UG    0      0        0 tun0
10.8.0.2        0.0.0.0         255.255.255.255 UH    0      0        0 tun0

I think kernel may block something. I don't know. The openvpn setup is fine 100%, the configs working on another linux servers. 

It is something wrong with tun device on android kerne or how linux deploy act with it

Please help.

Пожалуйста, помогите)

**Comment by UralZima** [comment]
Socat TUN is also not working
http://www.dest-unreach.org/socat/doc/socat-tun.html

socat -d -d -d  TCP:10.0.8.88:11443 TUN:192.168.255.2/24,up
2019/10/31 20:32:01 socat[29853] I socat by Gerhard Rieger and contributors - see www.dest-unreach.org
2019/10/31 20:32:01 socat[29853] I This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit. (http://www.openssl.org/)
2019/10/31 20:32:01 socat[29853] I This product includes software written by Tim Hudson (tjh@cryptsoft.com)
2019/10/31 20:32:01 socat[29853] N opening connection to AF=2 10.0.9.77:11443
2019/10/31 20:32:01 socat[29853] I starting connect loop
2019/10/31 20:32:01 socat[29853] I socket(2, 1, 6) -> 5
2019/10/31 20:32:01 socat[29853] N successfully connected from local address AF=2 10.0.9.95:52792
2019/10/31 20:32:01 socat[29853] I setting option "iff-up" to 1
2019/10/31 20:32:01 socat[29853] N creating tunnel network interface
2019/10/31 20:32:01 socat[29853] I open("/dev/net/tun", 02, 0666) -> 6
2019/10/31 20:32:01 socat[29853] I socket(2, 2, 0) -> 7
2019/10/31 20:32:01 socat[29853] I resolved and opened all sock addresses
2019/10/31 20:32:01 socat[29853] N starting data transfer loop with FDs [5,5] and [6,6]
2019/10/31 20:32:01 socat[29853] N socket 1 (fd 5) is at EOF
2019/10/31 20:32:02 socat[29853] I poll timed out (no data within 0.500000 seconds)
2019/10/31 20:32:02 socat[29853] I shutdown(5, 2)
2019/10/31 20:32:02 socat[29853] N exiting with status 0

I found on google about android: Only NET_ADMIN is allowed to fully control TUN interfaces
What is means? Maybe CONFIG_PARANOID_NETWORK causes problems?

**Comment by UralZima** [comment]
I found the answer. 
ip rule add from all lookup main pref 1

**Comment by Pavel-Matskevich** [comment]
ip rule add from all lookup main pref 1
Thanks a lot!!!
