### ISSUE TITLE
2.5.0, / ... mount: can't setup loop device: No such file or directory

### ISSUE THREAD

**Issue by youling257** [meefik/linuxdeploy#1132]
update to 2.5.0, / ... mount: can't setup loop device: No such file or directory
reinstall 2.4.1 can mount success, then update to 2.5.0, also can mount success.

**Comment by youling257** [comment]
reboot Android just now, 2.5.0 mount failed, / ... mount: can't setup loop device: No such file or directory

**Comment by ElXreno** [comment]
I have the same problem. 
```
+ return 1
+ '[' -d /data/local/mnt ]
+ local mnt_opts
+ '[' -d /sdcard/linux.img ]
+ mnt_opts=rw,relatime
+ mount -o rw,relatime /sdcard/linux.img /data/local/mnt
mount: can't setup loop device: No such file or directory
+ is_ok fail 'done'
+ '[' 2 -eq 0 ]
+ '[' -n fail ]
+ msg fail
+ echo fail
fail
```
Manual mounting with the same parameters works fine.

**Comment by ElXreno** [comment]
Just checked, it's a busybox problem. 
```
root@lavender:/ # /data/data/ru.meefik.linuxdeploy/files/bin/mount -o rw,relatime /sdcard/linux.img /data/local/mnt
mount: can't setup loop device: No such file or directory
```

**Comment by Mwyann** [comment]
@ElXreno you're right, I've replaced the busybox binary in the /data folder with a backup of the previous busybox that was shipping with Linux Deploy, and it works again.

**Comment by Uchiha-Peng** [comment]
same problem

**Comment by Danct12** [comment]
Please update meefik's busybox.

**Comment by shuaixr** [comment]
set path /system/bin/
then update ENV

**Comment by tjchick** [comment]
I have this problem. the /dev/loop0 device is missing

If you do in terminal
su
mknod /dev/loop0 b 7 0

Then it should work after.

meefik - could you add this to the startup of the application?

**Comment by meefik** [comment]
Please try [v2.5.0-155](https://github.com/meefik/linuxdeploy/releases/tag/2.5.0)

**Comment by pbranly** [comment]
I have tried this v2.5.0-155 and the result is the same
The external Hardrives seem to be correctly mounted during the start process but they are not accessible from the Linux session
Please help
Regards
Philippe

**Comment by ElXreno** [comment]
@pbranly try to fully reinstall application

**Comment by pbranly** [comment]
Oups surely no !
Further tests:
In normal session external HDD is not accessible 
In SU session it is !

beelink@localhost:/storage$ 
beelink@localhost:/storage$ ls
3668E0DE68E09DBD  E2AE6A34AE6A0201
beelink@localhost:/storage$ cd 366*
-bash: cd: 3668E0DE68E09DBD: Permission non accordée
beelink@localhost:/storage$ 
beelink@localhost:/storage$ su
root@localhost:/storage# cd 366*
root@localhost:/storage/3668E0DE68E09DBD#

**Comment by zixijian** [comment]
try turn off SElinux

**Comment by sayamsamal** [comment]
@pbranly I'm having the exact same problem. The sdcard gets mounted successfully, but I can only access it through root(sudo su). For this reason I'm unable to get transmission working (already tried running transmission as root:root and also trying adding to aid_sdcard_rw group). Have you found any solution?

**Comment by pbranly** [comment]
@sayamsamal 
I do not get any good solutions for that issue.
I had to make a new clean installation and the issue did not reappear 
Regards from France
Take care
Philippe

**Comment by ghost** [comment]
> 

me the same
