### ISSUE TITLE
Why can't copy the "bash"/"apt" etc. to Android's "/system/bin" ?

### ISSUE THREAD

**Issue by HookeLiu** [meefik/linuxdeploy#1134]
Is it no way to use linuxdeploy's file in original Android's linux?
I'm thinking about to extend the original Android's linux environments so that develop directly. 
But when I trying to execute blow:
```
sudo unchroot
su
cp /data/data/ru.meefik.linuxdeploy/files/kali/bin/bash /system/bin
```
I got "read-only file system"
so I execute `mount -o remount,rw   /system`
and try copy aging, it seemed OK(`ls -shl bash` can see the valid line), but,
execute `/system/bin/bash` got "/system/bin/bash: No such file or directory" 
try copy aging, got "cp: /system/bin/bash: I/O error"
![20191108151117](https://user-images.githubusercontent.com/36752109/68459841-5cb95100-0241-11ea-8b60-405017afede2.png)

**Comment by Danct12** [comment]
Android **doesn't use** [glibc](https://en.wikipedia.org/wiki/GNU_C_Library), it uses [bionic](https://en.wikipedia.org/wiki/Bionic_(software)), which is not compatible with binaries that is used in your standard Linux distribution.

**Comment by HookeLiu** [comment]
Thanks
