### ISSUE TITLE
How to use Docker?

### ISSUE THREAD

**Issue by Uchiha-Peng** [meefik/linuxdeploy#1141]
I want to know how to use Docker in Linuxdeploy. Can you provide a tutorial? thank you very much. I chose to install Docker directly, or running Docker on CentOS or Ubuntu  failed.

**Comment by apoorv28goel** [comment]
I don't think you can. I may be wrong.

**Comment by kityun** [comment]
Whether to solve？Docker  on Debian  failed too.

**Comment by lgyurci** [comment]
Alright, so I managed to run ubuntu:latest docker image with linux deploy, but networking did not work. What I did was going into linux deploy terminal (but in theory any terminal app should do the work with root access). From the app, I set the distro to docker, and installed it, and when it finished, I stopped the container to unmount it. From the terminal, I went to `/data/data/ru.meefik.linuxdeploy/files/bin` and there executed `linuxdeploy start -m` and then `linuxdeploy shell bash`. It did put me into an ubuntu terminal, but I didn't manage to bring life into networking, so you can't really install any program, or make the container useful in any way.

**Comment by Uchiha-Peng** [comment]
> 好的，所以我设法在Linux deploy上运行ubuntu：latest docker镜像，但是网络无法正常工作。我所做的就是进入linux部署终端（但从理论上讲，任何终端应用都应该通过root访问来完成工作）。从应用程序中，我将发行版设置为docker，并进行了安装，完成后，我停止了容器的卸载。从航站楼，我去了`/data/data/ru.meefik.linuxdeploy/files/bin`那里`linuxdeploy start -m`，然后执行`linuxdeploy shell bash`。它的确使我进入了ubuntu终端，但我没有设法使生活变得生动起来，因此您无法真正安装任何程序，也无法以任何方式使该容器有用。

> Alright, so I managed to run ubuntu:latest docker image with linux deploy, but networking did not work. What I did was going into linux deploy terminal (but in theory any terminal app should do the work with root access). From the app, I set the distro to docker, and installed it, and when it finished, I stopped the container to unmount it. From the terminal, I went to `/data/data/ru.meefik.linuxdeploy/files/bin` and there executed `linuxdeploy start -m` and then `linuxdeploy shell bash`. It did put me into an ubuntu terminal, but I didn't manage to bring life into networking, so you can't really install any program, or make the container useful in any way.

**Comment by Uchiha-Peng** [comment]
Maybe we should give up using Linux Deploy to run Docker, because any distribution installed using Linux Deploy is not full Linux, I refered to a tutorial to install Termux in Android phones, install qemu in Termux, and then use qemu Install X86 or ARM Alpine Linux, then install Docker in Alpine,even without root phone, the effect is very good, but a bit slow 【by google translate】 https://www.dazhuanlan.com/2019/11/28/5ddf5d9429698/

**Comment by lgyurci** [comment]
Keep in mind that running docker and running a docker image is two separate things. Linux deploy wants to do the latter.

**Comment by Uchiha-Peng** [comment]
> Keep in mind that running docker and running a docker image is two separate things. Linux deploy wants to do the latter.

I successfully installed Docker using ubuntu 18.04 of linuxdeploy, but I always get an error and cannot use commands such as docker ps, but termux + qemu + linux + docker can run docker containers normally

**Comment by keesterbrugge** [comment]
Although this issue is closed, I'd love to see a small example of how to run a docker image. I'm having a hard time figuring out how to do it also

**Comment by VNRARA** [comment]
@Uchiha-Peng where u actually talking about the Docker distribution in Linux Deploy or installing a linux type distri and then installing Docker?
