### ISSUE TITLE
socket: permission denied

### ISSUE THREAD

**Issue by jedenastka** [meefik/linuxdeploy#1158]
After getting a new phone, a shiny Galaxy S5, and installing LineageOS 13 on it (Android 9), I noticed that ping and other networking stuff stopped working on old image. Appearently, I can't create an socket (even to localhost!) or resolve any domains. For some reason apt worked anyways. I backed up old image and created entirely new one, but problem persisted.
This is showcase of what happens:
```
Linux localhost 3.4.113-lineageos-g9fc6b38 #1 SMP PREEMPT We
d Jan 15 10:26:14 UTC 2020 armv7l
Debian GNU/Linux bullseye/sid [running via Linux Deploy]
Last login: Fri Jan 31 21:11:35 2020 from ::1
grzesiek11@localhost:~$ ping google.pl
ping: google.pl: Temporary failure in name resolution
grzesiek11@localhost:~$ ping 8.8.8.8
ping: socket: Permission denied
grzesiek11@localhost:~$ ping localhost
ping: socket: Permission denied
grzesiek11@localhost:~$ su -
root@localhost:~# ping google.pl
ping: google.pl: Temporary failure in name resolution
root@localhost:~# ping 8.8.8.8
ping: socket: Permission denied
root@localhost:~# ping localhost
ping: socket: Permission denied
root@localhost:~# exit
logout
grzesiek11@localhost:~$ sudo apt update
Get:1 http://ftp.debian.org/debian unstable InRelease [142 k
B]
Get:2 http://ftp.debian.org/debian unstable/non-free Sources
.diff/Index [27.8 kB]
Get:3 http://ftp.debian.org/debian unstable/main Sources.dif
f/Index [27.9 kB]
Get:4 http://ftp.debian.org/debian unstable/main armhf Packa
ges.diff/Index [27.9 kB]
Get:5 http://ftp.debian.org/debian unstable/main Translation
-en.diff/Index [27.9 kB]
Get:6 http://ftp.debian.org/debian unstable/non-free armhf P
ackages.diff/Index [27.8 kB]
Get:7 http://ftp.debian.org/debian unstable/non-free Sources
 2020-01-31-1417.29.pdiff [232 B]
Get:8 http://ftp.debian.org/debian unstable/non-free Sources
 2020-01-31-2009.16.pdiff [1367 B]
...
```

**Comment by meefik** [comment]
Add the user grzesiek11 to group aid_inet
```
usermod -aG aid_inet grzesiek11
```

**Comment by jedenastka** [comment]
That worked, but... This means that every new user and all of old ones need to be assigned to this group. Is this unfixable from your perspective? Also, what does that group do? Is it something from Android? - I've never seen something like this in GNU/Linux.

**Comment by meefik** [comment]
You can use the option "Privileged users" - A list of users in a format UID:GID separated by a space to be added UID to GID.
E.g. `android:aid_inet android:aid_media_rw`

**Comment by jedenastka** [comment]
Thank you, I close this for now.

**Comment by eusoubrasileiro** [comment]
unfortunattelly  ```usermod -aG aid_inet``` doesn't work for me.

Only if I reboot android and remount everything it get's to work again.

**Comment by mztulip** [comment]
I have identical problem but without solution. My user is in `aid_inet` group.
Reboot not working.
I updated busybox to 1.34.1 and still not working.
I am trying to make it working with lineageos 22.2.
