### ISSUE TITLE
Could not resolve host

### ISSUE THREAD

**Issue by jiajiayao** [meefik/linuxdeploy#1159]
_i using ubuntu 16_

**/etc/resolv.conf**

`nameserver 114.114.114.114
nameserver 8.8.8.8
`

**i cant git clone or wget by the url with hostname**
like
`--2020-02-07 09:45:20--  http://www.baidu.com/
Resolving www.baidu.com (www.baidu.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘www.baidu.com’
`
`	fatal: unable to access 'https://github.com/tyler-smith/go-bip39/': Couldn't connect to server
`
**what should i do?**

**Comment by zhuohoudeputao** [comment]
I meet the same error, and I add sudo to solve it. But I think there must be a better solution.

**Comment by jiajiayao** [comment]
在设置里面加下dns就行了

**Comment by eusoubrasileiro** [comment]
translating just add it in the settings DNS
