### ISSUE TITLE
2.6.0, click mount points force exit

### ISSUE THREAD

**Issue by youling257** [meefik/linuxdeploy#1161]
click mount points, edit the mount points list, crash.

**Comment by meefik** [comment]
What is your version of Android?

**Comment by meefik** [comment]
@Iscle please comment

**Comment by Iscle** [comment]
Interesting... Will take a look at it today!

**Comment by Iscle** [comment]
Okay, I've just tried it and it works fine for me. Could you describe the issue a bit more? Maybe, if possible, send the log.

Thanks!

**Comment by youling257** [comment]
update 2.6.0 from 2.5, click existing profile mount points, and has list, will no response; no list no problem.
if i create a new profile, click mount points no problem.

**Comment by Iscle** [comment]
Okay, I'll try reproducing the issue and I'll get back to you. Thanks for reporting it!

**Comment by youling257** [comment]
oh, 2.6.0, mount list become /dev/block/mmcblk1p2 - /data/1
2.5.1, /dev/block/mmcblk1p2:/data/1

**Comment by youling257** [comment]
my old profile /data/data/ru.meefik.linuxdeploy/files/config/1.conf
MOUNTS="/dev/block/sda2:/1 /data/media/0"

my new profile /data/data/ru.meefik.linuxdeploy/files/config/4.conf
MOUNTS="/dev/block/mmcblk2p3:/data/1 /data/media/0:"
if i edit the new profile to MOUNTS="/dev/block/mmcblk2p3:/data/1 /data/media/0"
open app click the new profile mount point will no response.

**Comment by youling257** [comment]
I edit my old profile conf file, add : to solve this problem.

**Comment by youling257** [comment]
2.6.0, mount list only set Source, not set Target, will not mount !
2.5.1, needn't set Target.

**Comment by youling257** [comment]
if i edit to MOUNTS="/data/data/com.termux/files/home/ /data/media/0 /data/sdext2 /data/app /data/f2fs /data/adb /su" , the mount list can mount, but open app click the new profile mount point will no response.

edit to MOUNTS="/data/data/com.termux/files/home/: /data/media/0: /data/sdext2: /data/app: /data/f2fs: /data/adb: /su:" , the mount list will not be mount.

**Comment by Iscle** [comment]
I fixed it on the latest commit in my fork. I've opened a new pull request.
