### ISSUE TITLE
Upgrade linux kernel Unsuccessful

### ISSUE THREAD

**Issue by kityun** [meefik/linuxdeploy#1167]
1.download Linux-image  deb

2. install deb
      dpkg -i linux-headers-*_armhf.deb
        dpkg -i linux-image-*_armhf.deb
        dpkg -i linux-libc-dev*.deb
3. uanme -r still
    3.10.33
 
current version:
Linux localhost 3.10.33 4b7227d(20171020.115330) armv7l
Debian GNU/Linux 10 (buster) [running via Linux Deploy]

Hope to upgrade 5.5 or laset,
What's the solution?

**Comment by HoshiYamazaki** [comment]
Do you even understand what chroot is?

**Comment by kityun** [comment]
ok，Thank you
