### ISSUE TITLE
无法升级到ubuntu20.04

### ISSUE THREAD

**Issue by wjcwqc** [meefik/linuxdeploy#1192]
安卓4.3环境，装了LD2.51更新环境后没有ubuntu-focal的选项，从ubuntu18.04
`do-release-upgrade -d`提示
Authenticating the upgrade failed. There may be a problem with the network or with the server.
谷歌无果，使用apt换源到focal
`apt update && apt dist-upgrade`
升级后ssh无法使用，重新配置也是无法再次连入ssh

**Comment by wjcwqc** [comment]
升级完之后系统之后重启ssh服务`service ssh restart`解决了ssh的问题，不重启无法再次打开任意ssh连接。但是由于手机存储速度问题升级到ubuntu20.04的过程非常缓慢，花了4、5个小时。希望提供直接安装的选项

**Comment by ICHx** [comment]
开发者不一定会中文呢，

**Comment by wjcwqc** [comment]
> 开发者不一定会中文呢，

我之前看到过有繁中的issue，meefik不会有合作者会就ojbk

**Comment by lateautumn233** [comment]
请试试这个
https://ww.lanzous.com/icj2cje

**Comment by wjcwqc** [comment]
> 请试试这个
> https://ww.lanzous.com/icj2cje

安卓4.3 只能装2.51 2.6安装提示解析安装包错误，安卓sdk太老不支持的。我还以为你给的这个是老版本sdk打包的。。。。

**Comment by wjcwqc** [comment]
手机容器升级到20.04后关机，再打开必须重新更新环境或者以debian环境方式启动，不然会显示syntax error 点击配置设置直接闪退，点击配置 安装 启动全部无法使用

**Comment by Whyle** [comment]
执行这个就好了
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 871920D1991BC93C`
