### ISSUE TITLE
Keep CPU wake up not working properly

### ISSUE THREAD

**Issue by zixijian** [meefik/linuxdeploy#1198]
On my device, version 2.30-245 can better keep the CPU awake, and updating the app version does not work very well. What causes this?

**Comment by istomyang** [comment]
Maybe we should use a low version, I am in Andorid 4, it's a very old device and I have Termux in Andorid 10.

**Comment by zixijian** [comment]
i found a new way.

shell command to acquire a wake lock
```
echo lock_me > /sys/power/wake_lock
```  
shell command to release the same wake_lock
```
echo lock_me > /sys/power/wake_unlock
```  
in chroot use unchroot + command.

**Comment by Hamusuta0320** [comment]
> i found a new way.
> 
> shell command to acquire a wake lock
> 
> ```
> echo lock_me > /sys/power/wake_lock
> ```
> 
> shell command to release the same wake_lock
> 
> ```
> echo lock_me > /sys/power/wake_unlock
> ```
> 
> in chroot use unchroot + command.

very nice way，it helps me，nice bro.
