### ISSUE TITLE
Xserver XSDL support

### ISSUE THREAD

**Issue by einhander** [meefik/linuxdeploy#120]
Plaease add Xserver XSDL support to your app. There is one способ to automaticaly start linux gui through Xserver XSDL http://4pda.ru/forum/index.php?showtopic=531636&view=findpost&p=28655837, but you need to start ssh session and some scripting. 
I'm think the ability to create custom shortcuts to linux app or whole session will be great.

**Comment by irregularisnotrandom** [comment]
Hi

I know the ticket is closed but i cant  find an answer. I have xsdl installed xserver selected  and xfce is selected as the desktop. LD stats Xsdl no problem but the desktop is not starting. I am not sure habout hpw to start it in xserver.

Thanks

**Comment by ducklin5** [comment]
" LD stats Xsdl no problem but the desktop is not starting". I second this. 
fix?

**Comment by joaopa00** [comment]
For the two last comments, see the  post
https://github.com/meefik/linuxdeploy/issues/577
