### ISSUE TITLE
i can not mount /... what should i do?

### ISSUE THREAD

**Issue by Bedivere-Sun** [meefik/linuxdeploy#1207]
hi,
it is my first time run linux deploy.
my device is __xiaomi redmi 3 prime__ which has root access already with magisk manager.

i got this error log when starting install the linux system/container with default settings:
```
[16:07:50] >>> start
[16:07:50] Checking file system ... done
[16:07:50] Mounting the container: 
[16:07:50] / ... fail
[16:07:50] <<< start
```
what should i do? did i missed something that needed to do before?

**Comment by caponk12** [comment]
Enable debug mode! And share the debug log here
