### ISSUE TITLE
Linux still connectable after uninstall

### ISSUE THREAD

**Issue by BaigHack3rss** [meefik/linuxdeploy#1242]
Hi there i have a strange problem. See i uninstalled linux deploy while the container was mounted and the vnc connection didn't stop. now even if i install linux deploy the container is not mounted when i hit the stop button. i even deleted the linux.img file and still the connection is running.]

how do i stop the connection? please help

**Comment by IdreesM0** [comment]
is it still running? How did you stop it?

**Comment by BaigGam3rss** [comment]
I just restarted my device
