### ISSUE TITLE
Missing parameters: TARGET_PATH

### ISSUE THREAD

**Issue by aiivy782** [meefik/linuxdeploy#1250]
Hey! Faced a problem in the program. `Missing parameters: TARGET_PATH`

What does this mean and how can I fix it?

**Comment by rhobb** [comment]
I have the same

**Comment by TheColetrain** [comment]
anyone?

**Comment by aiivy782** [comment]
In the settings, we are looking for the item: `Environment directory` (may actually be called differently), copy this directory (I have `/data/user/0/ru.meefik.linuxdeploy/files`), and paste this to `PATH Variable` (may actually be called differently).

**Comment by DaDogeDev** [comment]
i did what you said but i still get the error
