### ISSUE TITLE
Got error with not find( help wanted)

### ISSUE THREAD

**Issue by Saikatsaha1996** [meefik/linuxdeploy#1259]
Linux deploy Already installed
Every this is fine but got error like this..
I am rooted user
Please help

![IMG_20210608_173653](https://user-images.githubusercontent.com/72664192/121182315-95d40000-c880-11eb-8741-78aae892b7ca.jpg)

**Comment by qwerty65432** [comment]
What?
Tell more

**Comment by Saikatsaha1996** [comment]
Actually when I Compile OpenCL I got this type of error..
directly termux environment it successful..

**Comment by Saikatsaha1996** [comment]
> What?
> Tell more

Actually it is linker problem...
But I don't know why..
I am rooted user
I am installed Linux dep in my system partition
Perfectly running
And already monut rw /system
But got error... Please solve this issue

![Screenshot_20210613-142718469](https://user-images.githubusercontent.com/72664192/121801358-8f64d000-cc54-11eb-8a0b-e47ea52a2bd8.jpg)

**Comment by qwerty65432** [comment]
what you want to do that gives eror

**Comment by qwerty65432** [comment]
🥲

**Comment by Saikatsaha1996** [comment]
> 🥲
> are you steel have problems ?

I want to compile OpenCL in my mobile
In my mobile already available OpenCL and already my mobile rooted..
But got this type of problem

**Comment by Saikatsaha1996** [comment]
> what you want to do that gives eror
> this is noy looks like linux deploy

Yes this is Linux deploy ssh terminal

**Comment by Saikatsaha1996** [comment]
> 🥲
> are you steel have problems ?

Any solution please 🙏
🥺😕

**Comment by qwerty65432** [comment]
hi

**Comment by Saikatsaha1996** [comment]
> hi

Hello !...

**Comment by Saikatsaha1996** [comment]
> hi

Any solution please..
