### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by mizzunet** [meefik/linuxdeploy#1265]
[20:14:21] W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/libc6_2.27-3ubuntu1_arm64.deb
[20:14:21] W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/libc6_2.27-3ubuntu1_arm64.deb is at fault)
Why is it?

**Comment by Fatichti** [comment]
Can you specify:

- the architecture of the machine (ARM...)
- the version of android
- the operating system you want to install and its suite

Can you do :

- Go to Linux Deploy > Left menu > Settings > and check Debug mode
- Replay your problem and take a screenshot

A little help for developers ;)

**Comment by embeeweezer** [comment]
I have the same problem. But only on *some* installations:
Mi A2 lite with ArrowOS 18.1 has the problem,
Mi A2 lite with LOS 18.1 (unofficial) has the problem,
Mi A2 lite with Stock Android 10 (latest update) does NOT have the problem,
Redmi 7 with LOS 18.1 (official) does NOT have the problem.

My workaround was just create a linux image on a phone without the problem and copy that onto the phone with the problem. That works but of course is not a real solution.

**Comment by mizzunet** [comment]
I think it was due to the ROM. I tried a different ROM mow it's installed. Very nice thank you. However, it returns errors on vnc and all.
