### ISSUE TITLE
/files/bin/linuxdeploy: No such file or directory

### ISSUE THREAD

**Issue by aiivy782** [meefik/linuxdeploy#1270]
I faced with this problem on ArchLinux ARM: `/system/bin/sh: <stdin>[4]: /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory`

**Comment by a1797831629** [comment]
I have the same problem as you, you can just reinstall BusyBox. However, I have a problem here. I have installed BusyBox, but after a while, it shows that busyBox is not installed

**Comment by AzeAstro** [comment]
https://github.com/meefik/linuxdeploy/issues/1272#issuecomment-981109987

**Comment by streamingchannels** [comment]
#1272
