### ISSUE TITLE
permission denied (terminal)

### ISSUE THREAD

**Issue by bortan1** [meefik/linuxdeploy#1278]
I have just installed linux deploy and run it using VNC Viewer. I have opened the terminal and typed "apt-get update"and I got this error:
Readin package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/

I have obviously rooted my phone, as Linux Deploy requires root for distribution installation. I have installed Kali Linux and pretty much any command that I insert gives the same permission denied error. What can I do?

**Comment by raspiduino** [comment]
I myself faced this :) Just go to properties and set the username to root, then reinstall.
Boom, it works.

Hope you can fix it.

**Comment by bortan1** [comment]
> I myself faced this :) Just go to properties and set the username to root, then reinstall.
> Boom, it works.
> 
> Hope you can fix it.

That helped, thanks a lot

**Comment by raspiduino** [comment]
No problems :)) You can now close the issue

**Comment by bortan1** [comment]
issue solved
