### ISSUE TITLE
I cannot do directory install

### ISSUE THREAD

**Issue by BaigHack3rss** [meefik/linuxdeploy#1281]
For an unknown reason i cannot do the directory install in my internal storage on android 11
[output.log](https://github.com/meefik/linuxdeploy/files/7190375/output.log)
Here is the log file

**Comment by Shubhamvis98** [comment]
If you're installing in /sdcard then you can't install it because sdcard is mounted as fuse fs. You can change the directory to /data/local/tmp of similar to it.
