### ISSUE TITLE
Linux Deploy 2.6.0 - Failure [INSTALL_FAILED_OLDER_SDK] - android 4.4.4 adb install

### ISSUE THREAD

**Issue by 0nobody0** [meefik/linuxdeploy#1283]
Linux Deploy 2.6.0 adb install fails on android 4.4.4 device with error "Failure [INSTALL_FAILED_OLDER_SDK]"

**Comment by Practicalbutterfly5** [comment]
The latest Linux deploy version only supports sdk 21 (Android 5.0) and above. You can try with 2.5.1 version of linux deploy which supports android 4.1+

**Comment by 0nobody0** [comment]
thank you
