### ISSUE TITLE
[SOLVED] Failed to install on some custom roms

### ISSUE THREAD

**Issue by Practicalbutterfly5** [meefik/linuxdeploy#1288]
I was able to install it fine on my previous android 10 custom rom (lineage os Android 10). But I cannot install it on some android 11 and 12 custom roms.

My device is aarch64
Distribution: Ubuntu and debian both have same error.

Installation ends with the following error :

```
[01:53:48] I: Extracting zlib1g...
[01:53:48] :: Configuring core/mnt ... 
[01:53:48] :: Configuring core/net ... 
[01:53:48] I: Installing core packages...
[01:53:52] W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/libc6_2.27-3ubuntu1_arm64.deb
[01:53:52] W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/libc6_2.27-3ubuntu1_arm64.deb is at fault)
[01:53:52] <<< deploy
```

Here is the debootstrap.log

```Selecting previously unselected package libc6:arm64.
(Reading database ... 364 files and directories currently installed.)
Preparing to unpack .../libc6_2.28-10_arm64.deb ...
ERROR: Your kernel version indicates a revision number
of 255 or greater.  Glibc has a number of built in
assumptions that this revision number is less than 255.
If you\'ve built your own kernel, please make sure that any
custom version numbers are appended to the upstream
kernel number with a dash or some other delimiter.

dpkg: error processing archive /var/cache/apt/archives/libc6_2.28-10_arm64.deb (--install):
 new libc6:arm64 package pre-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/libc6_2.28-10_arm64.deb
```

It seems to a problem with newer kernels. Found this from a quick google search, page was down but wayback machine had archived it.

https://web.archive.org/web/20040810052307/http://www.dreamflow.nl/mt/archives/000012.html

It tells that libc6 checks for kernel version from /proc/sys/kernel/osrelease . 

Also found this 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987266

which suggests that this bug is fixed in libc6_2.31-14 (20 Apr 2021)

**Comment by Practicalbutterfly5** [comment]
Update : Installing debian testing branch actually installs the latest libc and solves the issue.

**Comment by HyperLYP** [comment]
I also encountered this problem while installing ubuntu 18.04 on an Android R device. So maybe I can rename the kernel version to fix it?

**Comment by HyperLYP** [comment]
Wow！It really works ！I compiled the kernel and just changed the kernel version like this.
![Uploading Screenshot_20211031-153501_内核管理.png…]()

**Comment by HyperLYP** [comment]
Wow! It really works! I compiled the kernel and just changed the kernel version like this.
![Screenshot_20211031-153501_内核管理](https://user-images.githubusercontent.com/63620765/139573302-a6072c6c-3dd1-44c4-8735-4015a28b36dc.png)

**Comment by Mahoo12138** [comment]
Just install from the repository can avoid this issue

**Comment by Practicalbutterfly5** [comment]
> Just install from the repository can avoid this issue

Repositories are not up to date. They are still on Ubuntu 18.04.

Simply installing debian testing branch installs bookworm for me.
