### ISSUE TITLE
linux deploy failed to download package

### ISSUE THREAD

**Issue by serranof** [meefik/linuxdeploy#131]
Downloaded LinuxDeploy from GooglePlay
Install worked but 1 package was not downloaded - gave warning
stop install
install again
Install worked but 1 package was not downloaded - a different package than before
Did this 4 times and each time a different package would not install.
examples: 
W: Couldn't download package sed (ver 4.2.1-10 arch armhf)
W: Couldn't download package ifupdown (ver 0.7.8 arch armhf)
W: Couldn't download package libcomerr2 (ver 1.42.5-1.1 arch armhf)
W: Couldn't download package initscripts (ver 2.88dsf-41+deb7u1 arch armhf)

The warning at each install tells me the program will not run properly so I need to find a way to do a complete install

At each install I did a STATUS and every time the status was the same.  

> > > begin: status 
> > > Linux Deploy version: 1.4.6-110 
> > > Android version: 4.3 
> > > Device: Sony SGP311 
> > > CPU: ARMv7 Processor rev 2 (v7l) 
> > > MemTotal: 1819036 kB 
> > > SwapTotal: 0 kB 
> > > SELinux: yes 
> > > Support loop device: yes 
> > > Supported file systems: ext2 ext3 ext4 fuseblk texfat vfat 
> > > Active system: unknown 
> > > Running services: 
> > > - SSH: no 
> > > - VNC: no 
> > >   Mounted parts on Linux: 
> > > - / 
> > >   Available mount points: 
> > > - /system: 0.8/2.0 GB (ext4) 
> > > - /data: 5.5/11.4 GB (ext4) 
> > > - /mnt/idd: 0.0/0.0 GB (ext4) 
> > > - /cache: 0.5/0.5 GB (ext4) 
> > > - /lta-label: 0.0/0.0 GB (ext4) 
> > > - /mnt/shell/emulated: 5.5/11.4 GB (fuse) 
> > > - /storage/emulated/legacy: 5.5/11.4 GB (fuse) 
> > > - /storage/removable/sdcard1: 50.8/59.4 GB (texfat) 
> > > - /storage/emulated/0: 5.5/11.4 GB (fuse) 
> > > - /storage/emulated/0/Android/obb: 5.5/11.4 GB (fuse) 
> > > - /storage/emulated/legacy: 5.5/11.4 GB (fuse) 
> > > - /storage/emulated/legacy/Android/obb: 5.5/11.4 GB (fuse) 
> > >   Available partitions: 
> > > - /dev/block/mmcblk1p1: 63.8 GB (HPFS/NTFS) 
> > >   <<< end: status 

I hope some one would help me... I don't know anything about Linux 

Thank you

Felipe Serrano
serranof@ispali.com

**Comment by phupqpr** [comment]
yeah. trust like me

**Comment by shakil720** [comment]
I have a problem please help me 
[00:48:49] Requires superuser privileges (root).
[00:48:57] >>> stop
[00:48:58] The container is not mounted.
[00:48:58] <<< stop
[00:51:10] >>> deploy
[00:51:10] :: Installing bootstrap/rootfs ... 
[00:51:10] Checking installation path ... done
[00:51:10] Making new disk image (2047 MB) ... done
[00:51:14] Making file system ... done
[00:51:14] Mounting partitions: 
[00:51:14] / ... done
[00:51:14] /proc ... done
[00:51:14] /sys ... done
[00:51:14] /sys/fs/selinux ... done
[00:51:14] /dev ... done
[00:51:14] /dev/pts ... done
[00:51:14] /dev/shm ... done
[00:51:14] :: Installing bootstrap/kalilinux ... 
[00:51:15] I: Retrieving InRelease 
[00:51:18] I: Retrieving Packages 
[00:51:56] I: Retrieving Packages 
[00:57:24] E: Couldn't download dists/kali-rolling/main/binary-armhf/Packages
[00:57:24] <<< deploy
I tried many time but every time I will fail
Please some one help me

**Comment by eirkkk** [comment]
http://ftp.hands.com/kali  😎😎

**Comment by ghost** [comment]
I don't know if it's related to the problem, but after several attempts, with failure to download random packages installing Ubuntu bionic, I disabled the "Track network changes" option. It worked for me.

(google translate from portuguese)
