### ISSUE TITLE
Port it to Proot

### ISSUE THREAD

**Issue by dontknowhy** [meefik/linuxdeploy#1315]
i only have a HONOR device 
so i can't ROOT
please port linux deploy to Proot
I don't mind Proot's limitations 
thanks

**Comment by UsernameForTheWin** [comment]
older version already supports proot

**Comment by UsernameForTheWin** [comment]
the last version to support it was 2.4.1

**Comment by dontknowhy** [comment]
> the last version to support it was 2.4.1

i found it…
but i need the latest version support Proot
QAQ

**Comment by dontknowhy** [comment]
> the last version to support it was 2.4.1

There's definitely something wrong with my IQ…
![Screenshot_20220511_125350.jpg](https://user-images.githubusercontent.com/85813508/167771816-46feff18-16d8-4bf6-9537-07c0c847342d.jpg)

**Comment by UsernameForTheWin** [comment]
well i think using termux+termux-x11 is gonna be better than ld proot

**Comment by dontknowhy** [comment]
> well i think using termux+termux-x11 is gonna be better than ld proot

but termux-x11 is REALLY UNSTABLE

**Comment by UsernameForTheWin** [comment]
well what about sparkle i was able to use it on termux without root plus it is really smooth

**Comment by dontknowhy** [comment]
> well what about sparkle i was able to use it on termux without root plus it is really smooth

i need your help
QAQ
i can't login the sparkle's ftp server
and the github doesn't have any release (doesn't have apk)
also gitlab blocked me…
please try to send the apk file in this issue, if the apk file is too large, please compress it.
(i am unable to use Google Drive and other cloud drives that are not in China. sorry )

**Comment by dontknowhy** [comment]
> > well what about sparkle i was able to use it on termux without root plus it is really smooth
> 
> i need your help
> QAQ
> i can't login the sparkle's ftp server
> and the github doesn't have any release (doesn't have apk)
> also gitlab blocked me…
> please try to send the apk file in this issue, if the apk file is too large, please compress it.
> (i am unable to use Google Drive and other cloud drives that are not in China. sorry )

also
how can i init system in proot?(how do the INIT works in LinuxDeploy)

**Comment by UsernameForTheWin** [comment]
which one do you need exactly? The old version is already on the xda thread by the author so imma send latest ver

**Comment by dontknowhy** [comment]
> which one do you need exactly? The old version is already on the xda thread by the author so imma send latest ver

the newest nersion
and it's driver

**Comment by UsernameForTheWin** [comment]
https://forum.xda-developers.com/attachments/sparkle-old-apk.5418423/

**Comment by UsernameForTheWin** [comment]
Driver https://forum.xda-developers.com/attachments/pcm_sparkle-tar-gz.5418421/

**Comment by UsernameForTheWin** [comment]
well if you want audio then you dont need it u can just use pulseaudio from termux
https://github.com/meefik/linuxdeploy/issues/1297

**Comment by UsernameForTheWin** [comment]
imma upload latest ver later

**Comment by dontknowhy** [comment]
> imma upload latest ver later 

i can't load it
QAQ
i havn't root…

**Comment by UsernameForTheWin** [comment]
ofc it wont work if u directly press start but i know a way to make it work without root

**Comment by UsernameForTheWin** [comment]
My first time writing a how to so forgive me for mistakes
now first go to mounts and add /data and click start

open sparkle app and tap edit user.sh
now delete everything in it and click save

now ssh in to your distro and type 
sudo apt install nano xwayland && nano sparkle.sh
paste these into it
#!/bin/bash 
set -e 
XDG_RUNTIME_DIR=/data/data/com.sion.sparkle/files Xwayland &
sleep 1
export DISPLAY=:0
~/.xinitrc
now go to sparkle and click start and type sh sparkle.sh

**Comment by dontknowhy** [comment]
> My first time writing a how to so forgive me for mistakes
> now first go to mounts and add /data and click start
> 
> open sparkle app and tap edit user.sh
> now delete everything in it and click save
> 
> now ssh in to your distro and type 
> sudo apt install nano xwayland && nano sparkle.sh
> paste these into it
> #!/bin/bash 
> set -e 
> XDG_RUNTIME_DIR=/data/data/com.sion.sparkle/files Xwayland &
> sleep 1
> export DISPLAY=:0
> ~/.xinitrc
> now go to sparkle and click start and type sh sparkle.sh

noting works…
did you remember i havn't root?

**Comment by UsernameForTheWin** [comment]
huh i remember tryin it yesterday without root in termux and it did work

**Comment by UsernameForTheWin** [comment]
press the start button in sparkle before you do these
Try
sudo rm sparkle.sh && nano sparkle.sh
and paste these in
#!/bin/bash
set -e
XDG_RUNTIME_DIR=/tmp Xwayland &
sleep 1
export DISPLAY=:0
~/.xinitrc

**Comment by dontknowhy** [comment]
> press the start button in sparkle before you do these
> Try
> sudo rm sparkle.sh && nano sparkle.sh
> and paste these in
> #!/bin/bash
> set -e
> XDG_RUNTIME_DIR=/tmp Xwayland &
> sleep 1
> export DISPLAY=:0
> ~/.xinitrc

nothing works
I'll just wait for the Termux-X11 to settle down...

**Comment by UsernameForTheWin** [comment]
I see

**Comment by dontknowhy** [comment]
> I see
> 

i have a problem:
how does LinuxDeploy's init works?

**Comment by UsernameForTheWin** [comment]
Its a script that starts when you press start
If you are asking how to use it then:
Check the init box in menu and type what you want in /etc/rc.local

**Comment by UsernameForTheWin** [comment]
im not sure if it would work without root
