### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by ghost** [meefik/linuxdeploy#133]
When trying to install Kali Linux, any command fails. I fixed a bunch of errors, but here's the latest:

Updating configuration file ... done.
sh: <stdin>[1]: /storage/extSdCard/linuxdeploy/bin/linuxdeploy: can't execute: Permission denied.

Samsung Galaxy Tab 3 Lite (SM-T110)

Thanks,
Alex

**Comment by OwnageIsMagic** [comment]
troubles with permissions while installation of environment
this might fix this
cd /data/data/ru.meefik.linuxdeploy/
chmod -R 777 linux

**Comment by tangbozhi1** [comment]
I'm get the same problem,Do you finish it?
