### ISSUE TITLE
Feature Request: How to miracast the linux screen?

### ISSUE THREAD

**Issue by nitinjs** [meefik/linuxdeploy#1344]
How to miracast the linux screen?
Futuristic: TV as a remotely connected monitor via miracast
and bluetooth/RF keyboard and mouse connected to the linux 

```
android phone with linux as a CPU
BT/RF keyboard and mouse
TV as a monitor
Speakers? TV already has it
```

every android phone with Samsung dex but wireless, isn't it? 
![image](https://github.githubassets.com/images/icons/emoji/unicode/1f440.png)

**Comment by MatejMagat305** [comment]
if you want to make bluetooth connection from chroot linux i will wish you luck, becouse it is a still android device and I do not know how to it work for "native" ..........., but if you want have mouse and keyboard it is working via android pairing ...., I was trying this long time ago ...

**Comment by nitinjs** [comment]
not bluetooth connection from chroot linux

maybe mouse/kb can be connected to linux with `USB over IP`
but then we require some hardware(arduino kind of) where we connect the bt/rf dongle

**Comment by nitinjs** [comment]
@MatejMagat305 I found a way, termux running proot-distro with xrdp, then on the same wifi network I can rdp from TV having BT mouse and keyboard connected
