### ISSUE TITLE
aid_inet as root user and init.d scripts

### ISSUE THREAD

**Issue by jrmurad** [meefik/linuxdeploy#135]
I have a rooted RK3188 device running Android 4.2 with wifi-only networking (http://www.timingpower.com/android-mini-pc-rk3188). I intend to use it as a Ubuntu mail server.

Several services can't seem to be started through /etc/init.d. Adding "root" and their associated users to aid_inet fixed some of them but not all.

$ sudo -i
# grep inet /etc/group

aid_inet:x:3003:jason,messagebus,www-data,mysql,postgres,root,amavis

For example:
# amavisd-new debug

aware, LANG="en_US.UTF-8"
Jul 30 13:45:54.157 samwise.thriess.com /usr/sbin/amavisd-new[531]: user=, EUID: 107 (107);  group=, EGID: 110 110 (110 110) *********\* note the missing 3003. why? something to do with amavis creating a chrooted jail? **********
...
Jul 30 13:45:54.242 samwise.thriess.com /usr/sbin/amavisd-new[531]: (!)Net::Server: 2014/07/30-13:45:54 Can't connect to TCP port 10024 on 127.0.0.1 [Permission denied]\n  at line 92 in file /usr/share/perl5/Net/Server/Proto/TCP.pm

What it looks like when it works, run as non-root user:
# su - amavis

$ /usr/sbin/amavisd-new debug

Jul 30 13:47:33.053 samwise.thriess.com /usr/sbin/amavisd-new[1899]: user=107, EUID: 107 (107);  group=, EGID: 110 109 110 3003 (110 109 110 3003)
Jul 30 13:47:33.139 samwise.thriess.com /usr/sbin/amavisd-new[1899]: Net::Server: Binding to TCP port 10024 on host 127.0.0.1

Another failing program:
# freshclam

ClamAV update process started at Wed Jul 30 13:51:25 2014
WARNING: Can't query current.cvd.clamav.net
WARNING: Invalid DNS reply. Falling back to HTTP mode.
Reading CVD header (main.cvd): WARNING: Can't get information about db.local.clamav.net: Temporary failure in name resolution
WARNING: Can't read main.cvd header from db.local.clamav.net (IP: )

A warning from spamd:
# spamd

Jul 30 13:53:06.779 [6006] warn: logger: failed to add syslog method: logger: syslog initialization failed

I don't know if these things are related or whether there's an easy fix. Any help would be appreciated.

**Comment by enekux** [comment]
Did you ever found the solution for starting amavisd-new?

I am having the same issue...

To fix "freshclam" just do:

usermod -G aid_inet clamav

Thank you and regards,
