### ISSUE TITLE
Arch Linux installation failed with`Installation type` set to `Directory`

### ISSUE THREAD

**Issue by MaZED-UP** [meefik/linuxdeploy#1365]
I tried installing Ubuntu the same way but it fails unless I choose the `File` option.
> I've only tried  `File`. Other options are overwhelming for me (for now).

I have BusyBox installed, by the way. Is the problem related to how permissions work in Android?

![Linux Deploy.jpeg](https://github.com/meefik/linuxdeploy/assets/59477548/07b16847-c5b7-4c0c-841f-2c1455581948)

**Comment by MaZED-UP** [comment]
I managed to install Arch Linux in `${ENV_DIR}/rootfs/arch` but I still want to know how can I install it in `/sdcard/Linux/arch` 😁

My phone's system is a custom Android 13 ROM (AOSP).

**Comment by supechicken** [comment]
It is impossible to do it since the Android shared storage (mounted on `/sdcard`, aka `/storage/emulated/0`) disallowed `exec` (mounted with `noexec` option), which prevents executables from running.

**Comment by MaZED-UP** [comment]
Alright. Thank you for the clarification.
