### ISSUE TITLE
Any chance of getting newer versions of ubuntu?

### ISSUE THREAD

**Issue by AyrtonRicardo** [meefik/linuxdeploy#1378]
Is there any chance that we are getting newer versions of Ubuntu directly from your hub?

**Comment by yejianfengblue** [comment]
see https://github.com/meefik/linuxdeploy/issues/1228

https://github.com/meefik/linuxdeploy/issues/1260#issuecomment-860256044

**Comment by AyrtonRicardo** [comment]
> see #1228
> 
> [#1260 (comment)](https://github.com/meefik/linuxdeploy/issues/1260#issuecomment-860256044)

thanks for the point, the conf change is great trick. 
Currently I've updated to 22.04 and created a rootfs from it, but that conf trick is waaaay faster. Thank you!
