### ISSUE TITLE
Please,  bro explain where is the fucking mounted container!?  I already  have spent two days searching for that mounted locations. 

### ISSUE THREAD

**Issue by ustargordoy** [meefik/linuxdeploy#1386]
Please, who knows explain where is the fucking mounted container!?  I already  have spent two days searching for that mounted location. Thanks a lot!!

**Comment by griha41** [comment]
> Please, who knows explain where is the fucking mounted container!?  I already  have spent two days searching for that mounted location. Thanks a lot!!

Wow, wow, wow, dude!
The container is the Linux OS that you're using on your Android OS.

So if you wish to edit or change something in your Linux OS (LOS), you shall mount the LOS image into your Android OS (AOS), and the demount (after editing).

But you shall keep in mind that location of you LOS would be based on location of installation of your AOS and it would be the: /system/media/0/... or somewhere there, or another Linux drive where is located the root folder of your Linix Deploy.

I hope it's helped a little...

**Comment by ustargordoy** [comment]
> > Please, who knows explain where is the fucking mounted container!?  I already  have spent two days searching for that mounted location. Thanks a lot!!
> 
> Wow, wow, wow, dude! The container is the Linux OS that you're using on your Android OS.
> 
> So if you wish to edit or change something in your Linux OS (LOS), you shall mount the LOS image into your Android OS (AOS), and the demount (after editing).
> 
> But you shall keep in mind that location of you LOS would be based on location of installation of your AOS and it would be the: /system/media/0/... or somewhere there, or another Linux drive where is located the root folder of your Linix Deploy.
> 
> I hope it's helped a little...

Thank  a lot for you help bro! I have had really  mad, now it everything ok! 
In fact this programm is the best, and every thing developed in good and clever way! Thanks for this great work! Wish all the best!!

**Comment by griha41** [comment]
> > > Please, who knows explain where is the fucking mounted container!?  I already  have spent two days searching for that mounted location. Thanks a lot!!
> > 
> > Wow, wow, wow, dude! The container is the Linux OS that you're using on your Android OS.
> > 
> > So if you wish to edit or change something in your Linux OS (LOS), you shall mount the LOS image into your Android OS (AOS), and the demount (after editing).
> > 
> > But you shall keep in mind that location of you LOS would be based on location of installation of your AOS and it would be the: /system/media/0/... or somewhere there, or another Linux drive where is located the root folder of your Linix Deploy.
> > 
> > I hope it's helped a little...
> 
> Thank  a lot for you help bro! I have had really  mad, now it everything ok! 
> In fact this programm is the best, and every thing developed in good and clever way! Thanks for this great work! Wish all the best!!  

Agreed @meefik had done the awesomest job!
