### ISSUE TITLE
Unable to install debian

### ISSUE THREAD

**Issue by lnoxsian** [meefik/linuxdeploy#1388]
Just as the name states unable to install debian stable on linux deploy as i have set up linux deploy with the settings
![settings](https://github.com/meefik/linuxdeploy/assets/97118089/4bbd3f6c-2b52-4354-a65e-2a37ccb4bd73)
and the error is
![error](https://github.com/meefik/linuxdeploy/assets/97118089/321499bc-2881-4183-a6ba-01e672357821)
the version of busybox is
![busybox](https://github.com/meefik/linuxdeploy/assets/97118089/c31df015-5801-4272-a10c-ddb422347867)
and the app version is 
![Screenshot_20240603-211951_Linux_Deploy](https://github.com/meefik/linuxdeploy/assets/97118089/a32bdcb3-3f26-45d5-9c96-ce1f4521dc00)
all the settings are default and the device is running lineage os with magisk as the root permission manager so its as far i know its reproducable on one more device with the same exact error so know of any fixes

**Comment by griha41** [comment]
Based on your submitted screenshots, I can say that you have an issue with Debian decencies itself.
The installer reports that there's the packages that couldn't be resolved by name or version, the branch of debian that you trying to download is required the package version that's not existing at the brach.

I don't know how you can resolve it without rebuilding the package froms source and validate each step of installation.

I'm not sure but might be the presented packages that's not required by standard installer but required by installer system that's provided in the application and that's the base of issue as I'm thinking.

**Comment by lnoxsian** [comment]
So i do know about the dependencies being outdated does updating or editing the scripts in linux-deploy-cli found in the /data/data folder help change the output ? i dont know whats gonna happen also thanks for you help

**Comment by griha41** [comment]
> So i do know about the dependencies being outdated does updating or editing the scripts in linux-deploy-cli found in the /data/data folder help change the output ? i dont know whats gonna happen also thanks for you help

Hm if you know where's it's located then we can mess it up as we prefer to see!
We can use Android Studio for the file access or even Android itself because there's one path that can grant us access to International memory (/media/0/Android/data)
With root eights we can override the files in /data/data with Root Explorer App for example. I'm sorry I have only the Android 14 (31 API) and app is quite outdated, but I think bit later I'll try to mess up with it, maybe I'll able to find how to override "recipes" and make Debian working again on LInux Deploy, but it's required some time to waste :D

**Comment by lnoxsian** [comment]
i do have root access so i can edit the /data/data/meefik.something.* folder i think updating debootstrap and fixing some scripts can i guess get debian working on the bright side alpine works perfectly last i checked also trying to run the seperate cli program on my local machine to find any changes in between the app and the linuxdeploycli

**Comment by griha41** [comment]
> i do have root access so i can edit the /data/data/meefik.something.* folder i think updating debootstrap and fixing some scripts can i guess get debian working on the bright side alpine works perfectly last i checked also trying to run the seperate cli program on my local machine to find any changes in between the app and the linuxdeploycli

I can give my head in work if i don't onow what to do. Anyway I need to explore what do i can do and only then we could fine the possible solution :-)

**Comment by griha41** [comment]
> i do have root access so i can edit the /data/data/meefik.something.* folder i think updating debootstrap and fixing some scripts can i guess get debian working on the bright side alpine works perfectly last i checked also trying to run the seperate cli program on my local machine to find any changes in between the app and the linuxdeploycli

Mate I'd found the way how we can shook it.
On my A14, the path of profile is: /data/user/0/ru.meefik.linuxdeploy/files/config/linux conf
This fule is current profile for Linux distro.

If check it's content you'll found the line: SUITE="buster"
Buster is completely outdated and if we'll try to switch to the "bookworm" that migh be that everything starts without the errors.

DON'T USE THE STABLE NAME, because it might require the wrong decencies!

I'm performing current actions for the configuration.

1st of all prepare the confirmation though the App then stip it.

2. Perform the configuration.
3. Press stop button when configuration is done.
3. Started the installation (in img container in device memory/Linux/Debian_Bookworm.img, I'd setted 10Gb size).
4. Awaiting when it's finished (it requires some time)
P.S. Idk I met troubles that can't download some pkgs...

Maybe you'll be bit more lucky :D

**Comment by lnoxsian** [comment]
There the files are same for the linuxdeploy-cli and the files folder in the /data/data/ru.meefik.linuxdeploy also i have changed the default config for the linux image to bookworm but it did not work

**Comment by griha41** [comment]
> ok will do and try it

Failed each time on different packages this time libext2fs2 & isc-dhcp-common, I guess it's because of my WiFi...

**Comment by lnoxsian** [comment]
it just shows the same error
![image](https://github.com/meefik/linuxdeploy/assets/97118089/32367769-5bc7-42fc-bc15-fcf51122b8b1)

**Comment by griha41** [comment]
> it just shows the same error
> ![image](https://github.com/meefik/linuxdeploy/assets/97118089/32367769-5bc7-42fc-bc15-fcf51122b8b1)
> 

No man you have more luck then me it's almost configured, you can connect over ssh and complete the installation

**Comment by lnoxsian** [comment]
there is a deploy.sh in the files/include/extra/ssh it has the command for intalling openssh-server using apt let me add the depends for openssh in it

**Comment by griha41** [comment]
> there is a deploy.sh in the files/include/extra/ssh it has the command for intalling openssh-server using apt let me add the depends for openssh in it

Hm I'm passed after 6 retires to the configuration process, let's a wait xD

**Comment by lnoxsian** [comment]
![image](https://github.com/meefik/linuxdeploy/assets/97118089/2435f7b5-e4b7-4096-8f7c-646385bafc36)
i guess openssh-server is not installed so it just show configured but is unable to launch since there is no openssh :)

**Comment by griha41** [comment]
> ![image](https://github.com/meefik/linuxdeploy/assets/97118089/2435f7b5-e4b7-4096-8f7c-646385bafc36)
> i guess openssh-server is not installed so it just show configured but is unable to launch since there is no openssh :)

Cmon it's not balck-jack, let's not guessing let's break it though xD

**Comment by lnoxsian** [comment]
the fun thing is the cli project has a updated debootstrap with templates for [bookworm](https://github.com/meefik/linuxdeploy-cli/tree/master/include/bootstrap/debian/debootstrap/scripts) to be honest when trying this last year it just show libhogweed usermerge error in between the core install so this is a really big step up

**Comment by griha41** [comment]
> the fun thing is the cli project has a updated debootstrap with templates for [bookworm](https://github.com/meefik/linuxdeploy-cli/tree/master/include/bootstrap/debian/debootstrap/scripts) to be honest when trying this last year it just show libhogweed usermerge error in between the core install so this is a really big step up

I think we need to dig another file. Also what's arch do you trying to install, I'm trying amd64 and you?

**Comment by lnoxsian** [comment]
> > the fun thing is the cli project has a updated debootstrap with templates for [bookworm](https://github.com/meefik/linuxdeploy-cli/tree/master/include/bootstrap/debian/debootstrap/scripts) to be honest when trying this last year it just show libhogweed usermerge error in between the core install so this is a really big step up
> 
> I think we need to dig another file. Also what's arch do you trying to install, I'm trying amd64 and you?

I am using my android device and a vm for x86 also there are some docs for [linuxdeploy-cli](https://meefik.github.io/2016/01/26/linuxdeploy-cli-on-pc/)

**Comment by griha41** [comment]
> > > the fun thing is the cli project has a updated debootstrap with templates for [bookworm](https://github.com/meefik/linuxdeploy-cli/tree/master/include/bootstrap/debian/debootstrap/scripts) to be honest when trying this last year it just show libhogweed usermerge error in between the core install so this is a really big step up
> > 
> > I think we need to dig another file. Also what's arch do you trying to install, I'm trying amd64 and you?
> 
> I am using my android device and a vm for x86 also there are some docs for [linuxdeploy-cli](https://meefik.github.io/2016/01/26/linuxdeploy-cli-on-pc/)

It's irrelevant, what Debian Distribution arch are you using? :)

The question is important coz if we are trying the same arch then issue in Debian side, if different archs then in Lin Dep :)

**Comment by lnoxsian** [comment]
> > > > the fun thing is the cli project has a updated debootstrap with templates for [bookworm](https://github.com/meefik/linuxdeploy-cli/tree/master/include/bootstrap/debian/debootstrap/scripts) to be honest when trying this last year it just show libhogweed usermerge error in between the core install so this is a really big step up
> > > 
> > > 
> > > I think we need to dig another file. Also what's arch do you trying to install, I'm trying amd64 and you?
> > 
> > 
> > I am using my android device and a vm for x86 also there are some docs for [linuxdeploy-cli](https://meefik.github.io/2016/01/26/linuxdeploy-cli-on-pc/)
> 
> It's irrelevant, what Debian Distribution arch are you using? :)

aarch arm64 also x86_64 :)

**Comment by griha41** [comment]
> > > > > the fun thing is the cli project has a updated debootstrap with templates for [bookworm](https://github.com/meefik/linuxdeploy-cli/tree/master/include/bootstrap/debian/debootstrap/scripts) to be honest when trying this last year it just show libhogweed usermerge error in between the core install so this is a really big step up
> > > > 
> > > > 
> > > > I think we need to dig another file. Also what's arch do you trying to install, I'm trying amd64 and you?
> > > 
> > > 
> > > I am using my android device and a vm for x86 also there are some docs for [linuxdeploy-cli](https://meefik.github.io/2016/01/26/linuxdeploy-cli-on-pc/)
> > 
> > It's irrelevant, what Debian Distribution arch are you using? :)
> 
> aarch arm64 also x86_64 :)

If your's devise is x86 then you shall try the i386 or even arm86 for installation.

Coz configuration of packages may through erros and we are failde to install...

**Comment by lnoxsian** [comment]
My android device is arm64 its just that i am trying it on both amd64 also

**Comment by griha41** [comment]
> My android device is arm64 its just that i am trying it on both amd64 also

Ah i see then i missed that :)
Ok nevertheless we need dig bit deeper

**Comment by gitmanbloggus** [comment]
I'm on a kindle and I cant install older versions of debian, I want to as ubuntu is quite limited on arm for some reason, 
armv7 android 2.3.7 (CM7)
amazon kindle fire 1st gen
every time I try to install, since the archive keyring is being used, it throws an error and I cant ssh into it because it can't verify the packages

**Comment by gitmanbloggus** [comment]
I'm on a kindle and I cant install older versions of debian, I want to as ubuntu is quite limited on arm for some reason, 
armv7 android 2.3.7 (CM7)
amazon kindle fire 1st gen
every time I try to install, since the archive keyring is being used, it throws an error and I cant ssh into it because it can't verify the packages

**Comment by griha41** [comment]
> I'm on a kindle and I cant install older versions of debian, I want to as ubuntu is quite limited on arm for some reason, 
> armv7 android 2.3.7 (CM7)
> amazon kindle fire 1st gen
> every time I try to install, since the archive keyring is being used, it throws an error and I cant ssh into it because it can't verify the packages

Maybe you shall find the way, and if i didn't missed bubuntu sended to the hell Debian and said I'm self-sufficient hooker so layoff from my daddy and went off, so idk why are you asking why is that shift isn't working in the theme about Debian...

**Comment by lnoxsian** [comment]
> I'm on a kindle and I cant install older versions of debian, I want to as ubuntu is quite limited on arm for some reason, 
> armv7 android 2.3.7 (CM7)
> amazon kindle fire 1st gen
> every time I try to install, since the archive keyring is being used, it throws an error and I cant ssh into it because it can't verify the packages

to be honest all the debian ubuntu and even kali uses the same shell scripts for making the chroot enviorment also i just have a armv7 android 7 device which on being tested just showed the ssh package depends error

**Comment by Akegarasu** [comment]
I encountered the exact same issue. After troubleshooting, I managed to fix it. This project is no longer maintained, and its built-in debootstrap script (used for building Debian's root filesystem) no longer supports the latest stable version. After replacing it with a new debootstrap, the installation works fine.

**Comment by griha41** [comment]
> I encountered the exact same issue. After troubleshooting, I managed to fix it. This project is no longer maintained, and its built-in debootstrap script (used for building Debian's root filesystem) no longer supports the latest stable version. After replacing it with a new debootstrap, the installation works fine.

Hm, sounds fine, may you just a bit detailed describe from where and to where what did you placed. That might be that we can find the way how to resolve it.

Heck man I even will try it on my A14 for the test :D

**Comment by Akegarasu** [comment]
replace like this pr https://github.com/meefik/linuxdeploy-cli/pull/30
or you can simply try my [ci build](https://github.com/akibanzu/Linuxdeploy-Pro/actions/runs/9974854683)

**Comment by lnoxsian** [comment]
thanks for the help so just by adding a zstdcat binary fixed the whole issue that is in turn done by using the updated linuxdeploy-cli script thanks a lot im trying out your app build thanks for providing the build it works
