### ISSUE TITLE
configuration files not found + sudo dosent help me update

### ISSUE THREAD

**Issue by lioneez** [meefik/linuxdeploy#142]
I had a few problems with running a linux system on my android with linux deploy, so I need to describe what I did to try and solve it.
First I rooted my phone with my PC and a program called Odin, and in root check it says that my phone is rooted.
Than I tried to install kali-linux, but linux deploy didnt create the img file at first even when i currected the path and runned ENV update in the linux deploy options.
To fix this I needed to update ENV and write this little code in the terminal emulator app on my phone:
$ su-
# cd /data/data/ru.meefik.linuxdeploy/linux/bin
# rm sh chroot
# ln s- /system/bin/mksh sh
# ln s- /system/binx/busybox chroot

And after this I need to re enter linux deploy and I can install and start the img without any problems from these two apps.
Lastly when I entered kali-linux I found out that I couldnt do anything in the terminal there, the main thing that bothers me is that I couldnt apt-get update even with sudo, in the first case it stated I didnt had premission, but with sudo this poped up:
PERM_ROOT: setresuid (0, -1, -1): premission denied.
So to fix this I tried to change the VNC app, but it didnt work.
Than I tried to delete linux.img with its files and re install linux deploy, but now in linux deploy no matter what I do it says:
Configuration file not found
Updating the ENV dosent work, and the thing with $ su- dosent do anything too.
This is a harsh first expirience with linux, and I am really out of ideas to how to fix all these problems, but for now I cant even run linux deploy right.
Please help me, I am 24/7 on this already with no progress at all.
My android is 3.4v galaxy s3, please help.

**Comment by MaryGrosholz** [comment]
I did all steps but when I go to install kali I get...
/data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy[1708]: chroot: not found
