### ISSUE TITLE
Kali Linux running from SD Card

### ISSUE THREAD

**Issue by Baloothebear1979** [meefik/linuxdeploy#147]
Im wondering if anybody has tried altering the recovery image file to allow for Kali to be run directly from the SD Card. I have succesfully installed kali using linux deploy on my galaxy note 10.1 and installed it to ExtSdCard. I would much prefer to have kali running from the sd card as i have a 64gb card with nothing but the Kali installed on it. Is there any way to alter the recovery img file to instruct that tablet to boot the linux from the sdcard ?? Would appreciate any help on this, having linux deploy to debug the image is great but would much prefer to run the image outside of android.

**Comment by twaik** [comment]
You can try to use https://github.com/meefik/linuxdeploy-cli inside the recovery.
