### ISSUE TITLE
Why framebuffer does not work in linuxdeploy as my own script does?

### ISSUE THREAD

**Issue by felonwan** [meefik/linuxdeploy#152]
The frame buffer does work using my own scripts, but it does not work in linux deploy.
I just stop the android graphical interfaces and then using the command:
Xorg :0 vt1
and other things are all the same.

My script to start linux desktop env:
# !/bin/bash
###### 

#           start Linux Distro. after Chroot  
# Usage：xfinit start_desktop_cmd [synergy server IP]  
# Note: "synergy server IP" is not necessary  
#       start_desktop_cmd examples: startlxde, startkde  
# Author：felonwan@gmail.com                                    
###### 
###### 

#  set start_desktop_cmd and synergy server IP     #
###### 

if [ $# -eq 1 ]; then
  dsk=$1
elif [ $# -eq 2 ]; then
  dsk=$1
  syg=$2
else
  echo -e "Usage: xfinit [cmd] [ip]\n cmd--command to start desktop, e.g. openbox-session.\n syg--synergy server ip.\n"
  exit 1
fi
###### 

#     Env variables     #
###### 

export USER=root
export PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin:/usr/local/sbin:/usr/games:$PATH
export TERM=linux
export HOME=/root
export DISPLAY=:0
hostname LinuxPad
###### 

#     start linux desktop environment     #
###### 
# nohup udevd -d 1>udev.log 2>udev.err &

nohup Xorg :0 vt1 1>x.log 2>x.err &
if [ $# -eq 2 ]; then
  nohup synergyc -n pad $syg 1>syn.log 2>syn.err &
fi
sleep 1s
$dsk
# /bin/bash -i

The xorg.conf file:

Section "ServerLayout"
  Identifier "Layout0"
  Screen "Screen0"
  InputDevice "touchscreen" "CorePointer"
EndSection

Section "InputDevice"
  Identifier "touchscreen"
  Option "Device" "/dev/input/event2" #linuxdeploy
  #Driver "multitouch"
  #Driver "evdev"
  Driver "mtrack"
  #Driver "tslib"
EndSection

Section "Device"
  Identifier "Card0"
  Driver "fbdev"
  Option "fbdev" "/dev/graphics/fb0" #linuxdeploy
  Option "Rotate" "UD"  #or "CW" or "CCW"
EndSection

Section "Screen"
  Identifier "Screen0"
  Device "Card0"
  DefaultDepth 24
  SubSection "Display"
    Depth 24
  EndSubSection
EndSection

**Comment by twaik** [comment]
You can alter Xorg cmdline in Framebuffer method settings.
