### ISSUE TITLE
Disk image created at 0 bytes

### ISSUE THREAD

**Issue by KeithBronstrup** [meefik/linuxdeploy#156]
Trying to create a 4GB image, the app is executing the following:
dd if=/dev/zero of=/storage/emulated/0/ubuntu1404.img bs=1048576 seek=4096 count=0
which, of course, results in a 0 byte image being created. This cause mke2fs to fail, which, of course, causes mounting to fail.

The correct command should be:
dd if=/dev/zero of=/storage/emulated/0/ubuntu1404.img bs=1048574 count=4096

**Comment by meefik** [comment]
Maximum image size 4095 MB for FAT.
