### ISSUE TITLE
Use existing linux.img file

### ISSUE THREAD

**Issue by Efreak** [meefik/linuxdeploy#171]
I switch distros and reinstall on a semi-regular basis, and would like for Linux Deploy to detect that linux.img already exists and use it. Perhaps by adding an option, by popping up a prompt, or in any other manner. I do not have enough room on my device to store more than one distro. Downloading packages is fast and easy due to use of apt-cacher-ng, I'll submit a pull request later with instructions for setting it up on windows(!)

**Comment by meefik** [comment]
Change Properties -> Installation path and execute Properties -> Reconfigure
