### ISSUE TITLE
Fails on Samsung Galaxy Note 4

### ISSUE THREAD

**Issue by CyberShadow** [meefik/linuxdeploy#180]
The installation script fails at the "Making new disk image" stage, with "Permission denied".

Upon closer inspection, I discovered that any external command started from the `linuxdeploy` script fails to run. Even a `whoami` added to the very top of the script fails to run with "Permission denied". As the script did not set `-e`, it was simply that all commands before that failed as well, and the script ignored the failures and kept running until the point where it explicitly checked the exit code.

I've tried to toggle "Built-in shell" to no avail.

Please consider enabling `-e` at the top of the script, it makes debugging much easier. Not doing so is the equivalent of `ON ERROR RESUME NEXT` in Visual Basic.

**Comment by CyberShadow** [comment]
OK, looks like it's working after I updated the environment after disabling "Built-in shell". It would be good to detect this situation though, e.g.

```bash
whoami > /dev/null || (
    echo "Can't run commands, try toggling 'Built-in shell' and update environment"
    exit 1
)

set -e
...
```

**Comment by meefik** [comment]
See #60

**Comment by CyberShadow** [comment]
Yes, I solved my problem - I left this open because it is possible to detect and handle this problem much better in the script.
