### ISSUE TITLE
Install Kali Linux without internet

### ISSUE THREAD

**Issue by mvpcom** [meefik/linuxdeploy#184]
Can I Install Kali Linux with android deploy offline(without internet)? I downloaded kali-linux-1.0.9a-armhf.img but I can't install it in android with LinuxDeploy. This application need access internet unfortunately, I think?!? Please make installation offline and with downloaded packages and releases.

**Comment by meefik** [comment]
See the guide http://meefik.ru/blog/2015/01/31/linuxdeploy-kali-linux/

**Comment by kshubham506** [comment]
can i install kali linux on android using inux deplay without having internet on phone...I can download the files by pc..

**Comment by twaik** [comment]
You can download Kali Linux armhf rootfs and install it in LD interface. http://cdimage.kali.org/kali-2018.2/kali-linux-light-2018.2-armhf.img.xz

**Comment by happysmash27** [comment]
What is LD interface? 

My internet was bad, constantly resetting the download with the default downloader, so I redownloaded a Gentoo image with Aria2c, but LinuxDeploy will not accept the image.
