### ISSUE TITLE
Don't work with all issue

### ISSUE THREAD

**Issue by ikkiphoenix** [meefik/linuxdeploy#186]
Hello, 

I try to run linuxdeploy on my tablet GalaxyTab4. The last problem that i had after i see all issue is /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy : not such file or directory
Like i see with others issue, i try to do : sudo chmod -R 777 and it works but the issues don't resolve and i have the same error. 
So i want see if the file exist, so i go with cd, and ls -l to see permission and all is good. 
I don't understand why i have this problem.. ? 
Thanks to help me.

**Comment by meefik** [comment]
Please, show the result of the command:

    ls -l /data/data/ru.meefik.linuxdeploy/ /data/data/ru.meefik.linuxdeploy/linux/ /data/data/ru.meefik.linuxdeploy/linux/bin/

May be helpful uncheck Settings -> Built-in shell and run Settings -> Update ENV. Also see #60
