### ISSUE TITLE
What I should do for getting working framebuffer?

### ISSUE THREAD

**Issue by ghost** [meefik/linuxdeploy#192]
Hello. Linux deploy is working on my device with xsdl xserver. Problem start's when I want to use framebuffer - it don't work, only black screen. Device is Galaxy Tab 2 10.1 GT-5110 with CM11 and default kernel for it.
I tried this command's for testing fbdev:
su
cat /dev/urandom > /dev/graphics/fb0
sh: cat: <stdout>: No space left on device
cat /dev/urandom > /dev/graphics/fb1
sh: cat: <stdout>: No space left on device
There are only two files in /dev/graphics/ - fb0 and fb1.
What I can do to get it working? I can change kernel and ROM to what I want, also, if it's needed, I will try my nerdo skill's to compile new kernel. I heard that it's must be vt, fb, or fbdev enabled. What word shortcut is correct for that?

**Comment by twaik** [comment]
Try to use "Force refresh" option.
