### ISSUE TITLE
Sorry, but what is root password for ubuntu vivid xfce

### ISSUE THREAD

**Issue by zhangtemplar** [meefik/linuxdeploy#193]
Hi, all,

I know all the arguments that using root is not safe, blah, blah. But no one will ever try this app at all, if he is not an experienced user, right?

I tried to use "android" to log in with "changeme", everything is fine, except when I try to install some new app, e.g., "xfce4-terminal", which doesn't exist in the installation!!!. I tried the command "sudo apt-get install xfce4-terminal". But it reports the error "sudo: PERM_ROOT (0, -1, -1) PERMISSION DENIED".

After some search, this problem is related to that "android" doesn't belong to sudoer. Some posts online has some solution, however all of them requires "sudo" permission first.

Then the question is, how can I do "sudo" if I don't have "sudo" permission. One solution is to log in as root user, and add "android" to "sudoer". But I don't have the root password.

Please help!

**Comment by zhangtemplar** [comment]
I have found the solution for myself.

In settings, change the user name from "android" to "root", then choose reconfigure, which will set your root password to "changeme". 

You can then start the server and logging in as root with the password "changme", where you can do everything you want, e.g., install vim via "apt-get install vim".

After you done with root, please stop the server and in the setting change user from "root" to "android".

**Comment by versluis** [comment]
Thanks for this tip, I had the same question. I had assumed we could never be root and instead had to do everything via sudo (which on my system never asked for a password).

**Comment by zhangtemplar** [comment]
@versluis 

The sudo doesn't work properly here. We need to switch to root user. You can check my blog for more information: http://167.88.47.13/?p=245

**Comment by starkruzr** [comment]
Switching from "android" to "root" in that configuration item doesn't seem to log one in as root. Do we have a better way to do this yet?

**Comment by zhangtemplar** [comment]
@starkruzr that's weird, it works for me.

**Comment by CrazyJ36** [comment]
Didn't work for me either, same "sudo" error. If it matters, I've used this app fine for A long time on Android, though this time I'm using A Samsung Galaxy S6 edge SM-G925P (arm64 proccessor, UFS 2.0 storage) this might help. Problem may be with Ubuntu itself also

**Comment by arjunrsekhar** [comment]
Use 'sudo su' too get root access
