### ISSUE TITLE
SSH and VNC stdin: is not a tty

### ISSUE THREAD

**Issue by spiler79** [meefik/linuxdeploy#194]
I installed Kali Linux with linux deploy, then I proceeded with reconfigure. Now if I press START, I get these errors:

![screenshot_2015-02-17-22-42-36](https://cloud.githubusercontent.com/assets/11050202/6237838/74fd36a0-b6f6-11e4-958b-c33913f95f63.png)

**Comment by hattwj** [comment]
Ditto here. Guess i should not have done that. Any fixes?

**Comment by twaik** [comment]
`stdin: is not a tty` is just a warning. Not an issue.
