### ISSUE TITLE
How do I install mate as desktop?

### ISSUE THREAD

**Issue by dyharlan** [meefik/linuxdeploy#196]
How do I install mate as desktop after selecting other in desktop environment? I am using Debian wheezy armhf and XServer XSDL as X client

**Comment by rbrewer123** [comment]
I'm running the ubuntu install.  I think I did something like `sudo apt-get install mate` and after everything was installed I set my `DISPLAY` and run `mate-session` to start it up.

**Comment by twaik** [comment]
Addition: add the line "mate-session" to the ~/.xinitrc for autostart.
