### ISSUE TITLE
X: user not authorized to run the X server, aborting

### ISSUE THREAD

**Issue by wilecoyote2015** [meefik/linuxdeploy#198]
Hello,
On my Galaxy Note 10.1 using cyanogenmod 12, starting a fresh archlinux install with framebuffer fails with the debug message: 
X: user not authorized to run the X server, aborting

I was able to solve the issue following this tip: 
karuppuswamy.com/wordpress/2010/09/26/how-to-fix-x-user-not-authorized-to-run-the-x-server-aborting/

**Comment by twaik** [comment]
Looks like the bug was fixed in the latest LD release.
