### ISSUE TITLE
Execv: exec format error

### ISSUE THREAD

**Issue by wilecoyote2015** [meefik/linuxdeploy#199]
Hello!
I have tried to install Arch Linux as i686 on my Galaxy Note 10.1 (Linux Deploy seem to support that using qemu according to the notes of a recent update), however after the installation of additional packages I get an error that reads like Execv: exec format error. 

Has anyone else faced this pdoblem yet?

**Comment by meefik** [comment]
Need support binfmt_misc in Linux kernel.
