### ISSUE TITLE
Making new disk image (512 MB) ... fail 

### ISSUE THREAD

**Issue by gerroon** [meefik/linuxdeploy#200]
Hi

Nexus 7 CM11 And 4.4.4

Release resources ... done 
Unmounting partitions:  
/proc/sys/fs/binfmt_misc ... skip 
Disassociating loop device ... done 
<<< end: stop 
Updating environment ... mkdir failed for /data/data/ru.meefik.linuxdeploy/linux, File exists
rm: can't remove '/system/bin/linuxdeploy': Read-only file system
ln: /system/bin/linuxdeploy: File exists
done
Updating configuration file ... done
Updating configuration file ... done

> > > begin: install 
> > > Checking mount points ... done 
> > > Checking installation path ... done 
> > > Making new disk image (512 MB) ... fail 
> > > <<< end: install 

thanks

**Comment by twaik** [comment]
Fixed in the latest LD release.
