### ISSUE TITLE
Frame Buffer missing xsession.pid

### ISSUE THREAD

**Issue by aensley** [meefik/linuxdeploy#203]
I am trying to run an Ubuntu 14.10 (utopic) image file-based system using Frame Buffer.

I have a custom kernel with all VT options enabled, root (obviously), the latest BusyBox pro version, and SELinux set to permissive mode.

I selected Desktop Environment, SSH Server, and X Server as components to install. Everything installed well, but when I start it, all I get is a black screen. Below is the output of my start action (with debug info turned on):

```
[16:36:23] >>> begin: start
[16:36:23] Mounting partitions: 
[16:36:23] / ... done
[16:36:23] /proc ... done
[16:36:23] /sys ... done
[16:36:23] /sys/fs/selinux ... done
[16:36:23] /dev ... done
[16:36:23] /dev/pts ... done
[16:36:23] /dev/shm ... done
[16:36:23] /proc/sys/fs/binfmt_misc ... done
[16:36:23] Updating configuration: 
[16:36:23] dns ... done
[16:36:23] mtab ... done
[16:36:23] Starting services: 
[16:36:23] SSH :22 ... stdin: is not a tty
[16:36:27]  * Starting OpenBSD Secure Shell server sshd
[16:36:27]    ...done.
[16:36:27] done
[16:36:27] Frame Buffer ... cat: can't open '/data/data/ru.meefik.linuxdeploy/linux/mnt/tmp/xsession.pid': No such file or directory
[16:36:28] done
[16:36:28] <<< end: start 
```

What's odd is that there is nothing in the `/data/data/ru.meefik.linuxdeploy/linux/mnt/` directory while this image is running; not even the `tmp` directory.

Any ideas? It seems like it may be a problem with X Server not starting successfully, but I don't see any X errors.
### Edit

I fiddled around some more. I tried disabling the "Use built in BusyBox" option and updating the environment. After that; nothing worked at all "mksh not found". But, when I re-enabled that option and updated the environment again, the xsession.pid error went away! However, my screen is still blank and now I have no errors to go on.

My GUI settings are:
- **Display**: 1
- **DPI**: 124
- **Video device**: /dev/graphics/fb0
- **Input device**: /dev/input/event8
- **X options**: empty
- **Freeze Android UI**: Don't freeze

I'm using a Samsung Galaxy Note Pro, so event8 is the stylus.

**Comment by flamadiddle** [comment]
Any suggestions on what my next steps should be?

**Comment by sunboy2** [comment]
Hi!
Try enabling the debug mode in the settings so that more useful information will be printed.

Seems like you are running into this error:
https://github.com/meefik/linuxdeploy/issues/198

The solution mentioned in the link worked for me.

**Comment by flamadiddle** [comment]
@sunboy2 The output above is with debug mode turned on. There is no X error at all, so I at least can't conclusively say that that *is* my issue, but it might be. I will give your fix a try. Thanks!

**Comment by meefik** [comment]
The warning "xsession.pid: No such file or directory" can be ignored. This does not affect the operation.
