### ISSUE TITLE
Question: Why the 4GB size limitation?

### ISSUE THREAD

**Issue by versluis** [meefik/linuxdeploy#206]
Dear meefik,

THANK YOU SO MUCH for this app - it's working great on my Nook Tablet! 

I'm curious: why does the image have the 4GB limitation? Is there a way to increase it? Is it possible to use the remaining space as a second partition and mount it (I haven't tried it yet, just thinking out loud).

Thanks again ;-)

**Comment by versluis** [comment]
Answer: FAT32 only allows a maximum file size of 4GB. 
And all the while I could have sworn the card was formatted in EXT4 - but alas it was not. As soon as I can convince my device to mount EXT4 formatted cards I'm sure it'll be different ;-)

**Comment by Fiksdal** [comment]
Some devices allow exFAT.
