### ISSUE TITLE
Port forwarding and remote access

### ISSUE THREAD

**Issue by dimti** [meefik/linuxdeploy#210]
Hi

I dont known - how resolve my problem:

Linux deploy on ArchLinux (192.168.0.32)
Remote server on linux (ex. 8.8.8.8)
My computer on local area network (192.168.0.44)

I say to linux in my tablet:
ssh -R 222:localhost:22 root@8.8.8.8
... and i say on remote server:
ssh -R 4000:localhost:4000 root@localhost -p 222

And wow. I can connect from android system to local port 127.0.0.1:4000 (ssh tunneling redirect to remote server 8.8.8.8)

But.. i can not connect to 192.168.0.32:4000 from my local area network (from 192.168.0.44 ip - my windows computer on local network)

I try use iptables on linux system on my tablet:
iptables -t nat -I OUTPUT --src 0/0 --dst 127.0.0.1. -p tcp --dport 5000 -j REDIRECT --to-ports 4000

If try to connect from linux-tables - it work:
telnet localhost 5000
...
Yes baby, how you?
Escape character is...

But i unable connect to 192.168.0.32:5000 from local area network

How to fix it and what generate this problem?

**Comment by lbdroid** [comment]
Uh... your objective here is to create a tunnel that lets you connect from 192.168.0.44 --> 192.168.0.32:4000 and have that redirect to 8.8.8.8's localhost:4000?

If so, what is the point of the double reverse tunnel?

Just do a single forward tunnel, like;
ssh -NL 4000:localhost:4000 8.8.8.8

Even more straightforward... you don't need to use a chroot linux on your android device to accomplish this.

Use openssh;
https://github.com/lbdroid/Android_SSH
https://github.com/lbdroid/Android-Binaries/blob/master/Android_SSH.apk

In the tunnel page (menu drawer --> tunnels) create a new tunnel as;
ssh server: 8.8.8.8
ssh port: 22
ssh user: whatever
tunnel host: localhost
tunnel host port: 4000
tunnel local port: 4000
Add it, install the public key to your server, and toggle hold (dot turns green in 0-5 seconds) to create the tunnel.

**Comment by dimti** [comment]
Thanks for the other solution for this reason.

I try ssh - N -T -L 4000:localhost:4000 8.8.8.8 (on linux deploy)
But i unable to connect from android app to my local port 4000

But, if i send command
ssh -R 228:localhost:22 root@remote.server
And on remote machine:
ssh -R 4000:localhost:4000 root@localhost -p 228
Then I successfully connect to localport 4000 from android app (app: nomachine). I use remote desktop via tunneled ports

Why is use -NL, i unable to connect from another system to this port (on linux deploy i success connect to localport 4000, if use -NL)

**Comment by lbdroid** [comment]
Android can get a little bit funny when binding ports for non privileged users. Try running it as root.

**Comment by lbdroid** [comment]
Also, you can try listening on a port between 32768 and 61000.

**Comment by dimti** [comment]
Fire

**Comment by kevincaradant** [comment]
Hi guys,  sorry to write here,  But maybe you can help me.  I have some problem to connect at a tvheadend server to manage télévision.  I have install that on a raspberry with linuxdeploy but when I want to connect at my adress : http://192.x.x.x:9981,  i have something like connexion refused from chrome. ERR_CONNEXION_REFUsed. Maybe a forward to fix this problem ?  Sorry I m a noob for the iptable so à little help will be great :).  Thanks you

**Comment by dimti** [comment]
Yes. You can.
On raspberry in linuxdeploy:
ssh -R 9981:localhost:9981 root@another_linux_machine
Problem number 1: Need another linux machine.

I try install OpenSSH on andorid 4.4, but no luck. May be it help to use forwarding ports directly to android (as onto another linux machine).

You try also bind other prot in your app. ibdroid says - try port between 32768 and 61000

**Comment by kevincaradant** [comment]
Thank you :) but to summarize because I m not sure to understand ,  i write on the raspberry pi in linuxdeploy the command : ssh -R 9981:localhost:9981.  And then on the other Linux computer at home,  what do I to do ? And  I dont understand the goal  to use that :You try also bind other prot in your app. ibdroid says - try port between 32768 and 61000.  The port is 9981 for tvheadend so I can t use an other port ? Thank you for your patience with me :)

**Comment by dimti** [comment]
ssh -R.. needed for translate local port 9981 to another linux machine (not android, really PC). And, after setup redirecting ports you can try connect to another_linux_machine_ip:9981 from web browser.

ssh -R 9981:localhost:9981 root@another_linux_machine_ip

Check in your /etc/ssh/sshd_config on all computers (Configuration SSH-Server)
AllowTcpForwarding yes
GatewayPorts yes (i not sure really need this option, but...)

How to configure other port in tvheadend. Hmm. I not sure. May be help redirecting ports from local to local machine:

ssh -R 32981:localhost:9981 root@localhost

**Comment by kevincaradant** [comment]
On my computer under linux , i haven't this file : Check in your /etc/ssh/sshd_config. 

Only  /etc/ssh/ssh_config and if at the end of the file , i write that :     AllowTcpForwarding yes
    GatewayPorts  then i have this error : /etc/ssh/ssh_config: line 55: Bad configuration option: allowtcpforwarding
/etc/ssh/ssh_config: terminating, 1 bad configuration options

So i can't write your options :/. Is it a problem ? 

On linuxdeploy , i have your file "/etc/ssh/ssh_config" , so i added the  two lines at the end of the file but i don't know if that change something or not.

How can I setup redirecting ports ? With the internet box ? or with an other way ? what is the process ? Sorry but with me , to understand , it's step by step :)

And to finish : ssh -R 32981:localhost:9981 root@localhost  in linuxdeploy , ask me a password for the user root@localhost's. But i don't know him .... :/.

**Comment by dimti** [comment]
5) Default password on linuxdeploy: changeme
4) Strange. sshd_config exists on my PC (if OpenSSH Server is installed )
AllowTcpForwarding - default to "yes" on my PC. Dont worry. Port redirects may be turned on default on your PC machine. If no - then you make correct to settings your ssh-server on linux-PC
3) Need practice. I use redirect ports feature one year. And i do not understand how it works (
3) If you need translate local port on remote machine - use -R option. Arguments: First port - port on remote machine. Second port - your local port, which needed translate to remote machine.
If you needed translate remote port on remote machine onto local port on local machine, use -N -T -L options. Arguments: First port - port on local machine, Second port - port on remote machine, which needed translated to local machine.
Sorry, if i misled you

**Comment by kevincaradant** [comment]
"4) Strange. sshd_config exists on my PC (if OpenSSH Server is installed )" i just come to install openssh-server. So now, i have configure the file like linuxdeploy.

Then i tried that : ssh -R 32981:localhost:9981 android@localhost ( replace "root" by "android" because the password is "changeme" in this case ) 
But when i tried to connect me from my PC , i saw that on the linuxdesploy console : 
                                   - connect_to localhost port 9981: failed.

I sorry to be so noob but really it's complicated and i don't know what understand with the error that i mentioned just before, i think i'm not so far to find the solution but it's not good in the moment :/

**Comment by dimti** [comment]
May be in this moment (when you connect from PC to android), service daemon of your app needed started?

Dont worry, port redirect still work if start or not start your service on port 9981. Try connect from PC: telnet localhost 32981 after started service of your app.

Port forwarding and accessibility ports from other computers in local network - theme with secret. Needed education... I also have problems, but i dont known how to fix it

**Comment by kevincaradant** [comment]
"service daemon of your app needed started" what service ? tvheadend server is running in this moment so it works :)

After : ssh -R 32981:localhost:9981 android@localhost 
           ssh -R 9981:localhost:9981 kevin@another_linux_machine_ip

Check in your /etc/ssh/sshd_config on all computers (Configuration SSH-Server)
AllowTcpForwarding yes
GatewayPorts yes 

ssh -R 32981:localhost:9981 root@localhost where a password is require , but i don' know him.

Nothing , in the moment , i have the rror in web browser : Unable to connect on ip_adress_raspi:998 or even an other :/

**Comment by dimti** [comment]
Dialogs with question - need for testing and write output here in topic

Way 1:
Andro: ssh -R 9981:localhost:9981 kevin@another_linux_machine_ip
PC(?): telnet localhost 9981

Way 2:
Andro: ssh -R 32981:localhost:9981 android@localhost 
Andro(?): telnet localhost 32981
PC(?): telnet android_ip 32981

ps: You needed restarted sshd daemon after change configuration files.
What the output:
Andro(?): telnet localhost 9981

**Comment by kevincaradant** [comment]
Way 1:
Andro: ssh -R 9981:localhost:9981 kevin@another_linux_machine_ip

![way1](https://cloud.githubusercontent.com/assets/6093175/9017308/6b8cc2dc-37d6-11e5-8854-fa0354785927.PNG)


PC(?): telnet localhost 9981
Trying 127.0.0.1...
connected to localhost
Escape charactere is '];
connexion closed by foreign host

Way 2:
Andro: ssh -R 32981:localhost:9981 android@localhost 
![way2](https://cloud.githubusercontent.com/assets/6093175/9017403/e29763f0-37d6-11e5-8ebc-96b13e53a49a.PNG)

Andro(?): telnet localhost 32981
![image](https://cloud.githubusercontent.com/assets/6093175/9017411/f2439daa-37d6-11e5-8cf0-7cee9d45c95b.png)



PC(?): telnet android_ip 32981
unable to connect to remote host : connexion refused

ps: You needed restarted sshd daemon after change configuration files.
What the output:
Andro(?): telnet localhost 9981
![way3](https://cloud.githubusercontent.com/assets/6093175/9017559/a8640656-37d7-11e5-893f-9d79b458729b.PNG)

**Comment by dimti** [comment]
Re: Andro(?): telnet localhost 9981 (last screenshot)
Our service on 9981 port not listen that port (or service not started correctly). All operations with redirecting ports - does not make sense, if main service not work

Andro(?): netstat -tpln

**Comment by kevincaradant** [comment]
My result ;)   : 

![capturefdsfsd](https://cloud.githubusercontent.com/assets/6093175/9064354/655a706e-3acc-11e5-9102-1ae20a0d658a.PNG)

**Comment by dimti** [comment]
After start your service (com.google.and?) - your system started listen port 37067. But i not see port 9981 on "active servers internet connections".
May be, "tvheadend" not started correctly or not fully started, or tvheadend listen port 37067, but no 9981

**Comment by kevincaradant** [comment]
yes you right so i don't understand because , the service says , it starts correctly but i don't see the port opened. All port opened are kodi and ssh but it's on android , not on linuxdeploy. Maybe do I have to configure that on linuxdeploy ? :(

**Comment by kevincaradant** [comment]
it's weird but look that : 

when i used this command :

![image](https://cloud.githubusercontent.com/assets/6093175/9082185/954c64ee-3b62-11e5-952f-a19df706663c.png)

**Comment by dimti** [comment]
I always liked the idea of the media house. But when I tried the event organized by the broadcast audio signal via the network, I ditched all the routers in the home ...

**Comment by nzeenzeen** [comment]
Hi dimti ! First. I can't speak english well.Please understand me
I have some ploblem and want to ask you about linuxdeploy network and tvheadend server.
I have android TV box (4.4.2 kitkat) and installed linuxdeploy.
I made Linux as Debian-Wheezy and install tvheadend on it.
It works. I can connect admin page (http://192....:9981) and config.
tvheadend setting is simple. but i met a problem.
iptv channel source url is rtp://233.....:60000.
I can watching iptv by url rtp://233.....:60000 on android(kitkat)-kodi, mxplayer etc.
But tvheadend on Debian can't scan that iptv url.
debian (on linuxdeploy) can't scan rtp protocol???
or just tvheadend's problem???
or network interface problem between linuxdeploy and android ???
Please help me.

**Comment by dimti** [comment]
@nzeenzeen 
Sorry . i do not use tvheadend and i not understant how to work RTP-protocol.
Try telnet 233..... 60000. What see?
