### ISSUE TITLE
Everytime I install ubuntu it always ends up with an error saying: errors were encountered while processing.

### ISSUE THREAD

**Issue by dyharlan** [meefik/linuxdeploy#215]

**Comment by meefik** [comment]
Execute after the installation: Properties - Reconfigure.

**Comment by dyharlan** [comment]
I did. It still had the same error.

**Comment by meefik** [comment]
Ubuntu version, Anroid version, Installation type (loop, sdcard part)?

**Comment by dyharlan** [comment]
Both Trusty and precise, Pac-Man ROM Stable CM11 Based of Android 4.4.4. Loop Image.

**Comment by MhSaadany** [comment]
I have the same problem.

I get this after reconfigure: 
No such file or directory
[04:45:06] dpkg: error processing openssh-server (--configure):
[04:45:06]  subprocess installed post-installation script returned error exit status 1
[04:45:06] Errors were encountered while processing:
[04:45:06]  openssh-server
[04:45:06] E: Sub-process /usr/bin/dpkg returned an error code (1)

Ubuntu precise on lollipop 5.1.1 CM12 and the device is GT-I9300

**Comment by AnguisCaptor** [comment]
Having the exact same error here, Nexus 6, tried it with all the ubuntu versions

Errors were encountered while processing:
 open-ssh server
E: Sub-processes /usr/bin/dpkg returned an error code (1)
<<< end install

**Comment by oraant** [comment]
Having same question. Seem's like it's opening for a year.

**Comment by twaik** [comment]
Solved in the latest LD release.
