### ISSUE TITLE
[request] Android distribution

### ISSUE THREAD

**Issue by merpelicous** [meefik/linuxdeploy#217]
Correct me if I'm wrong, but I believe android is linux. Would it be possible to have an android distribution and a bootable android img?

**Comment by lbdroid** [comment]
It may or may not be possible. The thing is, this does not boot a second kernel -- it shares the kernel that runs Android. Android uses a custom IPC mechanism called "binder". I think if you run another parallel Android, you would run into bad things happening when the two parallel instances of android are sharing a binder.

**Comment by twaik** [comment]
Android is not the GNU/Linux distribution.
