### ISSUE TITLE
Getting audio working in chroot under KitKat 4.4.2 

### ISSUE THREAD

**Issue by ShapeShifter499** [meefik/linuxdeploy#223]
Hi,

I have a LG Volt and everything is so nice but I cannot get audio working.   I have Arch Linux installed in the chroot.  When I try to run alsamixer I get "cannot load mixer controls: Invalid argument".  I've done a bit of googling but I haven't found any solutions.  Do you have any ideas how to get audio working?

**Comment by dyharlan** [comment]
Sound can be a bit of a pain in chroot environments for a very long time. Some people had success with sound but others won't. When I got sound working. (Or at least the programs didn't throw andy errors.) It ramped up my cpu to like 75%-90% usage. I am using GS2 Pac-Man rom (CM11, AOKP and Paranoid android all-in-one rom before switching to wizzedkat.)

**Comment by ShapeShifter499** [comment]
@dyharlan What did you do exactly to get sound working for you?   So far I was able to mess with the volume but that was only good for other apps and not the chroot.

**Comment by dyharlan** [comment]
I installed alsa made some modifications to asound.conf. But after testing a wav file, it sorta worked but again it just overloaded my cpu.

**Comment by ShapeShifter499** [comment]
I'm not sure what modifications to make to my system but I did try a kde install and that flat out causes hard reboots when ran

**Comment by ShapeShifter499** [comment]
I HAVE AUDIO!! Here is what I did. After disabling consolekit pulseaudio module inside /etc/pulse/default.pa  (afaik you don't really need it)   pulseaudio starts up on my chroot automatically with a "dummy output" and a "dummy output monitor".   I next run "pactl load-module module-simple-protocol-tcp rate=48000 format=s16le channels=2 source=auto_null.monitor record=true port=8000"    with auto_null.monitor being the "dummy output monitor".   I can play the stream that is created back using "simple protocol player"  from the play store  https://play.google.com/store/apps/details?id=com.kaytat.simpleprotocolplayer     I notice no issues with playback and I can play multiple audio sources inside the chroot at the same time if I wanted to. On the android side the app acts like a music player so anything else trying to play music will kill it but other sounds like system notifications are fine.

**Comment by radosd** [comment]
I'll write here some comments for getting audio inside chroot. Hope it'll be useful for someone.

my device is nexus 4, debian stable (no pulseaudio)

first - find out which of the devices in /proc/asound/card0/ is used for playing audio via speaker. I started playing tuneinradio stream from android - then grep -v closed

OK - so I know my audio is served via pcm14p.

Next - alsactl monitor - while starting playback from tuneinradio - I see:
card 0, #334 (2,0,0,SLIM TX3 MUX,0) VALUE
card 0, #364 (2,0,0,RX3 MIX1 INP2,0) VALUE
card 0, #365 (2,0,0,RX3 MIX1 INP1,0) VALUE
card 0, #372 (2,0,0,RX4 DSM MUX,0) VALUE
card 0, #271 (2,0,0,SLIMBUS_0_RX Audio Mixer MultiMedia5,0) VALUE

Then I searched inside sources of cyanogenmod:
https://github.com/CyanogenMod/android_device_lge_mako/blob/cm-13.0/mixer_paths.xml

looks quite similar:
`    <path name="speaker">
        <ctl name="SLIM_0_RX Channels" value="One" />
        <ctl name="RX3 MIX1 INP1" value="RX1" />
        <ctl name="RX3 MIX1 INP2" value="RX6" />
        <ctl name="RX4 DSM MUX" value="DSM_INV" />
        <ctl name="SLIM TX3 MUX" value="RMIX3" />
    </path>
`
So in fact - what was needed:
amixer sset 'SLIMBUS_0_RX Audio Mixer MultiMedia5' on
amixer sset 'SLIM TX3 MUX' 'RMIX3'
amixer sset 'RX3 MIX1 INP2' 'RX6'
amixer sset 'RX3 MIX1 INP1' 'RX1'
amixer sset 'RX4 DSM MUX' 'DSM_INV'

Then I may direct alsa to hw:0,14 and sound works fine. For line-out it's similar.

Can someone confirm it works also for other devices?

**Comment by dyharlan** [comment]
radosd, This looks confusing. Is there a step-by-step?

**Comment by dyharlan** [comment]
@radosd how did you perform the grep -v command?

**Comment by raghavsingh219** [comment]
Is there any way to enable sound in linux without pulseaudio ? Actually I m fed up of a lot of errors  and i need an easy way to enable sound on samsung galaxy tab 4 SM-t231.

**Comment by Aeysir** [comment]
I really want to get sound to work I know this is and old post but I'm so desperate. How did you use the grep -v command I cant get it to work. please any help is appreciated!

**Comment by radosd** [comment]
I no longer have the original device on which I was testing that. So here's the same, done on LG G2 (d802) - running lineageOS 14.1 weekly (android 7.1.2).

Debian stable in linuxdeploy, only one additional package installed (alsa-utils).

So first I start music on android and find which device is used:

`root@localhost:/proc/asound/card0# grep -v closed */sub0/status`
`pcm0p/sub0/status:state: RUNNING`

= pcm0p is used. 

`root@localhost:/proc/asound/card0# cat pcm0p/info`
`card: 0`
`device: 0`
`subdevice: 0`


= alsa device is hw:0,0

Next, I stop music, wait a moment, run # alsactl monitor, start music, stop music

`root@localhost:~# alsactl monitor`
`card 0, #563 (2,0,0,RX7 MIX1 INP1,0) VALUE`
`card 0, #58 (2,0,0,RX7 Digital Volume,0) VALUE`
`card 0, #441 (2,0,0,SLIMBUS_0_RX Audio Mixer MultiMedia1,0) VALUE`
`card 0, #441 (2,0,0,SLIMBUS_0_RX Audio Mixer MultiMedia1,0) VALUE`
`card 0, #58 (2,0,0,RX7 Digital Volume,0) VALUE`
`card 0, #563 (2,0,0,RX7 MIX1 INP1,0) VALUE`

Point here is to use amixer commands to mimic what android is doing. First 3 lines appeared when starting music, last 3 when stopping.

Only problem is that alsactl monitor is not actually showing the "VALUE". Last time I was looking in android sources for them - but there's a better way - asking amixer itself.

I have 3 controls to enable/disable (563,58,441), how are they named in amixer?

`root@localhost:~# amixer controls | egrep "numid=441,|numid=58,|numid=563,"`
`numid=58,iface=MIXER,name='RX7 Digital Volume'`
`numid=563,iface=MIXER,name='RX7 MIX1 INP1'`
`numid=441,iface=MIXER,name='SLIMBUS_0_RX Audio Mixer MultiMedia1'`

Now I can start music again and ask amixer for values:

`root@localhost:~# amixer cget numid=563,iface=MIXER,name='RX7 MIX1 INP1'`
`numid=563,iface=MIXER,name='RX7 MIX1 INP1'`
`  ; type=ENUMERATED,access=rw------,values=1,items=12`
`  ; Item #0 'ZERO'`
`  ; Item #1 'SRC1'`
`  ; Item #2 'SRC2'`
`  ; Item #3 'IIR1'`
`  ; Item #4 'IIR2'`
`  ; Item #5 'RX1'`
`  ; Item #6 'RX2'`
`  ; Item #7 'RX3'`
`  ; Item #8 'RX4'`
`  ; Item #9 'RX5'`
`  ; Item #10 'RX6'`
`  ; Item #11 'RX7'`
`  : values=5`

`root@localhost:~# amixer cget numid=58,iface=MIXER,name='RX7 Digital Volume'`
`numid=58,iface=MIXER,name='RX7 Digital Volume'`
`  ; type=INTEGER,access=rw---R--,values=1,min=0,max=100,step=0`
`  : values=67`
`  | dBscale-min=0.00dB,step=0.01dB,mute=0`

`root@localhost:~# amixer cget numid=441,iface=MIXER,name='SLIMBUS_0_RX Audio Mixer MultiMedia1'`
`numid=441,iface=MIXER,name='SLIMBUS_0_RX Audio Mixer MultiMedia1'`
`  ; type=BOOLEAN,access=rw------,values=1`
`  : values=on`

Value to set is shown as "values=x". Running the same commands when the music is NOT playing reveals the values for "music_stopped_state".

So, to setup linux chroot for music playback I can run (probably by shellscript):
`amixer cset numid=563,iface=MIXER,name='RX7 MIX1 INP1' 5`
`amixer cset numid=58,iface=MIXER,name='RX7 Digital Volume' 67`
`amixer cset numid=441,iface=MIXER,name='SLIMBUS_0_RX Audio Mixer MultiMedia1' on`

and direct alsa to hw:0,0 (via .asoundrc)

When finished playing, I run:
`amixer cset numid=441,iface=MIXER,name='SLIMBUS_0_RX Audio Mixer MultiMedia1' off`
`amixer cset numid=58,iface=MIXER,name='RX7 Digital Volume' 84`
`amixer cset numid=563,iface=MIXER,name='RX7 MIX1 INP1' 0`

to revert settings to original state. 

Similar concept applies for line-out/headphones. Just watch what android does via # alsactl monitor and do the same via amixer.

**Comment by Aeysir** [comment]
hmmm  when I do  "amixer controls | egrep "numid=441,|numid=58,|numid=563," " I get no output.

**Comment by nachum37** [comment]
@radosd all devices are closed...  what i can do?

**Comment by dyharlan** [comment]
@radosd when typing in grep -v closed in /proc/asound/card0, nothing appears.

**Comment by WilsonBradley** [comment]
Are there real instructions somewhere to get this running ?

**Comment by twaik** [comment]
See #56

**Comment by mirfatif** [comment]
This can help:
```
#!/bin/bash

sudo apt install alsa-utils

echo Play music or start recording and press enter.
read key

c=$(grep RUNNING /proc/asound/card*/pcm*/sub*/status | grep -o 'card[0-9]*' | grep -o [0-9]*) && echo "Card: $c"
p=$(grep RUNNING /proc/asound/card*/pcm*/sub*/status | grep -o 'pcm[0-9]*p' | grep -o [0-9]*) && { echo "Playback device: $p"; echo "i.e. alsa device is hw:$c,$p"; }
r=$(grep RUNNING /proc/asound/card*/pcm*/sub*/status | grep -o 'pcm[0-9]*c' | grep -o [0-9]*) && { echo "Recording device: $r"; echo "i.e. alsa device is hw:$c,$r"; }

echo
printf 'Stop playback / recording and press enter.'
read key

# alsactl doesn't seem to work when piped to grep
echo 'Start and stop playback / recording and observe values changes.'
sleep 3
echo 'Terminate when done.'
echo
trap 'pkill -1 alsactl' SIGINT
alsactl monitor

trap "kill $$" SIGINT
echo
printf 'Write Control Identifier (nmuid) of changed values with space: '
read -a val

for v in ${val[@]}
do
	printf 'Play music / start recording and press enter.'
	read key
	v1="$(amixer cget "$(amixer controls | grep "numid=${v},")" | grep ': values=' | cut -d= -f2)"
	printf 'Stop playback / recording and press enter.'
	read key
	sleep 3
	v2="$(amixer cget "$(amixer controls | grep "numid=${v},")" | grep ': values=' | cut -d= -f2)"

	if [ "$v1" = "$v2" ]; then
		echo "ERROR: No change in values detected for Control Identifier $v."
		continue
	fi

	V1="$(printf '%s\n%s' "$V1" "amixer cset $(amixer controls | grep "numid=${v},") $v1")"
	V2="$(printf '%s\n%s' "$V2" "amixer cset $(amixer controls | grep "numid=${v},") $v2")"
done

[ -z "$V1" ] || { printf '\n To start:'; echo "$V1"; }
[ -z "$V2" ] || { printf '\n To stop:'; echo "$V2"; }

```

**Comment by mirfatif** [comment]
@radosd brilliant work. Can we record sound in similar way?

**Comment by vlenircissrma** [comment]
Great app, thanks. 

Audio out was directly working on whyred Xiaomi red note pro. However I have problems to get audio in working (arecord, gst-launch1.0 alsasrc).

Doing alsactl monitor and launching a recorder in Android shows me the subdevice involved. However I cannot select the device through alsamixer or change the parameters using the amixer controls as suggested in an earlier post, no such control exists (amixer returns 2 simple mixer control master and capture with 2 numid switch and volume)

The card is sdm660-snd-card. Maybe with this card it is not possible to have audio in. Do you think it is an alsa problem ? A Linux deploy problem ? A driver for sdm660-snd-card not recognized ? What are your experiences with other phones? Are you able to record directly ? If yes with each model?

Thanks

**Comment by JanuszChmiel** [comment]
Dear advanced users and elite developers. What do you think about The following native .so library? May be, that it would be even possible to use ALSA directly even on non rooted Android devices thanks to it.
The Github tree with this .so library and even with prepared Alsa configuration files is available here.

The crucial question is, if this .so library is ARM or AArch64 Bit and if .so library do not depend on some .so library from The Exagear .apk package.
https://github.com/akbarri/ExaGear-SoundFix

**Comment by KiralyCraft** [comment]
I've taken the time to write a Python script which automates @radosd's process with the help of LLMs. It currently assumes the card is `card0`.

```python
import os
import subprocess
import time

def get_running_device():
    """Finds the first audio device in the RUNNING state by checking the status files."""
    proc_path = "/proc/asound/card0"
    
    # Loop over all status files in the subdirectories of /proc/asound/card0/
    for root, dirs, files in os.walk(proc_path):
        for file in files:
            if "status" in file:
                status_file_path = os.path.join(root, file)
                
                # Check the status file for a RUNNING state
                with open(status_file_path, 'r') as status_file:
                    for line in status_file:
                        if "RUNNING" in line:
                            # Extract the directory name as the device (e.g., pcm0p/sub0/status -> pcm0p)
                            relative_status_path = status_file_path.replace(proc_path, '')
                            return os.path.basename(relative_status_path.strip('/').split('/')[0])
    return None

def get_device_info(device):
    """Gets the card and device information from the device info file."""
    info_file_path = f"/proc/asound/card0/{device}/info"
    info = {}

    with open(info_file_path, 'r') as info_file:
        for line in info_file:
            if line.startswith("card:"):
                info['card'] = line.split(":")[1].strip()
            if line.startswith("device:"):
                info['device'] = line.split(":")[1].strip()
    
    return info

def alsactl_monitor(card_number, duration=10):
    """Runs 'alsactl monitor' for a given card and duration and captures its output."""
    process = subprocess.Popen(['alsactl', 'monitor'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    time.sleep(duration)  # Run it for the specified duration
    process.terminate()  # Terminate after the duration

    output, _ = process.communicate()
    return output.decode().splitlines()

def extract_control_info(monitor_output):
    """Extracts control numbers and names from the alsactl monitor output, starting from #NUMBER onwards."""
    controls = {}

    for line in monitor_output:
        if '#' in line:
            # Split the line at '#', extract the number and the rest of the description
            parts = line.split('#', 1)  # Split once at the first occurrence of '#'
            control_info = parts[1].strip()  # Get the part after '#'
            
            # Extract the control ID (the first number) and the control name (inside parentheses)
            control_id = control_info.split()[0]  # The first part is the ID (e.g., 573)

            # Extract the control name, which is inside the parentheses
            control_name = control_info.split('(', 1)[1].split(')', 1)[0].split(',')[3]  # Extract the name part
            
            controls[control_id] = control_name.strip()

    return controls

def run_amixer_cget(numid, control_name, card_number):
    """Runs the amixer cget command and fetches the value."""
    command = ['amixer', 'cget', f'numid={numid},iface=MIXER,name={control_name}', '-c', card_number]
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, _ = process.communicate()
    output_lines = output.decode().splitlines()

    # Look for the line containing 'values=' and extract its value
    for line in output_lines:
        if line.strip().startswith(': values='):
            value = line.split('=')[1].strip()
            return value  # Return the actual value
    return None


def main():
    input("Please start playing music, then press Enter...")

    # Get the device in RUNNING state
    running_device = get_running_device()
    if running_device:
        print(f"Device {running_device} is playing music...")

        # Get card and device information
        device_info = get_device_info(running_device)
        card_number = device_info['card']
        hw_device = f"hw:{card_number},{device_info['device']}"
        print(f"Using device: {hw_device}")

    input("Please pause the music and press Enter when done...")
    print("Prepare to start the music soon (NOT YET) ...")
    time.sleep(5)
    # Monitor ALSA controls and capture when user resumes playing music
    print(f"Start playing music NOW!")
    play_controls = alsactl_monitor(card_number, duration=10)
    play_control_info = extract_control_info(play_controls)

    print("ALSA control changes during music play:")
    for control_id, control_name in play_control_info.items():
        print(f"{control_id}: {control_name}")

    print(f"Prepare to stop playing music ...")
    time.sleep(2)
    print(f"Stop playing music NOW!")
    # Monitor ALSA controls again after user stops the music
    print(f"Monitoring ALSA controls on card {card_number} for 10 seconds again...")
    stop_controls = alsactl_monitor(card_number, duration=10)
    stop_control_info = extract_control_info(stop_controls)

    print("ALSA control changes after music stopped:")
    for control_id, control_name in stop_control_info.items():
        print(f"{control_id}: {control_name}")

    #========================================

    results_playing = {}
    results_stopped = {}
    input(f"Please start playing music and press Enter when done ...")
        # Fetch values for play controls
    for control_id, control_name in play_control_info.items():
        value = run_amixer_cget(control_id, control_name, card_number)
        results_playing[control_id] = {
            'name': control_name,
            'value': value
        }

    # Print results for play controls
    print("Play Control Values:")
    for control_id, info in results_playing.items():
        print(f"Control ID: {control_id}, Control Name: {info['name']}, Value: {info['value']}")

    input(f"Please stop playing music and press Enter when done ...")
    print("Waiting 5 seconds for controls to change for sure ...")
    time.sleep(5)
    # Fetch values for stop controls
    for control_id, control_name in stop_control_info.items():
        value = run_amixer_cget(control_id, control_name, card_number)
        results_stopped[control_id] = {
            'name': control_name,
            'value': value
        }

    # Print results for stop controls
    print("Stop Control Values:")
    for control_id, info in results_stopped.items():
        print(f"Control ID: {control_id}, Control Name: {info['name']}, Value: {info['value']}")


    print()
    # Example usage after fetching values for play_controls
    print("\nCommands to set values for playing:")
    for control_id, control_info in results_playing.items():
        print(f"amixer cset numid={control_id},iface=MIXER,name='{control_info['name']}' {control_info['value']} -c {card_number}")

    print("\nCommands to set values for stopping:")
    for control_id, control_info in results_stopped.items():
        print(f"amixer cset numid={control_id},iface=MIXER,name='{control_info['name']}' {control_info['value']} -c {card_number}")

if __name__ == "__main__":
    main()
```

I've yet to improve upon it, but so far it seems to return things correctly.
