### ISSUE TITLE
Any way to do orderly shutdown (other than stop in gui)?

### ISSUE THREAD

**Issue by brindleware** [meefik/linuxdeploy#225]
/etc/halt 
telinit 0
shutdown -y -g0 now
uadmin 2 0

and all typical *nix variations dont provide any shutdown actions.

Would love to have a way to an orderly shutdown from within the environment.
Thanks!

**Comment by dyharlan** [comment]
You can't because the image isn't even bootable from an emulator and It only contains the Linux files. No boot image, grub, etc... And

**Comment by brindleware** [comment]
So an unmount from the android side that started the chroot would do it?

Hmmmm...

I am running it on an android tv box, and without a clean shutdown (ie remove box power) ive seen fs corruption a time or two.

So how about a non gui trigger? Ie touch a file on the android side or sdcard?

Thanks

**Comment by dyharlan** [comment]
You can create a script that can umount the mounts in the img file. but first Kill the PIDs first. Not really sure, since I don't start and kill Linux Deploy manually.

**Comment by brindleware** [comment]
see my note on #352
