### ISSUE TITLE
Ubuntu With No Thing

### ISSUE THREAD

**Issue by OoMiDOoO** [meefik/linuxdeploy#234]
I have installed ubuntu - trusty - xfce 
And it's come with NO THING o.O ..
There is a desktop okay but theres no terminal 
When i try to open web browser it says :
_____
Field to execute dedufult web browser
Input/outpot error
_____
solution ?
(i need also to install some another programs like photo editor or something)

^
sorry for my english :) ..
i am newbie in linux :3

**Comment by florian-184-de** [comment]
Try to reinstall Ububtu. Lubuntu 14.04 trusty LTS (LXDE) on armhf/armv7l works fine on my tablet.
I had also problems with not installed programmes. It was because my internet connection has been split up for a small time and the installation aborted.

**Comment by florian-184-de** [comment]
Ubuntu*

**Comment by OoMiDOoO** [comment]
Yuk .. Okay I will test it :) ..
I will give you the updates ..

**Comment by OoMiDOoO** [comment]
Ookkaayy ..
It's sort a working ._. ..
It's perfectly working and very fast unlike Xfce ..
And the terminal is exist
Every thing is okay ..
But i can't open web browser ! ..
I am thinking of download google chrome on the android and move it to ubuntu some how
^
or re install it again ._. ..

**Comment by florian-184-de** [comment]
At default, there isn't any web browser installed with Linux Deploy.
Open terminal and install Firefox, Midori (very fast at me, but it has a bug with black input boxes) or any other browser.
(Tip: At firefox, use "sudo apt-get install --no-install-recommends firefox" not to install gnome desktop environment)

**Comment by OoMiDOoO** [comment]
Thank you very much florian :) ..
Everything is perfect :) ..
<3
