### ISSUE TITLE
how to display chinese?

### ISSUE THREAD

**Issue by bluelovers** [meefik/linuxdeploy#238]
sry im new, how to display chinese in linuxdeploy?

i choose ubuntu & lxde

![2015-6-28 01-14-40](https://cloud.githubusercontent.com/assets/167966/8393185/7d355270-1d36-11e5-968a-3d5782fcec31.png)

**Comment by PythonNut** [comment]
@bluelovers you'll need to install some fonts on your (linux) system. What distro are you running?
