### ISSUE TITLE
Question about "Added handling for shutdown event"

### ISSUE THREAD

**Issue by ShapeShifter499** [meefik/linuxdeploy#239]
Hi,

So does "Added handling for shutdown event"  in the changelog mean there is now support for a proper shutdown? Meaning if I use the app to start my Linux Chroot but I forget to stop it when I shutdown my device that the app itself will stop it for me.   Or does it mean something else?

Thank you in advance, Lance

**Comment by meefik** [comment]
Yes, this works when the option "Autostart" is checked.

**Comment by ShapeShifter499** [comment]
How awesome! Thank you so vary much for adding this feature.
