### ISSUE TITLE
Feature request: Add toggle for secure vnc connetions.

### ISSUE THREAD

**Issue by ShapeShifter499** [meefik/linuxdeploy#241]
Hi,

So I was looking around, I didn't want others to be able to attack my Chroot if I had connected my Android to a open WIFI while using my Chroot locally with a VNC viewer.   I found out you can secure it somewhat by passing the commands "-alwaysshared -localhost"    you also have to move the ":$VNC_DISPLAY" variable to the end making the final command look like inside your script
```
chroot $MNT_TARGET su - $USER_NAME -c "vncserver -depth $VNC_DEPTH -geometry $VNC_GEOMETRY -dpi $VNC_DPI $VNC_ARGS -alwaysshared -localhost :$VNC_DISPLAY"
```
You could turn this into a toggle, giving the user an option to open it up (without the -localhost) or keep it secure. With this you can connect using a local Android VNC viewer or securely over SSH (or similar) by forwarding the port.  This may work with other VNCservers than TigerVNC but they probably use a different variable to toggle localhost.

**Comment by ShapeShifter499** [comment]
@meefik Does this feature look like something you may add in the future?

**Comment by meefik** [comment]
"Properties -> GUI settings -> VNC options" not working?

**Comment by ShapeShifter499** [comment]
I'm sorry I think I had a typo under
