### ISSUE TITLE
Don't kill SSHD if it's not part of the Chroot.

### ISSUE THREAD

**Issue by ShapeShifter499** [meefik/linuxdeploy#242]
Hi,

I noticed other SSHD instances were getting killed when I stopped the Chroot, removing the following under the "stop_system" function in the linuxdeploy script fixed the issue for me.

```
                        # kill active sessions
                        sleep 1
                        pkill -9 'sshd' || true
```

**Comment by meefik** [comment]
Standard init script do not kill active ssh connections..

**Comment by ShapeShifter499** [comment]
Yes but it was killing SSHD outside the chroot. I kept having to restart it in order to SSH into my phone before I realized what was causing it.  No active SSH connections where open when the linuxdeploy script killed SSHD.

**Comment by fleixi** [comment]
Same by me. If i have a running sshd in Android it will be stoped if i stop linuxdeploy.

**Comment by ShapeShifter499** [comment]
@fleixi Glad I'm not the only one.

@meefik Any updates on this issue?

**Comment by ShapeShifter499** [comment]
@meefik any updates?

**Comment by meefik** [comment]
Fixed.
