### ISSUE TITLE
write error: Socket operation on non-socket

### ISSUE THREAD

**Issue by nroehrl** [meefik/linuxdeploy#243]
I'm trying to install debian unstable onto an (ext4) partition on the external sdcard running Android 5.0. I always get the following log:

>>> begin: install 
Checking mount points ... sh: write error: Socket operation on non-socket
sh: write error: Socket operation on non-socket
sh: write error: Socket operation on non-socket
sh: write error: Socket operation on non-socket
sh: write error: Socket operation on non-socket
sh: write error: Socket operation on non-socket
done 
fail 
Press STOP and repeat attempt. 
<<< end: install 

I already tried to use the external busybox and updating ENV. Does anyone have an idea?

Thanks..

P.S. The partition is /dev/block/mmcblk1p2 and it has already an ext4 fs

**Comment by crisonyx** [comment]
Having this same issue, anybody have any idea what the cause is?

Running android 5.1.1 on xperia z3 have tried all the steps mentioned above only I am using an image for the file system.

**Comment by Taconut** [comment]
@crisonyx I’m having the same problem on the same device with the same version of android. It may also help that I changed my SELinux mode to permissive

**Comment by nroehrl** [comment]
I resorted to a manual installation. E.g. https://wiki.debian.org/ChrootOnAndroid

**Comment by crisonyx** [comment]
@taconut I actually ended up correcting this by adding the filename.img  I wanted at the end of my storage location. Since I wanted it on my sd card I had changed the path but was trying to essentially write to a folder.

**Comment by Taconut** [comment]
Well I fixed the problem by exiting out of the profile and getting back in. Even rebooting/reinstalling didn’t help. But now everything seems to be magically fixed
