### ISSUE TITLE
Shell without SSH

### ISSUE THREAD

**Issue by Shinudgr8** [meefik/linuxdeploy#244]
Hello,
Your application works flawlessly, i installed debian on my Asus Zenfone 5 and it runs without an issue.
However i would like to run debian shell without having to use SSH, something that would allow me to use it in terminal emulator.
Sorry i dont know much about chroot and debootstep, so it would be really great if you could guide me or give me some pointers.
Cheers

**Comment by kdb424** [comment]
su -/data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy shell

**Comment by meefik** [comment]
Short command as root:

    linuxdeploy shell

It works if checked Settings -> Symlink. Or use long command as root:

    /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy shell

**Comment by allanlinuxmg** [comment]
Hello,
Please add one shortcut to start terminal, next, start /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy shell

Thanks!
