### ISSUE TITLE
/dev/tty0 is (still) missing

### ISSUE THREAD

**Issue by ljones0** [meefik/linuxdeploy#248]
Like some other people on here, I'm finding linuxdeploy dosen't work on my android device at all with framebuffer mode. I'm aware that there are other options, though is it just me or is having to start *another* program a bit of a clumsy way to fix this problem at all?

By and large my problem the same as what others have had, e.g. https://github.com/meefik/linuxdeploy/issues/45 - /dev/tty0 is missing. What I was wondering was first of all has this issue now been fixed or is there an alternative workaround (can I for example modify /etc/X11/xorg.conf, or maybe run without /dev/tty0 at all)?

ljones

**Comment by ShapeShifter499** [comment]
@ljones0 did you try the fix as mentioned in the changelog?

```
Added fix for tty0 (use X options: "-sharevts vt0")
```

**Comment by ljones0** [comment]
It *almost* works! I'm now getting a mouse pointer on an empty black screen

ljones

**Comment by ljones0** [comment]
It *almost* works! I now get a mouse pointer on a blank screen x.x Still seems to be some graphic problem however - the screen (or part of it) flickers for a moment but remains blank.

ljones

**Comment by mionec1** [comment]
ljones,how do you fix the problem?Please tell me.
