### ISSUE TITLE
Using USB keyboard on old pengpod 700 running android/linuxdeploy

### ISSUE THREAD

**Issue by ljones0** [meefik/linuxdeploy#251]
Well....after having no success on my phone I decided to try linuxdeploy on my only other device - an old pengpod 700 tablet.

I've had a _lot_ more success with getting linuxdeploy working on this device (pengpod) than my phone. All I needed to do after installing and creating an image is;
- Add -sharevts vt0 to X options in properties:linux (just in case!)
- Set Freeze android UI to "Pause" in properties:linux
- From an SSH/Terminal - ln -s /dev/graphics/fb0 /dev/fd0
- apt-get install dbus

Once I did these 4 things I get a usable LXDE desktop, I can click things, windows move around and soforth. Unfortunatly doing these for my phone didn't work though. But there's one thing I'm just trying to get to work.

How can I get both a USB mouse and keyboard to work? Can I specify two input devices in properties:linux in linuxdeploy, or do I have to modify /etc/X11/xorg.conf ?

Both the usb keyboard and mouse both seem to be generating seperate data - again at an SSH I can see data being generated in /dev/input/event2 from the mouse (but not the keyboard) and /dev/input/event3 from the keyboard (but not the mouse). So they don't seem to be getting mixed up.

I'm just not sure what to put and where!

ljones

**Comment by dyharlan** [comment]
add /dev/input/event3 on the xorg.conf and input2 with evdev

**Comment by ljones0** [comment]
I gave that a go best I could, but found it didn't work. It either did nothing at all or X or even ssh wouldn't start up. After looking more carefully I read that any files in /usr/share/X11/xorg.conf/ take presidence over xorg.conf. And in mine I have the file "10-evdev.conf" - it contains;

#
# Catch-all evdev loader for udev-based systems
# We don't simply match on any device since that also adds accelerometers
# and other devices that we don't really want to use. The list below
# matches everything but joysticks.

Section "InputClass"
        Identifier "evdev pointer catchall"
        MatchIsPointer "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
EndSection

Section "InputClass"
        Identifier "evdev keyboard catchall"
        MatchIsKeyboard "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
EndSection

Section "InputClass"
        Identifier "evdev touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
EndSection

Section "InputClass"
        Identifier "evdev tablet catchall"
        MatchIsTablet "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
EndSection

Section "InputClass"
        Identifier "evdev touchscreen catchall"
        MatchIsTouchscreen "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
EndSection

With all of that in there I wonder why that file isn't working or isn't being picked up at all....

**Comment by ljones0** [comment]
Unfotunatly this will probably never be resolved. An accident ment the tablet screen got smashed x.x I managed to save "the guts" so to speak, although I don't think it will even power on any more even to HDMI.
