### ISSUE TITLE
ethtool failed when use wifite, G Parted and some app didn't work.

### ISSUE THREAD

**Issue by wizardx95** [meefik/linuxdeploy#253]
First, i ran on Kingcom piphone luna with 7' screen, cpu MTK-8313, wifi 80211b/g/n, 1Gb RAM, Android 4.4.2
I'm trying to crack my Router, i used "wifite" command and it said:
[+] scanning for wireless devices...
 [+] available wireless devices:
1. ethtool failed...
2. Only mac80211 devices on kernel 2.6.33 or higher are officially supported by airmon-ng.
   I have installed newest ethtool and other tool like lsusb... but it still didn't work.
   Second, I've installed software-center, and it didn't work. some application didn't work too: Gparted, synaptic package manager.
   Please help me

**Comment by wizardx95** [comment]
Sorry, it is MTK 8312

**Comment by Fr1z** [comment]
Same problem here..

**Comment by ahmasoft** [comment]
I have these problem

**Comment by Systemad** [comment]
You'll have to have a patched kernel to support monitor more, alternativly you can use a network adapter. If you are using an adapter your kernel doesn't support the drivers you need, you have to build you own kernel (or find online) to support needed drivers.

**Comment by ahmasoft** [comment]
Can you give me links of kernels, which support ieee80211 for airmon-ng starting

**Comment by Systemad** [comment]
If your device is supported by CyanogenMod you can follow this:
http://null-byte.wonderhowto.com/how-to/android-cyanogenmod-kernel-building-monitor-mode-any-android-device-with-wireless-adapter-0162943/
Otherwise, I don't know, sorry.

**Comment by ahmasoft** [comment]
Thanks much, but I have jelly bean tablet, which does'nt support update on any other android (eplutus g10s)

**Comment by blueaftab** [comment]
Same issue  I have Kernel higher then 2.6.33

**Comment by davinde** [comment]
Same issue please tell us any solution

**Comment by twaik** [comment]
There is no solution. Ubuntu/Debian/etc have no drivers for android chipsets.
