### ISSUE TITLE
support for Ubuntu amd64 architecture

### ISSUE THREAD

**Issue by rbrewer123** [meefik/linuxdeploy#254]
I'm using a rooted Asus Zenfone 2, which has an amd64 (x86_64) architecture and is running an x86_64 kernel out of the box.  Using Linux Deploy from the Play Store I got ubuntu 15.04 i386 installed and working and am finding it very impressive.  Next I'd like to try and get docker (from docker.com) running, which prefers to run in a full 64-bit environment.  

How difficult would it be to get amd64 support into Linux Deploy?  I'm willing to help with this effort but don't yet know where to begin.  Any advice is appreciated.

**Comment by Tikilou** [comment]
Hi, i have the same device (Zenfone 2 551ml x86_64 quadcore intel@2.3Ghz with 4Gb of ram), there is any way to have Ubuntu amd64 ?

**Comment by rbrewer123** [comment]
@Tikilou I added PR #258 which may get this working.  I haven't been able to test it yet.

**Comment by rbrewer123** [comment]
Despite spending a lot of time trying to do so, I haven't been able to get the right build environment to test my PR #258.  I did discover a workaround that enabled me to install Ubuntu 15.04 with amd64 architecture while we wait for the PR to be merged:

1. Install LinuxDeploy and run it
2. Set up the desired Linux configuration in LinuxDeploy (but with i386 architecture).  I used Ubuntu 15.04 (vivid) with only ssh (no graphical desktop, more on that later).
3. Press the Stop button in Linux deploy.  This will write out the config and other scripts.  Leave LinuxDeploy running.
4. In a terminal (with root) `cd /data/data/ru.meefik.linuxdeploy/linux`.  Now edit the file `etc/deploy.conf`.  Change the line `ARCH="i386"` to `ARCH="amd64"` and save the file.
5. Sometimes I have problems like #230, so you should also run `chmod 755 deploy/debootstrap/pkgdetails`
6. Run the installer:  `bin/linuxdeploy install`

This should give you an Ubuntu install with all amd64 packages.  You should be able to use the LinuxDeploy GUI to Start and Stop the services, but any reconfiguration or reinstallation needs to be done via the command line as above, and make sure to edit the `deploy.conf` file again since LinuxDeploy may reset the ARCH to i386.

I had a problem where the `bin/linuxdeploy install` failed early on with some mount issues.  I think this was solved by using the LinuxDeploy GUI to Start and Stop to get the mountpoints back to the correct state.

I used LinuxDeploy to install a minimal Ubuntu configuration (just SSH, no desktop environment).  Then after installation, I ssh'd into the Ubuntu environment and installed `mate-desktop-environment` which seems to work pretty well with xserver-xsdl.  Unfortunately, the stock kernel on the Zenfone 2 doesn't have the loop device module which is preventing me from running Docker.  But it's still pretty neat having a 64-bit Ubuntu environment on my phone.

**Comment by Tikilou** [comment]
Thanks for the tutorial ! :+1: 

I don't use the stock Kernel, but CyanogenMod 12.1 with is own Kernel options and modules ! :)

You can download last build here => http://download.crpalmer.org/nightlies/Z00A/

Anyway, do you know a way to use OpenGL acceleration on this device with chroot (except libgl1-mesa-swx11 => Very bad performances with CPU acceleration...) ?

I'm search a way to compile Virtualbox modules too, i've found a tutorial for chromebooks kernel without linux-headers package, but from kernel source directly => https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-%28x86%29

Maybe a way to compile our own modules ?

**Comment by rbrewer123** [comment]
@Tikilou, I haven't tried tg get opengl working.  There seems to be a fair amount of interest in it on the Zenphone 2 forum at xda-developers.com.  

I haven't unlocked my bootloader yet, but I think compiling our own kernel modules is the next step for virtualbox or docker.  I'm surprised the cyanogen kernel doesn't just have "all the modules" enabled, even if they're not distributed by default.  It's probably a similar level of effort to get a stock or cyanogen kernel build environment set up.

@meefik expanded and merged #258 so we should have amd64 out of the box with the next official linuxdeploy.
