### ISSUE TITLE
Essential to LinuxDeploy: Xvnc running with Xkb support?

### ISSUE THREAD

**Issue by PaulaDiord** [meefik/linuxdeploy#26]
Can you check if you Xvnc server is running with Xkb support?
Xkb support is essential for modern virtual keyboards like Onboard or Florence.
But both complain about 
"X keyboard extension not available" or 
"Unable to query XKB extension from X server".
(The a little bit old fashioned and not very good looking xvkbd has no problems with that)

In my opinion a virtual keyboard is the most important thing a Linus on Android should deploy. Most Linux-Apps and a lot of more Java apps are not able to work with the Android keyboard.

So without an own virtual keyboard Linux on Android is in more than 95% useless at all.
Without a virtual keyboard Linux on Android does not prove little more than that it is possible to install it on Android - but Linux on Android should be more than a technical 
trick: It should solve problems Android does not even think that they exists. 

And Linux should be available on millions of touchscreens to make millions of Java apps available on Android!

**Comment by JeffreyRFox** [comment]
You do not say why your Android keyboard doesn't work. Most users without a hardware keyboard would install Hacker's Keyboard or something similar off the play store to be able to produce the full range of PC keystrokes, and most VNC clients can send constructed key sequences as well.

**Comment by twaik** [comment]
Yes. Xvnc is running with Xkb support.
