### ISSUE TITLE
Issues with Xorg, VNC, and framebuffers

### ISSUE THREAD

**Issue by Taconut** [meefik/linuxdeploy#263]
Hi! I'm trying to get KDE5 to run on Ubuntu, but I'm encountering quite a few problems. Due to graphical limitations, I can't run KDE5 with tightvncserver, as it doesn't support the GLX extensions. As a result, many extensions required by KDE aren't being enabled (even though I set them in xorg.conf).

So, to work around the issue, I decided to attempt to use x11vnc. However, that requires an X display to be running beforehand. Unfortunately, startx fails due to framebuffer issues. It logs ```FBDEV(0): FBIOPUTCMAP: Invalid argument``` a couple dozen times and then crashes. 

I just got into this, so I'm not sure which of the many fixes I should use to either get framebuffers working or get VNC working with graphic extensions.

If I do end up having to resort to VNC, I've found that running it with [NoMachine](https://www.nomachine.com/) works beautifully on Android. A while back, I requested ARMHF packages for the server version. They actually did deliver and said packages are available on the site.

So where do I go from here?

Thanks!

**Comment by kdb424** [comment]
Unfortunately most android devices don't run openGL, they have opneGL ES. Adwanced desktop environments like Gnome, require hardware acceleration which most devices can't provide. I have not tested KDE myself, but if possible, I'd suggest using something like XFCE. It'll run a lot faster, and you can still run all KDE apps in it without a problem. You can test with that, and if it gives you similar problems, then we can rull out the hardware acceleraton easily. Lighter devices don't run KDE very well either, sao even if it does work, it'll put a lot more load on your system. I have a shield TV, which is a very  powerful processor, and many applications still strain it.

Hope that helps at least a bit.

**Comment by Taconut** [comment]
XFCE works really smoothly! Thanks for the advice.

I'm assuming framebuffer support is still janky and support is out of the question?

**Comment by kdb424** [comment]
Support comes down to your chipset. my tegra X1 will not work. Try this in a chrooted terminal as root.
cat /dev/urandom > /dev/graphics/fb0
If that puts random garbadge or colors on your screen, then it should work fine. Press ctrl+c to stop it, or exit the terminal. If that doesn't work, or gives you an "out of space" error, then your rom/chipset won't allow you direct access, and there is nothing that can be done about it. Give that a shot, and if it works, enable the framebuffer. You may also need the option to kill surfaceflinger, but if you do that, you'll have to reboot to get back to android on some devices. Good luck!

**Comment by Taconut** [comment]
That has solved the last of my issues, so I'll go ahead and close this issue. Linux is now running perfectly on my Phone.
