### ISSUE TITLE
Mount multiple SD cards

### ISSUE THREAD

**Issue by kdb424** [meefik/linuxdeploy#269]
I had a failed copy from one SD to the other SD and after this file failed at the last few Mb, I figured I would use rsync instead of recopying it all again. I couldn't use this as I can only get access to one SD at a time. Please add multiple mount points for storage and not force me to switch between them. Thank you.

**Comment by meefik** [comment]
You can be add multiple mout points in "Properties -> Mount points", use "Menu" button to display a pop-up menu.

**Comment by kdb424** [comment]
That is a radio button, so I can only choose one at a time, or is that just a graphical inaccuracy?

**Comment by kdb424** [comment]
Please close this. I now see what the radio button is for. My second directory always shows up empty, but I'll do more looking.

**Comment by meefik** [comment]
Radio button need only for delete item from the list.
