### ISSUE TITLE
No menu button to adjust settings on Nexus Player

### ISSUE THREAD

**Issue by angelorg74** [meefik/linuxdeploy#273]
I have placed image on USB and I can not access any of the settings tabs located when I installed the software on my samsung note 4 which are start, stop marked down arrow a settings locaton. Is there a shortcut I can use on my bluetooth keyboard to access those items. I also change the view layout to see if that was the problem that I still can not see these tabs that are needed for me to have Linux installed please help.

**Comment by meefik** [comment]
Please show this screenshot.

**Comment by angelorg74** [comment]
![20150831_231104](https://cloud.githubusercontent.com/assets/14061568/9597403/81dc74f8-503e-11e5-947f-ccf76ed92cca.jpg)

**Comment by ssb3304** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

ssb3304@naver.com 님께 보내신 메일 <Re: [linuxdeploy] No menu button to adjust settings on Nexus Player (#273)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by angelorg74** [comment]
As shown on picture.

**Comment by angelorg74** [comment]
![20150831_231110](https://cloud.githubusercontent.com/assets/14061568/9597443/f228aa74-503e-11e5-8937-5c432644bf70.jpg)

**Comment by meefik** [comment]
Hm, very strange...

**Comment by angelorg74** [comment]
Is it possible to had a keyboard shortcuts to those options?

**Comment by angelorg74** [comment]
Any software that I may be missing that it is not showing up those keys?

**Comment by angelorg74** [comment]
I assume I suppose to see that menu options even if it is not rooted as my nexus player is rooted but I can not see those options, but my Samsung Note 4 is not and I can see those. I guess I should try to load it on a nexus player that is not rooted although it has to be something else.

**Comment by angelorg74** [comment]
I assume I suppose to see that menu options even if it is not rooted as my nexus player is rooted but I can not see those options, but my Samsung Note 4 is not and I can see those. I guess I should try to load it on a nexus player that is not rooted although it has to be something else.

**Comment by angelorg74** [comment]
Okay I corrected the issue with not finding those options. I reloaded another image of Nexus player lolirock 2.1 and rooted it and now I see those options. I got an error installing more on that tonight.
