### ISSUE TITLE
Runing custom scrpts in reverse order when stopping

### ISSUE THREAD

**Issue by aligator** [meefik/linuxdeploy#275]
I think it would make sense to run the custom scripts in a reverse order when stopping linux.

**Comment by ssb3304** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

ssb3304@naver.com 님께 보내신 메일 <[linuxdeploy] Runing custom scrpts in reverse order when stopping (#275)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by meefik** [comment]
Already implemented.
