### ISSUE TITLE
SSH Password is incorrect

### ISSUE THREAD

**Issue by AnguisCaptor** [meefik/linuxdeploy#277]
I'm not able anymore to SSH using root as username and my own setted password
When I set the username/password in the settings, setting distro to kali sana and hit install
After install I'm not able to SSH into it, simply "Access denied"

**Comment by ssb3304** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

ssb3304@naver.com 님께 보내신 메일 <[linuxdeploy] SSH Password is incorrect (#277)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by meefik** [comment]
Check option "PermitRootLogin yes" in /etc/ssh/sshd_config

**Comment by ssb3304** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

ssb3304@naver.com 님께 보내신 메일 <Re: [linuxdeploy] SSH Password is incorrect (#277)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by AnguisCaptor** [comment]
How am I supposed todo that if I can't even SSH ?

**Comment by meefik** [comment]
After start the container from Android (as root):

    MNT_TARGET=/data/data/ru.meefik.linuxdeploy/linux/mnt
    sed -i "s|^[# ]*PermitRootLogin .*|PermitRootLogin yes|g" ${MNT_TARGET}/etc/ssh/sshd_config

or:

    /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy shell
    sed -i "s|^[# ]*PermitRootLogin .*|PermitRootLogin yes|g" /etc/ssh/sshd_config

**Comment by AnguisCaptor** [comment]
Thanks for the help, this worked :)
