### ISSUE TITLE
SSH: Wrong password 

### ISSUE THREAD

**Issue by florian-184-de** [meefik/linuxdeploy#279]
Hello,
The new feature "change user password" doesn't work.
I can't log in with SSH. "Authentication failed"
Also the standard password "changeme" doesn't work after I deleted the actual profile, added a new one and didn't changed the user password.

Mobile: OnePlus One Android 5.1.1
Linux-system: Ubuntu trusty armhf

**Comment by ssb3304** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

ssb3304@naver.com 님께 보내신 메일 <[linuxdeploy] SSH: Wrong password (#279)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by florian-184-de** [comment]
--> supplement: Also the standard password "changeme" doesn't work...
Specifically, I did this:
1. I changed the settings of it, also the user password and user name.
2. I installed Ubuntu. Success!
3. I started ubuntu and wanted to connect with ssh. Didn't work...
4. I stopped the not working Ubuntu
5. I deleted the profile of it.
6. I added a new one.
7. I changed the settings again, excluded the user password.
8 ... Installed Ubuntu again, same problem again. SSH: "Authentication failed"

**Comment by ssb3304** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

ssb3304@naver.com 님께 보내신 메일 <Re: [linuxdeploy] SSH: Wrong password (#279)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by kdb424** [comment]
Start the chroot, then in a terminal application type this.
su (then hit enter)
linuxdeploy shell
From this point you are root in the chroot. USe the command below to change the password of any user. Substitute "android" for any username you want to change the password of.
passwd android


That should be all.

**Comment by florian-184-de** [comment]
@kbd424 Doesn't work...
linuxdeploy shell: not found

**Comment by kdb424** [comment]
In the settings, make sure "create symlink" is checked.

**Comment by florian-184-de** [comment]
Yes, now it works. Thanks!
But I think, we should fix that bug because there are a lot of users who won't read this comment on  github.
Is it already fixed?

**Comment by kdb424** [comment]
Please email the dev with a log of starting the chroot with debug logging on which is also found in settings. There were changes in arch recently, so I'll be doing the same for that. Sending debug logs is the sight way for him to fix tt. He doesn't have one of every single chroot avaliable totest, so we need to provide logs. Thank you, and gd something is working for u at last in the time being.

**Comment by florian-184-de** [comment]
Bug seems to be fixed with version 1.5.3 from 18th September.
Log from Saturday: http://pastebin.com/raw.php?i=0Phb3yKy
