### ISSUE TITLE
Is it possible to use macchanger?

### ISSUE THREAD

**Issue by gerroon** [meefik/linuxdeploy#280]
Hi

I am wondering I could randomize my mac address using macchangger under Debian Jessie arm? I tried it it does not work. But  I am wondering if there is a way to make it work?

**Comment by ssb3304** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

ssb3304@naver.com 님께 보내신 메일 <[linuxdeploy] Is it possible to use macchanger? (#280)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by kdb424** [comment]
The networking is borrowed from the host, so no, it should not be possible. With a rooted android, you can fake a mac with the android OS, then the chroot will use the borrowed faked mac.

**Comment by gerroon** [comment]
@kdb424 
Can you point out some leads on how to achieve fake mac ?

thanks

**Comment by kdb424** [comment]
http://forum.xda-developers.com/showthread.php?t=2286440 Quick google search would have solved this. Please consider solved.
