### ISSUE TITLE
Any way to mount an OTG Cable?

### ISSUE THREAD

**Issue by alexhulbert** [meefik/linuxdeploy#282]
I was wondering if it was possible to use a USB OTG host cable to plug a USB device into my Linux OS, treating the Linux OS as a host. This could allow me to interface with hardware that would normally be completely incompatible with Android.

**Comment by kdb424** [comment]
Unfortunately that's not the way that it works. Well, it is and isn't. The kernel needs to have the driver for it, and that's being borrowed from android. The chroot has full access to /dev so it should see anything that the kernel finds, even if android doesn't know how to use it. If the kernel sees it, you can use it the asme as you would in linux, if not, you'll need to compile your own kernel to add uspport for the device that you want added.
