### ISSUE TITLE
Checking mount points ... fail; The container is already mounted.

### ISSUE THREAD

**Issue by craigtipping** [meefik/linuxdeploy#285]
On starting to install within linuxdeploy the following errors occur and then no further action.  I am using a rooted Samsung Note 8.0 N5110 that is using the normal factory setup.

[10:52:36] Updating configuration file ... done
[10:52:36] >>> install 
[10:52:36] Checking mount points ... fail 
[10:52:36] The container is already mounted. 
[10:52:36] <<< install

Any ideas?

Reagrds Craig

**Comment by meefik** [comment]
Update to version 1.5.3-165

**Comment by craigtipping** [comment]
Thanks. I have downloaded the latest release which I think is 1.5.3-163. Menu -> Status has a blank at Linux Deploy Version:

Output below.

[19:58:01] Updating environment ... done
[19:58:59] Updating configuration file ... done
[19:58:59] >>> install
[19:58:59] The container is already mounted. 
[19:58:59] <<< install
[20:10:04] Updating configuration file ... done
[20:10:04] >>> status
[20:10:04] Linux Deploy version:  
[20:10:04] Device: unknown 
[20:10:04] Android: unknown 
[20:10:04] Architecture:  
[20:10:04] Kernel:  
[20:10:04] Memory: / MB 
[20:10:04] Swap: / MB 
[20:10:04] SELinux: yes 
[20:10:04] Loop devices: no 
[20:10:04] Support binfmt_misc: yes 
[20:10:04] Supported FS:   
[20:10:04] Mounted system: unknown 
[20:10:04] Running services:  
[20:10:04] * SSH: no 
[20:10:04] * GUI: no 
[20:10:04] Mounted parts on Linux:  
[20:10:04]  ...nothing mounted 

END OF LOG
[20:10:04] Available mount points:  
[20:10:04]  ...no mount points 
[20:10:04] Available partitions:  
[20:10:16]  ...no available partitions

**Comment by meefik** [comment]
Try the following:

1) Reboot the device.

2) Update to version 1.5.3-165 (https://github.com/meefik/linuxdeploy/releases/tag/1.5.3).

3) Remove directory "/data/data/ru.meefik.linuxdeploy/linux" from Android.

4) Check "Linux Deploy -> Menu -> Settings -> Debug mode".

5) Change "Linux Deploy -> Menu -> Settings -> ENV directory" to /data/data/ru.meefik.linuxdeploy/linux

6) Change "Linux Deploy -> Properties -> Chroot directory" to /data/local/linux

7) Install BusyBox and uncheck "Settings -> Built-in shell".

8) Run "Linux Deploy -> Menu -> Settings -> Update ENV".

**Comment by craigtipping** [comment]
Thank you.  Your instructions worked great.  To look at it further I completely removed linuxdeploy and reinstalled with the option "Built-in Shell" unchecked and all is great.

**Comment by vasubesimple** [comment]
Hello I have the same problem, it says container already mounted, I have samsung s4 galaxy,

I fallow the steps that you have mentioned above but nothing works , can you please help me out?

**Comment by craigtipping** [comment]
Hi.  I am running 1.5.3-165 that I downloaded from Github and have decided not to upgrade to the latest on the Play store (I don't know what version is there).  The only option I changed from default was to uncheck the  "Built-in Shell" option.

**Comment by vasubesimple** [comment]
I am using the same version but i don't have that option.  i tried to remove the option manually and add busybox shell 

cd /data/data/ru.meefik.linuxdeploy/linux/bin
rm sh (if any)
ln -s /system/bin/sh sh
Or, if you want to use busybox one if you have it:
ln -s /system/xbin/bash sh

this gives me the same error and also a permission denied error saying that 
data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy line 1978 chroot permission deined.

**Comment by Systemad** [comment]
Install busybox via this application and try again.
https://play.google.com/store/apps/details?id=ru.meefik.busybox

**Comment by vasubesimple** [comment]
I already have it ! I tried sadly nothing works :( !

**Comment by mesvak** [comment]
hello 
my problem is : 
updating configuration file ... done
>>> install
/data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy: line 1989: grep : permission denied
ash: bad number
the container is already mounted 
<<< install
how to fix it ?

**Comment by rjdawg** [comment]
Go to settings and uncheck option "built-in shell".That's it.Don't do Anytn else.

**Comment by L337Q4dr1** [comment]
The Container Is already Mounted. Plz help.   
meefik 
commented 10 months ago
Try the following:

1) Reboot the device.

2) Update to version 1.5.3-165 (https://github.com/meefik/linuxdeploy/releases/tag/1.5.3).

3) Remove directory "/data/data/ru.meefik.linuxdeploy/linux" from Android.

4) Check "Linux Deploy -> Settings -> Debug mode".

5) Change "Linux Deploy -> Settings -> ENV directory" to /data/data/ru.meefik.linuxdeploy/linux

6) Change "Linux Deploy -> Properties -> Chroot directory" to /data/local/linux

7) Install BusyBox and uncheck "Linux Deploy -> Settings -> Built-in shell".

8) Run "Linux Deploy -> Settings -> Update ENV".

Tried this

**Comment by chaos-zhu** [comment]
> The Container Is already Mounted. Plz help. meefik commented 10 months ago Try the following:
> 
> 1. Reboot the device.
> 2. Update to version 1.5.3-165 (https://github.com/meefik/linuxdeploy/releases/tag/1.5.3).
> 3. Remove directory "/data/data/ru.meefik.linuxdeploy/linux" from Android.
> 4. Check "Linux Deploy -> Settings -> Debug mode".
> 5. Change "Linux Deploy -> Settings -> ENV directory" to /data/data/ru.meefik.linuxdeploy/linux
> 6. Change "Linux Deploy -> Properties -> Chroot directory" to /data/local/linux
> 7. Install BusyBox and uncheck "Linux Deploy -> Settings -> Built-in shell".
> 8. Run "Linux Deploy -> Settings -> Update ENV".
> 
> Tried this

remove /data/data/ru.meefik.linuxdeploy/cache
