### ISSUE TITLE
VNC is broken on debian based systems

### ISSUE THREAD

**Issue by HaraldWeber** [meefik/linuxdeploy#289]
the package tightvncserver is broken. So VNC fails to start.
There are some problems with the FONTPATH.

To fix this i loged into the system removed tightvncserver and installed vnc4server.

``` bash
$ apt-get remove tightvncserver
$ apt-get install vnc4server
```

Just stop and start the chroot and VNC will start.

(vnc4server is not available for arm in debian)

**Comment by twaik** [comment]
Looks like the issue is solved in latest LD release.
