### ISSUE TITLE
Support F2FS file system

### ISSUE THREAD

**Issue by PythonNut** [meefik/linuxdeploy#297]
F2FS has many beneficial properties for running phone flash-storage. It should be pretty easy to add it to Arch Linux, as the distro is already configured to use it when needed, but I can't say for the other distros.

**Comment by kxra** [comment]
It's supported in the mainline linux kernel so enabling it should be extremely easy and supported across distributions, and the performance benefits huge

**Comment by twaik** [comment]
Linux Deploy does not implement any FS support, it uses Android kernel features. Contact your device vendor to get F2FS-featured kernel.

**Comment by PythonNut** [comment]
This isn't about kernel support, as noted previously that should be widespread (I know all of my kernels have supported it for years now). It's just about adding an option in the GUI for it.

**Comment by meefik** [comment]
how do I check if my device supports F2FS?
```
Aquaris_X5:/ $ cat /proc/filesystems                                           
nodev	sysfs
nodev	rootfs
nodev	bdev
nodev	proc
nodev	cgroup
nodev	tmpfs
nodev	debugfs
nodev	sockfs
nodev	pipefs
nodev	anon_inodefs
nodev	configfs
nodev	devpts
	ext3
	ext2
	ext4
nodev	ramfs
	vfat
	fuseblk
nodev	fuse
nodev	fusectl
nodev	selinuxfs
nodev	functionfs
```
```
root@THL:/ # cat /proc/filesystems                                             
nodev	sysfs
nodev	rootfs
nodev	bdev
nodev	proc
nodev	cgroup
nodev	tmpfs
nodev	debugfs
nodev	sockfs
nodev	pipefs
nodev	anon_inodefs
nodev	devpts
	ext3
	ext4
nodev	ramfs
	vfat
	msdos
	iso9660
	fuseblk
nodev	fuse
nodev	fusectl
nodev	selinuxfs
nodev	mtd_inodefs
nodev	functionfs
```

**Comment by PythonNut** [comment]
@meefik Yes, that is how you would check. I can only speak for myself that my devices have supported it. I suppose some may not. Perhaps I have been fortunate.
