### ISSUE TITLE
Tp link TL WN 722N not working on kali

### ISSUE THREAD

**Issue by Hanzla23** [meefik/linuxdeploy#299]
I have installed kali on my Pantech Vega A860L and connected TP link 722N usb antena to it but it is not being detect by system.Kindly help me for this

**Comment by Devvyas83** [comment]
Your phone would be not compatible with your wifi adapter

**Comment by Hanzla23** [comment]
Thnx for reply but i get it now after intricated searching.All i have to do is build my kernel with externel wifi card support.im on it and will do it soon.

**Comment by Devvyas83** [comment]
You're welcome
