### ISSUE TITLE
chroot ( linux deploy) can't execute 'su' No such file or directory 

### ISSUE THREAD

**Issue by 9625401000** [meefik/linuxdeploy#300]
![screenshot_2015-09-27-12-10-24](https://cloud.githubusercontent.com/assets/14857404/10121635/aefc4a00-6513-11e5-84dd-f8d1e6b83265.png)

**Comment by dyharlan** [comment]
Are you even rooted?

**Comment by BookThief-D** [comment]
I also met, I change the chroot catalog ( likes  /data/local/newdir ) , my english is poor ,hope it helps you out.
