### ISSUE TITLE
Can't create new img file: "dd: Invalid Arguement"

### ISSUE THREAD

**Issue by namandixit** [meefik/linuxdeploy#304]
Every time Linux Deploy tries to create a new img file, it keeps on restarting the creation process. So, what happens is that the a file will be created of proper size and then it will again try to write the same file making the size zero bytes and starting all over again in an infinite loop. Following is the debug trace:

[08:01:24] + dd if=/dev/zero of=/storage/sdcard0/Linux/Debianstable.img bs=1048576 seek=2999 count=1
[08:11:30] dd: /storage/sdcard0/Linux/Debianstable.img: Invalid argument
[08:11:30] + dd if=/dev/zero of=/storage/sdcard0/Linux/Debianstable.img bs=1048576 count=3000

and this keeps going on and on. The file paths above are correct and the same setup did indeed worked previously. I am using the latest update along with the inbuilt Busybox on ARM7 device (Micromax Canvas A1) running PacROM 5.1

**Comment by namandixit** [comment]
UPDATE: Same thing happening if using external busybox too.

**Comment by namandixit** [comment]
UPDATE: After trying a few more times, it abruptly worked; debug logs are exactly the same as before (couple of "Invalid Argument" errors and then suddenly formatting to EXT2 began followed by a complete installation). Still no idea what was causing the bug though.

**Comment by EzekielM** [comment]
Iv had this same problem and found out how to fix it... literally just wait 5 or 10 minutes and it will continue the install process that is it.  You'll notice it'll freeze up your phone when it goes into the error so it takes a minute to fully unfreeze and install linux.
