### ISSUE TITLE
how to install Google Chrome 

### ISSUE THREAD

**Issue by yean24** [meefik/linuxdeploy#313]
Hi I want to install Google Chrome . How to do?

**Comment by Systemad** [comment]
A simple search in Google...

https://digitz.org/blog/how-to-install-and-use-google-chrome-on-kali-linux-2-0/

These kind of question is not related to Linux Deploy.

**Comment by yean24** [comment]
My kali not have browser download chrome .deb with what ?

**Comment by iceblade112** [comment]
wget

**Comment by Systemad** [comment]
Yep, wget
http://askubuntu.com/questions/79280/how-to-install-chrome-browser-properly-via-command-line

**Comment by yean24** [comment]
Package architecture  (i386) does not much system  (armhf) how to do?

**Comment by arjunrsekhar** [comment]
http://blog.valitov.me/2014/06/installing-google-chromium-on-arm.html?m=1

Here is the answer
