### ISSUE TITLE
Linux deploy i386 error! Can't install!

### ISSUE THREAD

**Issue by JTS2111** [meefik/linuxdeploy#315]
Whenever I install an ARM type Linux, it works perfectly fine with no problems at all. I can install whatever, load up a vnc, etc. However, I soon realized that ARM is useless. I was thrilled when Linux deploy allowed i386 architecture. However, I get the error: /debootstrap/debootstrap: permission denied. Any fixes?

**Comment by CrazyJ36** [comment]
The I386 option is only useful if your phone uses Intels' i386 processor. Just like A PC.

**Comment by meefik** [comment]
Emulation mode (arm ~ x86) works only with support binfmt_misc in the kernel.
