### ISSUE TITLE
ubuntu amd64 on moto x 2014

### ISSUE THREAD

**Issue by fredericoallan** [meefik/linuxdeploy#316]
I have a motox 2 (aARM Qualcomm Krait 400) and try to install ubuntu, trusty, amd64. When instalation finish the error print on sreen:

chroot: can't execute 'debootstrap'

after that , i try start and
ssh [22] ....fail

**Comment by sunipkmukherjee** [comment]
Install armhf... Snapdragon is not amd64 (which means intel or amd processors with x86-64 instruction set)

**Comment by fredericoallan** [comment]
Tks...now i undertand that needs arquiteture of phone and linux Deploy not
emulate that...
Em 23/10/2015 5:48 PM, "sunipkmukherjee" <notifications@github.com>
escreveu:

**Comment by meefik** [comment]
Emulated only x86 (i386) ~ arm (armhf).
