### ISSUE TITLE
cgroups, chroot, systemd, archlinuxarm

### ISSUE THREAD

**Issue by russkiontheloose** [meefik/linuxdeploy#318]
Apparently /bin/init (symlinked to systemd) on archlinuxarm must be started with PID 1 to make stuff like "systemctl list-units" and friends work.

question is - can linux deploy start archlinuxarm with cgroups and exec systemd as init process. Something similar to systemd-nspawn with jchroot.

**Comment by crisonyx** [comment]
I would be interested in something like this too. Any insight is welcome!

**Comment by JuniorJPDJ** [comment]
+1

**Comment by wvffle** [comment]
+1

**Comment by twaik** [comment]
Android kernels don't support cgroups and namespaces.

**Comment by JuniorJPDJ** [comment]
Can't you check if it actually does? Custom kernels and custom ROMs could make it work as optional addition.

**Comment by jscinoz** [comment]
Some newer devices do appear to have kernels supporting both cgroups and namespaces.

From a Samsung Galaxy Note 9 international variant (Exynos), running the stock kernel:
```
crownlte:/ $ cat /proc/config.gz | gzip -d | grep -e _NS= -e CGROUP
CONFIG_CGROUPS=y
CONFIG_CGROUP_DEBUG=y
CONFIG_CGROUP_FREEZER=y
CONFIG_CGROUP_PIDS=y
CONFIG_CGROUP_DEVICE=y
CONFIG_CGROUP_CPUACCT=y
CONFIG_CGROUP_SCHEDTUNE=y
# CONFIG_BLK_CGROUP is not set
CONFIG_CGROUP_SCHED=y
# CONFIG_CGROUP_PERF is not set
CONFIG_CGROUP_BPF=y
CONFIG_SOCK_CGROUP_DATA=y
CONFIG_UTS_NS=y
CONFIG_IPC_NS=y
CONFIG_USER_NS=y
CONFIG_PID_NS=y
CONFIG_NET_NS=y
CONFIG_NF_CONNTRACK_NETBIOS_NS=y
# CONFIG_NETFILTER_XT_MATCH_CGROUP is not set
CONFIG_NET_CLS_CGROUP=y
# CONFIG_CGROUP_NET_PRIO is not set
CONFIG_CGROUP_NET_CLASSID=y
```
