### ISSUE TITLE
How to run vsftpd service?

### ISSUE THREAD

**Issue by zhangew** [meefik/linuxdeploy#32]
Excuse me, I'd like to ask a question.
I installed vsftpd and ftp using "yum".
And when I typed "sudo service vsftpd start", it told me:

"Redirecting to /bin/systemctl start  vsftpd.service"
"Running in chroot, ignoring request".

by using ftp command then, I received an failed message.

I'm a Linux newbie indeed, would you like to tell me how to run a ftp server in Linux Deploy?
Thanks and best regards.

**Comment by okumedia** [comment]
Wow, worked for me too in starting apache.
nohup httpd >/dev/null &

**Comment by okumedia** [comment]
I am now a bit lost. How do I stop the service?

**Comment by okumedia** [comment]
How about how to stop connection?
