### ISSUE TITLE
Question about Linux deploy pls see

### ISSUE THREAD

**Issue by Devvyas83** [meefik/linuxdeploy#325]
Hello I am a beginner in this linux deploy buisness and I couldn't download the sana package of Kali . but someone said me to download the official  image file for armhf from kali.org . so I did it it was of 2 gb . but now I am stuck . what to do next of the 2gb armhf image file ?

**Comment by Devvyas83** [comment]
Ah yes sorry I didn't mentioned that I don't have WiFi or 3g  . I am using 2g so it was difficult for me to download this 2gb file .

**Comment by Fafadu40** [comment]
You should try to get a working connection just for downloading all packages properly. You can try to go in a cybercafe or any place that provides that free wifi service.
Best regards.
