### ISSUE TITLE
Feature Request: Add Chromium OS

### ISSUE THREAD

**Issue by scndthe2nd** [meefik/linuxdeploy#326]
I know it sounds kind of basic, but adding a chromium os like vanilla or cloudready would be really amazing. You'd be about two years ahead of google. The concept would be that you can use the phone in a media dock or chromecast with a wireless keyboard and mouse. You'd have a (nearly) functioning chromebook along side your regular phone that's with you wherever you go.

I'm tinkering through right now, and while I'm fairly new with linux in general, this project has me really excited. Maybe I'll find a better way to use it along the way. Thanks for doing this.

**Comment by twaik** [comment]
Chromium OS does not have Xorg or tightvnc package so it is unusable even with LD.
