### ISSUE TITLE
E: The selected extractor cannot be found: ar

### ISSUE THREAD

**Issue by suspy69** [meefik/linuxdeploy#339]
Hello. I'm using version 1.5.4-181 on an Xperia T3 with android 4.4.4.

I'm trying to deploy kali Linux.
After successfully mounting on the external sd, I get the following error:
E: The selected extractor cannot be found: ar

Any thoughts?

**Comment by meefik** [comment]
Install this [BusyBox](https://github.com/meefik/busybox)

**Comment by suspy69** [comment]
I've already installed this Busybox https://play.google.com/store/apps/details?id=stericson.busybox

When I try to install meefik's Busybox, I get the following error:
Remounting /system to rw ... fail.

Of course I'm routed ;)

**Comment by meefik** [comment]
BusyBox stericson not supported ar and other required functions.

**Comment by suspy69** [comment]
I'll try to remove it and add meefik's.
Thank you for your help.

**Comment by meefik** [comment]
Please, enable debug mode from BusyBox settings and put logs here. My be need to reboot the device. Also your can install BB from recovery via zip archive.

**Comment by suspy69** [comment]
>>> INSTALL BUSYBOX
+ PATH=/data/data/ru.meefik.busybox/files/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
+ INSTALL_DIR=/system/xbin
+ INSTALL_APPLETS=true
+ REPLACE_APPLETS=false
+ . /data/data/ru.meefik.busybox/files/scripts/install.sh
+ busybox printf /system/xbin
+ busybox grep -c ^/system/
+ SYSTEM_REMOUNT=1
+ busybox test 1 -ne 0
+ busybox printf Remounting /system to rw ... 
+ busybox mount -o rw,remount /system
Remounting /system to rw ... mount: permission denied (are you root?)
+ busybox test 1 -eq 0
+ busybox printf fail\n
fail
+ exit 1
.

**Comment by meefik** [comment]
The application requests a superuser permissions?

**Comment by suspy69** [comment]
Yes. I grant it, but I get the error.

**Comment by meefik** [comment]
Strangely, you can try installing from recovery. Or manually (from Android termonal) copy busybox from /data/data/ru.meefik.linuxdeploy/files/bin/busybox to /system/xbin and execute /system/xbin/busybox --install -s /system/xbin

**Comment by suspy69** [comment]
It's at /data/data/ru.meefik.linuxdeploy/linux/bin/busybox but I cannot copy it due to permissions :/
I'll try to remove root and add it again and I'll let you know

**Comment by suspy69** [comment]
Ok. This worked.
Thank you very much for your help.

**Comment by mascondante** [comment]
Same issue. Is there a way to provide an updated version that works around the issue of the new busybox not working?

**Comment by meefik** [comment]
The latest version of Linux Deploy requires compatible BusyBox:
https://github.com/meefik/busybox/releases
https://play.google.com/store/apps/details?id=ru.meefik.busybox
Previous versions:
https://github.com/meefik/linuxdeploy/releases

If system BusyBox not working:
1) Install compatible BusyBox (https://github.com/meefik/busybox/releases)
2) Run BusyBox app.
3) Run Linux Deploy app and change "Settings -> BusyBox directory" to /data/data/ru.meefik.busybox/files/bin

**Comment by okumedia** [comment]
I dont have problem installing Fedora but Ubunu says"Cannot install into target '/data/local/linux' mounted with noexec or nodev"

**Comment by kmanbxv** [comment]
Meefik's most recent comment worked for me. 
side note:
make sure you are trying to install to a file, as directory install did not work for me after using this fix.

**Comment by akhileshverma** [comment]
i have the same problem the selcted extractor cannot be found how to solve it???

**Comment by mascondante** [comment]
lmki
On Dec 29, 2015 2:34 AM, "Anton Skshidlevsky" <notifications@github.com>
wrote:
>
> The latest version of Linux Deploy requires compatible BusyBox:
> https://github.com/meefik/busybox/releases
> https://play.google.com/store/apps/details?id=ru.meefik.busybox
> Previous versions:
> https://github.com/meefik/linuxdeploy/releases
>
> If system BusyBox not working:
> 1) Install compatible BusyBox (https://github.com/meefik/busybox/releases)
> 2) Run BusyBox app.
> 3) Run Linux Deploy app and change "Settings -> BusyBox directory" to
/data/data/ru.meefik.busybox/files/bin

**Comment by girisgc** [comment]
i am unable to install it please help me
i am getting this error
E: The selected extractor cannot be found: ar
my mobile is rooted, busybox installed
![screenshot_2016-02-05-13-58-49](https://cloud.githubusercontent.com/assets/17080975/12842736/a14c8bfe-cc1a-11e5-8416-eaf3c5410f17.png)

**Comment by PPinfor** [comment]
Oh,try it  ---  make the dir named system at root dir be 'read and write'

**Comment by TH30PH4CK3R** [comment]
I had the same problem as suspy69. meefik's version of busybox resolved my issue.

**Comment by sgebauer** [comment]
@meefik Doesn't LinuxDeply already contain a busybox binary? At least on my phone there is one in /data/data/ru.meefik.linuxdeploy/linux/bin .
Including this into $PATH at the top of cli.sh made it work for me without having to install busybox.
This might be a simple permanent fix for this issue, or am I missing something?

**Comment by PPinfor** [comment]
meefik‘s method can solve my problem,you can try it

**Comment by mujtabaimran** [comment]
Hi i am using linux deploy your version but in not only kali in kali rolling or sana what am i select kali rolling or sana?

**Comment by mujtabaimran** [comment]
plz reply meefik

**Comment by mujtabaimran** [comment]
Hi i am use your linux deploy version but in not only kali in kali rolling or sana which i am selected kali rolling or sana ?

**Comment by mrdb2006** [comment]
Solve this problem by installing BusyBox 1.23.2

have good time

**Comment by Greevaz** [comment]
When I tap "Install", it creates the img file, downloads all the required files, but then it fails and says: Failure while installing base packages. How do I fix this ?

**Comment by PPinfor** [comment]
this time,i change the installation path to /linux.img and solved this problem

**Comment by edouardocapelini** [comment]
I have the same problem as Greevaz. it downloads everything and unpack them. and then "failure while installing base packages"
![screenshot_2016-08-09-15-04-43-1](https://cloud.githubusercontent.com/assets/14261811/17521428/d5c703e0-5e42-11e6-8b0c-82bfe3414c3a.jpg)

**Comment by PackOsBeta** [comment]
My solution was change the BusyBox for this https://play.google.com/store/apps/details?id=ru.meefik.busybox

**Comment by riramar** [comment]
I'm having the same issues (failure while installing base packages) and using the same BusyBox as you.
Anyone was able to solve this issue? I'm using a rooted Nexus 5.

**Comment by Greevaz** [comment]
Someone please help us !!!

**Comment by g4njawizard** [comment]
@Greevaz check that out. this could help you. had the same issue.
https://github.com/meefik/linuxdeploy/issues/555

**Comment by fndpena** [comment]
@meefik may I uninstall Stericson Busybox and install yours in the same folder (/su/xbin)? Systemless root here. I noticed that when I uninstall stericson's busybox using the button inside the app, it tells me busybox is not installed, but when I check the folder /su/xbin folder it's still full of files. Do I need to manually remove anything?

**Comment by sloshnmosh** [comment]
Unistalling busybox and installing meefik busybox from playstore and following instructions such as:
If system BusyBox not working:
1) Install compatible BusyBox (https://github.com/meefik/busybox/releases)
2) Run BusyBox app.
3) Run Linux Deploy app and change "Settings -> BusyBox directory" to /data/data/ru.meefik.busybox/files/bin
4) Run "Settings -> Update ENV".
Worked fine for me! Cricket Alcatel one touch idol 3.  THANKS SO MUCH!

**Comment by Avayerd** [comment]
Help me

**Comment by Avayerd** [comment]
![Screenshot_2019-08-24-01-47-48-13](https://user-images.githubusercontent.com/425
![Screenshot_2019-08-24-01-47-32-99](https://user-images.githubusercontent.com/42517794/63631324-067c3f00-c650-11e9-9d05-42cd1ff9a1bc.png)
![Screenshot_2019-08-24-01-47-18-53](https://user-images.githubusercontent.com/42517794/63631329-12680100-c650-11e9-8b69-2f1cb3a045b1.png)

17794/63631313-dcc31800-c64f-11e9-8e43-73201172a291.png)

Help me

**Comment by Avayerd** [comment]
![Screenshot_2019-08-24-01-47-48-13](https://user-images.githubusercontent.com/42517794/63631338-417e7280-c650-11e9-8fdb-69d307d0c4a9.png)

Help me
