### ISSUE TITLE
Greetings!I have a little problem about environment...

### ISSUE THREAD

**Issue by mehmetburakeker** [meefik/linuxdeploy#345]
Hi , I am having a problem with updating environment and i have searched much on google.I would like   get help by a professional.

---

Updating environment ... fail

> > > install
> > > The container is already mounted. 
> > > ## <<< install

---

Updating environment ... + export PATH=/data/data/ru.meefik.linuxdeploy/linux/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
- chmod -R 755 /data/data/ru.meefik.linuxdeploy/linux/bin
- find /data/data/ru.meefik.linuxdeploy/linux/bin
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/bin
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/bin/mke2fs
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/bin/qemu-i386-static
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/bin/tar
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/bin/busybox
- read f
- chmod -R 755 /data/data/ru.meefik.linuxdeploy/linux/etc
- find /data/data/ru.meefik.linuxdeploy/linux/etc
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/etc
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/etc/deploy.conf
- read f
- chmod -R 755 /data/data/ru.meefik.linuxdeploy/linux/share
- find /data/data/ru.meefik.linuxdeploy/linux/share
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/android-groups
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/debootstrap
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/devices.tgz
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/functions
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/breezy
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/dapper
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/edgy
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/etch
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/etch-m68k
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/feisty
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/gutsy
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/hardy
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/hoary
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/hoary.buildd
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/intrepid
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/jaunty
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/jessie
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/kali
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/karmic
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/lenny
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/lucid
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/maverick
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/moto
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/natty
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/oldstable
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/oneiric
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/potato
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/precise
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/quantal
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/raring
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/sana
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/sarge
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/sarge.buildd
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/sarge.fakechroot
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/saucy
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/sid
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/squeeze
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/stable
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/stretch
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/testing
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/trusty
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/unstable
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/utopic
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/vivid
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/warty
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/warty.buildd
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/wheezy
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/wily
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/woody
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/woody.buildd
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/pkgdetails
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/xorg.conf
- read f
- /data/data/ru.meefik.linuxdeploy/linux/bin/busybox --install -s /data/data/ru.meefik.linuxdeploy/linux/bin
- sed -i s|^#!.*|#!/data/data/ru.meefik.linuxdeploy/linux/bin/ash|g /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy
- sed -i s|^ENV_DIR=.*|ENV_DIR="/data/data/ru.meefik.linuxdeploy/linux"|g /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy
- exit 0
  fail
  Updating environment ... + export PATH=/data/data/ru.meefik.linuxdeploy/linux/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
- chmod -R 755 /data/data/ru.meefik.linuxdeploy/linux/bin
- read f
- find /data/data/ru.meefik.linuxdeploy/linux/bin
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/bin
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/bin/mke2fs
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/bin/qemu-i386-static
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/bin/tar
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/bin/busybox
- read f
- chmod -R 755 /data/data/ru.meefik.linuxdeploy/linux/etc
- find /data/data/ru.meefik.linuxdeploy/linux/etc
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/etc
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/etc/deploy.conf
- read f
- chmod -R 755 /data/data/ru.meefik.linuxdeploy/linux/share
- find /data/data/ru.meefik.linuxdeploy/linux/share
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/android-groups
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/debootstrap
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/devices.tgz
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/functions
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/breezy
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/dapper
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/edgy
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/etch
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/etch-m68k
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/feisty
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/gutsy
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/hardy
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/hoary
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/hoary.buildd
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/intrepid
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/jaunty
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/jessie
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/kali
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/karmic
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/lenny
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/lucid
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/maverick
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/moto
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/natty
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/oldstable
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/oneiric
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/potato
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/precise
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/quantal
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/raring
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/sana
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/sarge
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/sarge.buildd
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/sarge.fakechroot
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/saucy
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/sid
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/squeeze
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/stable
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/stretch
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/testing
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/trusty
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/unstable
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/utopic
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/vivid
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/warty
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/warty.buildd
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/wheezy
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/wily
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/woody
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/scripts/woody.buildd
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/debootstrap/pkgdetails
- read f
- chmod 755 /data/data/ru.meefik.linuxdeploy/linux/share/xorg.conf
- read f
- /data/data/ru.meefik.linuxdeploy/linux/bin/busybox --install -s /data/data/ru.meefik.linuxdeploy/linux/bin
- sed -i s|^#!.*|#!/data/data/ru.meefik.linuxdeploy/linux/bin/ash|g /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy
- sed -i s|^ENV_DIR=.*|ENV_DIR="/data/data/ru.meefik.linuxdeploy/linux"|g /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy
- exit 0
  fail
  >>> install
- export PATH=/data/data/ru.meefik.linuxdeploy/linux/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
- export LINUXDEPLOY_DIR=/data/data/ru.meefik.linuxdeploy/linux
- echo >>> install
- /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy install
  The container is already mounted. 
  <<< install
- echo <<< install
## \+ exit 0

Sorry for mess.

Kind regards, Escorpioneer.

**Comment by meefik** [comment]
Please, try version 1.5.4
