### ISSUE TITLE
Issues installing on Xperia Z1 - 14.6.A.1.216

### ISSUE THREAD

**Issue by threader** [meefik/linuxdeploy#346]
Hi, 

Some issues on 5.1.1 - same as https://github.com/meefik/linuxdeploy/issues/256 ? 

Updating configuration file ... done
>>> install
Checking installation path ... ash: write error: Socket operation on non-socket
ash: write error: Socket operation on non-socket
done 
ash: write error: Socket operation on non-socket
Making new disk image (4000 MB) ... dd: /storage/sdcard1/Kali/linux.img: Invalid argument
4000+0 records in
4000+0 records out
4194304000 bytes (3.9GB) copied, 350.482203 seconds, 11.4MB/s
ash: write error: Socket operation on non-socket
ash: write error: Socket operation on non-socket
done 
fail 
<<< install
Updating configuration file ... done
>>> start
Mounting partitions:  
ash: write error: Socket operation on non-socket
/ ... ash: write error: Socket operation on non-socket
mount: mounting /dev/loop0 on /data/local/linux failed: Invalid argument
fail 
<<< start
ash: write error: Socket operation on non-socket
Updating configuration file ... done
Updating configuration file ... done
+ export PATH=/data/data/ru.meefik.linuxdeploy/linux/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
+ PATH=/data/data/ru.meefik.linuxdeploy/linux/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
+ export LINUXDEPLOY_DIR=/data/data/ru.meefik.linuxdeploy/linux
+ LINUXDEPLOY_DIR=/data/data/ru.meefik.linuxdeploy/linux
+ echo '>>> start'
>>> start
+ /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy start
+ start_container
+ [ 0 -eq 0 ]
+ mount_container
+ [ 0 -eq 0 ]
+ mount_container root proc sys selinux dev tty pts shm binfmt_misc custom
+ [ 10 -eq 0 ]
+ msg Mounting partitions: 
+ echo Mounting partitions:  
Mounting partitions:  
ash: write error: Socket operation on non-socket
+ mount_part root
+ msg -n / ... 
+ echo -n / ... 
/ ... ash: write error: Socket operation on non-socket
+ grep -c  /data/local/linux  /proc/mounts
+ local is_mnt=0
+ [ 0 -eq 0 ]
+ [ -d /data/local/linux ]
+ [ -d /storage/sdcard1/Kali/linux.img ]
+ local mnt_opts=rw,relatime
+ mount -o rw,relatime /storage/sdcard1/Kali/linux.img /data/local/linux
mount: mounting /dev/loop0 on /data/local/linux failed: Invalid argument
fail 
<<< start
+ [ 255 -eq 0 ]
+ msg fail
+ echo fail 
ash: write error: Socket operation on non-socket
+ return 1
+ [ 1 -ne 0 ]
+ return 1
+ [ 1 -ne 0 ]
+ return 1
+ [ 1 -ne 0 ]
+ return 1
+ echo '<<< start'
+ exit 0
Updating configuration file ... done
+ export PATH=/data/data/ru.meefik.linuxdeploy/linux/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
+ PATH=/data/data/ru.meefik.linuxdeploy/linux/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
+ export LINUXDEPLOY_DIR=/data/data/ru.meefik.linuxdeploy/linux
+ LINUXDEPLOY_DIR=/data/data/ru.meefik.linuxdeploy/linux
+ echo '>>> install'
>>> install
+ /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy install
+ install_container
+ prepare_container
+ container_mounted
+ grep -c  /data/local/linux  /proc/mounts
Checking installation path ... + local is_mnt=0
+ [ 0 -eq 0 ]
+ return 1
+ msg -n Checking installation path ... 
+ echo -n Checking installation path ... 
ash: write error: Socket operation on non-socket
+ [ -e /storage/sdcard1/Kali/linux.img -a ! -f /storage/sdcard1/Kali/linux.img ]
+ msg done
+ echo done 
ash: write error: Socket operation on non-socket
+ [ file = file ]
+ [ 4000 -eq 0 ]
+ msg -n Making new disk image (4000 MB) ... 
+ echo -n Making new disk image (4000 MB) ... 
ash: write error: Socket operation on non-socket
done 
Making new disk image (4000 MB) ... + expr 4000 - 1
+ dd if=/dev/zero of=/storage/sdcard1/Kali/linux.img bs=1048576 seek=3999 count=1
dd: /storage/sdcard1/Kali/linux.img: Invalid argument
+ dd if=/dev/zero of=/storage/sdcard1/Kali/linux.img bs=1048576 count=4000
4000+0 records in
4000+0 records out
4194304000 bytes (3.9GB) copied, 359.797523 seconds, 11.1MB/s
done 
fail 
+ [ 0 -eq 0 ]
+ msg done
+ echo done 
ash: write error: Socket operation on non-socket
+ msg fail
+ echo fail 
ash: write error: Socket operation on non-socket
+ return 1
+ [ 1 -ne 0 ]
+ return 1
<<< install
+ echo '<<< install'
+ exit 0
Updating configuration file ... done
+ export PATH=/data/data/ru.meefik.linuxdeploy/linux/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
+ PATH=/data/data/ru.meefik.linuxdeploy/linux/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
+ export LINUXDEPLOY_DIR=/data/data/ru.meefik.linuxdeploy/linux
+ LINUXDEPLOY_DIR=/data/data/ru.meefik.linuxdeploy/linux
+ echo '>>> install'
>>> install
+ /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy install
+ install_container
+ prepare_container
+ container_mounted
+ grep -c  /data/local/linux  /proc/mounts
Checking installation path ... done 
+ local is_mnt=0
+ [ 0 -eq 0 ]
+ return 1
+ msg -n Checking installation path ... 
+ echo -n Checking installation path ... 
ash: write error: Socket operation on non-socket
+ [ ! -b /dev/block/mmcblk1p2 ]
+ msg done
+ echo done 
ash: write error: Socket operation on non-socket
+ [ partition = file ]
+ [ partition = file -o partition = partition ]
+ local fs_support=
+ grep -c ext4 /proc/filesystems
Making file system (ext4) ... + [ 1 -gt 0 ]
+ fs_support=ext4
+ break
+ [ -z ext4 ]
+ [ auto = auto ]
+ FS_TYPE=ext4
+ msg -n Making file system (ext4) ... 
+ echo -n Making file system (ext4) ... 
ash: write error: Socket operation on non-socket
+ losetup+  -a
grep -c /dev/block/mmcblk1p2
+ local loop_exist=0
+ grep -c /dev/block/mmcblk1p2 /proc/mounts
+ local img_mounted=0
+ [ 0 -ne 0 -o 0 -ne 0 ]
+ mke2fs -qF -t ext4 -O ^has_journal /dev/block/mmcblk1p2
ext2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /dev/block/mmcblk1p2 is mounted.
+ [ 0 -eq 0 ]
+ msg done
+ echo done 
ash: write error: Socket operation on non-socket
+ msg fail
+ echo fail 
ash: write error: Socket operation on non-socket
+ return 1
+ [ 1 -ne 0 ]
+ return 1
done 
fail 
<<< install
+ echo '<<< install'
+ exit 0
Updating configuration file ... done
Updating configuration file ... done
+ export PATH=/data/data/ru.meefik.linuxdeploy/linux/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
+ PATH=/data/data/ru.meefik.linuxdeploy/linux/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
+ export LINUXDEPLOY_DIR=/data/data/ru.meefik.linuxdeploy/linux
+ LINUXDEPLOY_DIR=/data/data/ru.meefik.linuxdeploy/linux
+ echo '>>> install'
>>> install
+ /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy install
+ install_container
+ prepare_container
+ container_mounted
+ grep -c  /data/local/linux  /proc/mounts
+ local is_mnt=0
+ [ 0 -eq 0 ]
+ return 1
+ msg -n Checking installation path ... 
+ echo -n Checking installation path ... 
Checking installation path ... ash: write error: Socket operation on non-socket
+ [ ! -b /dev/block/mmcblk1p2 ]
+ msg done
+ echo done 
done 
ash: write error: Socket operation on non-socket
+ [ partition = file ]
+ [ partition = file -o partition = partition ]
+ local fs_support=
+ grep -c ext4 /proc/filesystems
Making file system (ext4) ... + [ 1 -gt 0 ]
+ fs_support=ext4
+ break
+ [ -z ext4 ]
+ [ auto = auto ]
+ FS_TYPE=ext4
+ msg -n Making file system (ext4) ... 
+ echo -n Making file system (ext4) ... 
ash: write error: Socket operation on non-socket
+ losetup -a
+ grep -c /dev/block/mmcblk1p2
+ local loop_exist=0
+ grep -c /dev/block/mmcblk1p2 /proc/mounts
+ local img_mounted=0
+ [ 0 -ne 0 -o 0 -ne 0 ]
+ mke2fs -qF -t ext4 -O ^has_journal /dev/block/mmcblk1p2
ext2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /dev/block/mmcblk1p2 is mounted.
done 
fail 
+ [ 0 -eq 0 ]
+ msg done
+ echo done 
ash: write error: Socket operation on non-socket
+ msg fail
+ echo fail 
ash: write error: Socket operation on non-socket
+ return 1
+ [ 1 -ne 0 ]
+ return 1
+ echo '<<< install'
+ exit 0
<<< install
Updating configuration file ... done
+ export PATH=/data/data/ru.meefik.linuxdeploy/linux/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
+ PATH=/data/data/ru.meefik.linuxdeploy/linux/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
+ export LINUXDEPLOY_DIR=/data/data/ru.meefik.linuxdeploy/linux
+ LINUXDEPLOY_DIR=/data/data/ru.meefik.linuxdeploy/linux
+ echo '>>> install'
>>> install
+ /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy install
+ install_container
+ prepare_container
+ container_mounted
+ grep -c  /data/local/linux  /proc/mounts
+ local is_mnt=0
+ [ 0 -eq 0 ]
+ return 1
+ msg -n Checking installation path ... 
+ echo -n Checking installation path ... 
Checking installation path ... ash: write error: Socket operation on non-socket
+ [ ! -b /dev/block/mmcblk1p2 ]
+ msg done
+ echo done 
done 
ash: write error: Socket operation on non-socket
+ [ partition = file ]
+ [ partition = file -o partition = partition ]
+ local fs_support=
+ grep -c ext4 /proc/filesystems
+ [ 1 -gt 0 ]
+ fs_support=ext4
+ break
+ [ -z ext4 ]
+ [ auto = auto ]
+ FS_TYPE=ext4
+ msg -n Making file system (ext4) ... 
+ echo -n Making file system (ext4) ... 
Making file system (ext4) ... ash: write error: Socket operation on non-socket
+ losetup -a
+ grep -c /dev/block/mmcblk1p2
+ local loop_exist=0
+ grep -c /dev/block/mmcblk1p2 /proc/mounts
+ local img_mounted=0
+ [ 0 -ne 0 -o 0 -ne 0 ]
+ mke2fs -qF -t ext4 -O ^has_journal /dev/block/mmcblk1p2
ext2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /dev/block/mmcblk1p2 is mounted.
+ [ 0 -eq 0 ]
+ msg done
+ echo done 
ash: write error: Socket operation on non-socket
+ msg fail
+ echo fail 
ash: write error: Socket operation on non-socket
+ return 1
+ [ 1 -ne 0 ]
+ return 1
done 
fail 
<<< install
+ echo '<<< install'
+ exit 0

**Comment by meefik** [comment]
Please, try version 1.24.1-20 https://github.com/meefik/busybox/releases/tag/1.24.1

**Comment by Zerzix** [comment]
error persists, I experience no errors installing or running on any other devices. this may be an Xperia specific issue.

**Comment by meefik** [comment]
Try static version of compatible BusyBox: https://yadi.sk/d/fBZdWQt7mmXci

**Comment by threader** [comment]
Thanks, compiled latest git some time ago and dumped it in /system/bin, however it says "Requires an installed busybox"  , permissions are correct and everything. BusyBox v1.25.0.git (2016-01-04 08:04:19 GMT) multi-call binary.
Noticed the path to /data/data/ru.meefik.linuxdeploy/files/bin/linuxdeploy here is is /data/data/ru.meefik.linuxdeploy/linux/bin - going to try reinstalling linux deploy, cant update env because of the busybox issue

Thanks
-Mike

**Comment by meefik** [comment]
@threader 
Change "Linux Deploy -> Settings -> BusyBox directory" to /system/bin

**Comment by threader** [comment]
Did that too. Should have stuck with android 4.4 ,everything was working there..

**Comment by threader** [comment]
I havent enabled global write though, so i cant remount /system without rebooting to recovery, could that explain anything?

**Comment by meefik** [comment]
@threader 
Please, try this version of compatible BusyBox: https://yadi.sk/d/fBZdWQt7mmXci
and install all applets: /system/xbin/busybox --install -s /system/xbin
This version differs from the standard BusyBox.

**Comment by threader** [comment]
Ok, will do , thanks.

**Comment by threader** [comment]
Ah, that worked, busybox --install -s /system/xbin was whats missing.

**Comment by threader** [comment]
Now on to install :>

**Comment by threader** [comment]
Success.
