### ISSUE TITLE
main.sh: getopts not found

### ISSUE THREAD

**Issue by coax75ohm** [meefik/linuxdeploy#348]
After updating to 1.5.4-182 from the play store, start up is failing:

```
Updating configuration file ... done
+ PATH=/data/data/ru.meefik.linuxdeploy/files/bin:/system/xbin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
+ printf >>> start

>>> start
+ linuxdeploy -t start
/data/data/ru.meefik.linuxdeploy/files/bin/linuxdeploy: /data/data/ru.meefik.linuxdeploy/files/share/main.sh: line 1992: getopts: not found
/data/data/ru.meefik.linuxdeploy/files/bin/linuxdeploy: shift: line 1993: Illegal number: -1
+ printf <<< start

<<< start
+ exit 0
```

It appears that my busybox ash doesn't support getopts, is there a recommended version to use?

**Comment by meefik** [comment]
Please, install compatible BusyBox (https://github.com/meefik/busybox/releases).

**Comment by hattwj** [comment]
That worked for me. It would be most excellent if this was the default error message.

**Comment by ruleh** [comment]
Getopts is also integrated in bash. Using bash to run the script should work as well.

**Comment by hattwj** [comment]
I think my problem was that busybox updated from the play store and I hadn't installed the new version. Not sure exactly, but the solution was to reinstall busybox after updating it. Although using bash to run the script might fix the problem, the default behavior from the UI lead to this error.

**Comment by meefik** [comment]
Linux Deploy used ash shell, by default /system/xbin/ash (see Settings - Busybox directory).

**Comment by ruleh** [comment]
I can't find it.
Bustbox directory shows "/system/xbin"
I can't find "ash" anywhere in the settings.

**Comment by meefik** [comment]
If system BusyBox not working:
1) Install compatible BusyBox (https://github.com/meefik/busybox/releases)
2) Run BusyBox app.
3) Change "LD - Settings - BusyBox directory" to /data/data/ru.meefik.busybox/files/bin
