### ISSUE TITLE
SetGID Permission Denied

### ISSUE THREAD

**Issue by DotERM** [meefik/linuxdeploy#349]
Hi. I Installed Debian Wheezy and everything was fine, but when i tried to su to install apps, the terminal show:

> su
Password: 
setgid: Permission Denied

So i thinked "if su doesn't work, try "sudo su"

> sudo su
sudo: PERM_ROOT (0, -1, -1) PERMISSION DENIED

I'm a newbie to linux and i expected this to work, but i don't know what to do. Pls help
Info about phone:

GT-I9300 (Galaxy S3)
Android 4.3 (Stock)
Rooted

**Comment by meefik** [comment]
#342

**Comment by DotERM** [comment]
Fixed by installing new ROM with version 4.2.2 instead of 4.3!
