### ISSUE TITLE
Failure to update libpam-systemd in 14.04 due to missing logind init script

### ISSUE THREAD

**Issue by mascondante** [meefik/linuxdeploy#362]
This little issue in Trusty causes some packages not to install properly. Particularly LXDE, KDE and other DEs. Per https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1325142 comment #38 the solution could be added into your script.

# dpkg-divert --local --add /etc/init.d/systemd-logind
# ln -s /bin/true /etc/init.d/systemd-logind

Then proceed with apt-get and and all is well.

**Comment by cloud9350** [comment]
Thanks! I solve install unity issue!
