### ISSUE TITLE
"cpio: cat_set_file not permitted" when installing ping and fping

### ISSUE THREAD

**Issue by jwulf** [meefik/linuxdeploy#364]
I encrypted my android device's drive using the Android dm-crypt feature in settings, and suddenly I couldn't install anything using `dnf` or `rpm` in my Fedora install. 

The error is `cpio cat_set_file not permitted`. 

The symptoms are similar to this docker issue: https://github.com/docker/docker/issues/6980

I decrypted the drive, but I still can't install software. Same error message. 

I'm not sure if encrypting the drive is the cause, but it's the only thing that I did around the time the issue appeared that I can remember.

**Comment by jwulf** [comment]
Here are a couple of examples of what it looks like:

```
# rpm -ivh iputils-20140519-4.fc22.armv7hl.rpm 
warning: Unable to get systemd shutdown inhibition lock
Preparing...                          ################################# [100%]
Updating / installing...
   1:iputils-20140519-4.fc22          ################################# [100%]
error: unpacking of archive failed on file /usr/bin/ping;5684142e: cpio: cap_set_file
error: iputils-20140519-4.fc22.armv7hl: install failed
```


```
# dnf install fping -y 
...

Running transaction
  Installing  : fping-3.10-3.fc22.armv7hl                                                                                                                             1/1 
Error unpacking rpm package fping-3.10-3.fc22.armv7hl
Error unpacking rpm package fping-3.10-3.fc22.armv7hl
warning: Unable to get systemd shutdown inhibition lock
error: unpacking of archive failed on file /usr/sbin/fping;56841454: cpio: cap_set_file
fping-3.10-3.fc22.armv7hl was supposed to be installed but is not!
  Verifying   : fping-3.10-3.fc22.armv7hl                                                                                                                             1/1 

Failed:
  fping.armv7hl 3.10-3.fc22   
```

**Comment by jwulf** [comment]
Actually, it's only those two packages and those two files that it fails on - that I can find. I just install `httpd` and `mosh` with no issues.

**Comment by jwulf** [comment]
Android 4.1.2. That could be the issue - this Red Hat bug https://bugzilla.redhat.com/show_bug.cgi?id=648654 says:

"When files are marked to have file system based capabilities, that is basically a request for setuid on older kernels or if someone has compiled their kernel without file system based capabilities turned on."

**Comment by cloud9350** [comment]
Hmm.. If you slove issue, please close this issue.

**Comment by jwulf** [comment]
I've installed Android 4.3.1, now I'm having trouble creating the image file. It fails at the dd command.

**Comment by cloud9350** [comment]
Instal recommand busybox. and try again.
https://play.google.com/store/apps/details?id=ru.meefik.busybox&hl=ko
