### ISSUE TITLE
Something is not right in latest Version 1.5.5-188

### ISSUE THREAD

**Issue by enekux** [meefik/linuxdeploy#367]
Hello,

first of all thank you very much for all your work it is pretty amazing ;-)

Since I installed the latest version of Linux Deploy version 1.5.5-188 (and also the latest BusyBox version v1.24.1 I am unable to deploy a working image. SSH service will work fine but VNC will fail. When I attempt to run apt-get update over SSH session the system complains that the command is not found...

Does anybody have any problem?

Thank you

**Comment by meefik** [comment]
Thanks! What is wrong?

**Comment by enekux** [comment]
Hi,

here are logs from Start process:

Starting services: 
SSH [:22] ... stdin: is not a tty
done
VNC [:5900] ... stdin: is not a tty
-su: vncserver: command not found
fail
<<< start

This is weird because tightvncserver is installed... as I mentioned before I can run apt-get update only if I am connected over the terminal if I connect over ssh no system commands are found... maybe a problem with ENV?

I have reinstalled all the apps deployed multiple distributions... Also tried it in different devices but I get same sympthoms in all. I didn't have such a problem in previous version...

Any suggestion?

Thanks

**Comment by meefik** [comment]
Yes.. This problem fixed in version 1.5.5-189

**Comment by enekux** [comment]
Hello,

I confirm that the latest version fixed the mentioned issue.

We are back on the road ;-)

Thanks
