### ISSUE TITLE
Problem installing packages

### ISSUE THREAD

**Issue by enekux** [meefik/linuxdeploy#369]
Hi,

with latest versions of Linux Deploy and Busybox I can no longer install packages with apt-get. I get next error:

root@localhost:/# apt-get install aptitude
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  aptitude-common aptitude-doc-en libclass-accessor-perl
  libcwidget3 libio-string-perl libparse-debianchangelog-perl
  libsub-name-perl libtimedate-perl libxapian22
Suggested packages:
  debtags apt-xapian-index libcwidget-dev libhtml-parser-perl
  libhtml-template-perl libxml-simple-perl xapian-tools
The following NEW packages will be installed:
  aptitude aptitude-common aptitude-doc-en libclass-accessor-perl
  libcwidget3 libio-string-perl libparse-debianchangelog-perl
  libsub-name-perl libtimedate-perl libxapian22
0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 4,662 kB of archives.
After this operation, 18.3 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://ftp.debian.org/debian/ jessie/main libcwidget3 armhf 0.5.17-2 [302 kB]
Get:2 http://ftp.debian.org/debian/ jessie/main aptitude-common all 0.6.11-1 [1,576 kB]
Get:3 http://ftp.debian.org/debian/ jessie/main libxapian22 armhf 1.2.19-1 [887 kB]
Get:4 http://ftp.debian.org/debian/ jessie/main aptitude armhf 0.6.11-1+b1 [1,327 kB]
Get:5 http://ftp.debian.org/debian/ jessie/main aptitude-doc-en all 0.6.11-1 [419 kB]
Get:6 http://ftp.debian.org/debian/ jessie/main libsub-name-perl armhf 0.12-1 [11.7 kB]
Get:7 http://ftp.debian.org/debian/ jessie/main libclass-accessor-perl all 0.34-1 [25.9 kB]
Get:8 http://ftp.debian.org/debian/ jessie/main libio-string-perl all 1.08-3 [12.3 kB]
Get:9 http://ftp.debian.org/debian/ jessie/main libtimedate-perl all 2.3000-2 [42.2 kB]
Get:10 http://ftp.debian.org/debian/ jessie/main libparse-debianchangelog-perl all 1.2.0-1.1 [57.9 kB]
Fetched 4,662 kB in 3s (1,192 kB/s)
dpkg-deb: unrecognized option `--control'
BusyBox v1.24.1-meefik (2015-12-30 14:22:33 MSK) multi-call binary.
Usage: dpkg-deb [-cefxX] FILE [argument]

Perform actions on Debian packages (.debs)

        -c      List contents of filesystem tree
        -e      Extract control files to [argument] directory
        -f      Display control field name starting with [argument]        -x      Extract packages filesystem tree to directory
        -X      Verbose extract
dpkg: error processing archive /var/cache/apt/archives/libcwidget3_0.5.17-2_armhf.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 1
dpkg-deb: unrecognized option `--control'

Any ideas?

Thank you

**Comment by meefik** [comment]
Please, execute the command: env

**Comment by enekux** [comment]
root@localhost:/# env
EMULATED_STORAGE_SOURCE=/mnt/shell/emulated
ANDROID_STORAGE=/storage
HOSTNAME=jflte
SHELL=/bin/bash
TERM=linux
LOOP_MOUNTPOINT=/mnt/obb
ASEC_MOUNTPOINT=/mnt/asec
ANDROID_PROPERTY_WORKSPACE=8,0
ANDROID_SOCKET_zygote=9
ANDROID_ASSETS=/system/app
ANDROID_BOOTLOGO=1
USER=root
SECONDARY_STORAGE=/storage/extSdCard
KNOX_STORAGE=/data/knox/ext_sdcard
PATH=/data/data/ru.meefik.linuxdeploy/files/bin:/system/xbin:/data/data/com.sonelli.juicessh/files/bin/arm/pie:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/apache-xml.jar:/system/framework/sec_edm.jar:/system/framework/seccamera.jar:/system/framework/scrollpause.jar:/system/framework/stayrotation.jar:/system/framework/smartfaceservice.jar:/system/framework/smartbondingservice.jar:/system/framework/commonimsinterface.jar:/system/framework/imsmanager.jar:/system/framework/secocsp.jar:/system/framework/secEmailBC.jar:/system/framework/knoxvpnuidtag.jar
VIBE_PIPE_PATH=/dev/pipes
ANDROID_DATA=/data
PWD=/
LANG=en_US.UTF-8
PS1=${debian_chroot:+($debian_chroot)}\u@\h:\w\$
ANDROID_VERSION=5.0.1
JUICESSH_BIN_DIR=/data/data/com.sonelli.juicessh/files/bin/arm/pie
MKSH=/system/bin/sh
HOME=/root
SHLVL=3
ANDROID_ROOT=/system
LOGNAME=root
EXTERNAL_STORAGE=/storage/emulated/legacy
MC_AUTH_TOKEN_PATH=/efs
EMULATED_STORAGE_TARGET=/storage/emulated
JUICESSH_VERSION=2.1.2
SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar
_=/system/xbin/env
root@localhost:/#

**Comment by meefik** [comment]
Use "linuxdeploy shell -u root" instead "linuxdeploy shell" for overwrite Android variables.

**Comment by enekux** [comment]
~$ su
root@jflte:/storage/emulated/0 # /data/data/ru
ru.meefik.busybox/               ru.meefik.linuxdeploy/
/ru.meefik.linuxdeploy/files/bin/linuxdeploy shell -u root       <
Debian GNU/Linux 8 (jessie) [running on Android via Linux Deploy]
root@localhost:~# apt-get install aptitude
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  aptitude-common aptitude-doc-en libclass-accessor-perl
  libcwidget3 libio-string-perl libparse-debianchangelog-perl
  libsub-name-perl libtimedate-perl libxapian22
Suggested packages:
  debtags apt-xapian-index libcwidget-dev libhtml-parser-perl
  libhtml-template-perl libxml-simple-perl xapian-tools
The following NEW packages will be installed:
  aptitude aptitude-common aptitude-doc-en libclass-accessor-perl
  libcwidget3 libio-string-perl libparse-debianchangelog-perl
  libsub-name-perl libtimedate-perl libxapian22
0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/4,662 kB of archives.
After this operation, 18.3 MB of additional disk space will be used.
Do you want to continue? [Y/n]
dpkg: unrecoverable fatal error, aborting:
 unable to create `/var/lib/dpkg/updates/tmp.i': Input/output errorE: Sub-process /usr/bin/dpkg returned an error code (2)
E: Failed to write temporary StateFile /var/lib/apt/extended_states.tmp
root@localhost:~#

**Comment by enekux** [comment]
I am using root account in my Android phone Galaxy S4 because of the issue mentioned here:

SetGID Permission Denied #349

in case this could be an issue...

**Comment by enekux** [comment]
Hi,

downgrading to version 1.5.4-183 fixes the mentioned issue...

https://github.com/meefik/linuxdeploy/releases/tag/1.5.4
