### ISSUE TITLE
ext4 (external sdcard) installation failed

### ISSUE THREAD

**Issue by hiruna** [meefik/linuxdeploy#37]
I have a Samsung 32GB Ultra microsd card
My device is Galaxy Note 10.1 (n8010)

I formatted the sdcard into 2 partitions, 1: ext4 and 2: fat32

when i set the path in linux deploy, " /dev/block/mmcblk1p1 " (ext4 partition) and update env and press install,

and after env is updated i get this as output :  

Updating Config... file ... done

> > begin install
> > Checking mount points .... done
> > making file system (ext4) ... fail

anything that i'm doing wrong ?

then i changed the path to : "  /dev/block/vold/179:49 "instead of mmcblk1p1 path
The env updated then it said 

making file sys ext 4 .. done
but after that it returned with this : 

/..... fail

Is there anything i can do ? can you please help me solve this issue ? 

Thanks

**Comment by pks9862728888** [comment]
While installing kali linux as partition in ext2 or ext4 gives error as 

making file system....failed

But while trying to install it in partition 3 gives error as,
[07:34:03] >>> install
[07:34:03] Checking installation path ... done
[07:34:03] Making file system (ext3) ... done
[07:34:17] Mounting partitions: 
[07:34:17] / ... done
[07:34:17] Installing Debian-based distribution: 
[07:34:17] E: The selected extractor cannot be found: ar
[07:34:17] <<< install
So what should I do ? pls help me.

**Comment by EugenNY** [comment]
I had the same problem over and over again. with 1GB, 4GB, auto, ext2, ext4. But then I just rebooted the phone and it installed smooth!

**Comment by BANGLADESHSHOHAG** [comment]
![Screenshot_20190420-132222](https://user-images.githubusercontent.com/49779584/56454230-62b41700-636f-11e9-8f2b-2a140b7993ac.jpg)

**Comment by BANGLADESHSHOHAG** [comment]
Plese solve my problem

**Comment by internauta-maromba** [comment]
in my case i use the path: /storage/extSdCard/linux.img
*Notes, in linux uppercase and lowercase do makes the difference
To find our phone path just go to " My Files > All files > SD memory card " them you can see below of My Files the right path. And in the end you enter the name of your linux to be writing like /kali.img

**Comment by gary02** [comment]
try unmount the sdcard first
