### ISSUE TITLE
No session for pid (pid of lxpolkit)

### ISSUE THREAD

**Issue by enekux** [meefik/linuxdeploy#370]
Hi,

I am running Debian Jessie and when I login via VNC an error pops up "No Session for PID"

The PID belongs to lxpolkit...

In Debian Wheezy does not occur this...

Any ideas?

Thank you

**Comment by cloud9350** [comment]
This is not LinuxDeploy issue.
Please search google.
e.g : No session for PID debian jessie <Desktop environment>
