### ISSUE TITLE
Feature request: Polish translation 

### ISSUE THREAD

**Issue by Cinkoski** [meefik/linuxdeploy#372]
Hi! I'd like to help translate this app to my home language, Polish.

**Comment by cloud9350** [comment]
You know Poliah language? And you can translate?
If you upload translate file, I can commit your tramslate.

**Comment by Cinkoski** [comment]
What file do I need to translate, strings.xml?

**Comment by meefik** [comment]
strings.xml and arrays.xml
See example: https://github.com/meefik/linuxdeploy/tree/master/res/values-ru

**Comment by cloud9350** [comment]
English strings.xml
https://github.com/meefik/linuxdeploy/blob/master/res/values/strings.xml

ENglish arrays.xml
https://github.com/meefik/linuxdeploy/blob/master/res/values/arrays.xml

**Comment by Cinkoski** [comment]
I'm sending the translated files

[values-pl.zip](https://github.com/meefik/linuxdeploy/files/93540/values-pl.zip)

**Comment by cloud9350** [comment]
@Cinkoski Checked. I upload pull request.
@meefik Check pull request please.
