### ISSUE TITLE
Install error: Unknown compression type

### ISSUE THREAD

**Issue by Madnevil** [meefik/linuxdeploy#373]
"Unknown compression type for in .//var/cache/apt/archives/adduser.deb"
It always happen when I try to install any debian distro/version.
For example Fedora 19 installs without problems.

**Comment by cloud9350** [comment]
You must reinstall GNU/Linux.

**Comment by Madnevil** [comment]
No.  I think problem is in busybox. There is issue with ar command.

**Comment by meefik** [comment]
Install compatible BusyBox
https://github.com/meefik/busybox/releases

**Comment by Madnevil** [comment]
Then i get socket error and it is related with ash command. The only solution I found for this moment is install busybox from play then start install and wait until packages are downloading and finaly in this moment (of downloading) install your busybox.

**Comment by meefik** [comment]
@Madnevil 
See #351

**Comment by Madnevil** [comment]
Statc busybox fixed problem. Closed. Thank you
