### ISSUE TITLE
DNS, MTAB, SSH, and VNC all fail

### ISSUE THREAD

**Issue by Steveor** [meefik/linuxdeploy#374]
I have been attempting to load Debian and/or Kali on my Samsung Tab 4 and trying various versions of Linux Deploy and BusyBox with no success.  In my latest attempt DNS, MTAB, SSH, and VNC all fail. I wouldn't be surprised if I left out something obvious but I have done so many iterations of directories, settings and preferences that my memory of all that I have done to this point is a blur.

My log is below. Any assistance in moving my efforts forward would be greatly appreciated.

Updating configuration file ... done
>>> status
Linux Deploy version: 1.5.3-174 
Device: SM-T230 
Android: 4.4.2 
Architecture: armv7l 
Kernel: 3.10.0-4357157 
Memory: 55/1319 MB 
Swap: 0/0 MB 
SELinux: yes 
Loop devices: yes 
Support binfmt_misc: no 
Supported FS: cramfs exfat ext2 ext3 ext4 fuseblk msdos vfat  
Mounted system: unknown 
Running services:  
* SSH: no 
* GUI: no 
Mounted parts on Linux:  
* / 
* /proc 
* /sys 
* /sys/fs/selinux 
* /dev 
* /dev/pts 
* /dev/shm 
Available mount points:  
* /system: 1.4/2.0 GB (ext4) 
* /cache: 0.2/0.2 GB (ext4) 
* /data: 2.5/4.7 GB (ext4) 
* /data/sdext2: 0.4/6.8 GB (ext2) 
* /efs: 0.0/0.0 GB (ext4) 
* /NVM: 0.0/0.0 GB (ext4) 
* /mnt/shell/emulated: 2.4/4.7 GB (sdcardfs) 
* /storage/emulated/0: 2.4/4.7 GB (sdcardfs) 
* /storage/emulated/0/Android/obb: 2.4/4.7 GB (sdcardfs) 
* /storage/emulated/legacy: 2.4/4.7 GB (sdcardfs) 
* /storage/emulated/legacy/Android/obb: 2.4/4.7 GB (sdcardfs) 
* /mnt/media_rw/extSdCard: 0.5/0.5 GB (vfat) 
* /mnt/secure/asec: 0.5/0.5 GB (vfat) 
* /storage/extSdCard: 0.5/0.5 GB (sdcardfs) 
Available partitions:  
fdisk: can't open '/dev/block/loop0'
fdisk: can't open '/dev/block/loop1'
fdisk: can't open '/dev/block/loop2'
fdisk: can't open '/dev/block/loop3'
fdisk: can't open '/dev/block/loop4'
fdisk: can't open '/dev/block/loop5'
fdisk: can't open '/dev/block/loop6'
fdisk: can't open '/dev/block/loop7'
* /dev/block/mmcblk1p1: 540 MB (Win95 FAT32 (LBA)) 
* /dev/block/mmcblk1p2: 7407 MB (Linux) 
Configuration file: 
DEBUG_MODE="y"
TRACE_MODE="n"
MNT_TARGET="/data/local/linux"
IMG_TARGET="/storage/emulator/0/linux.img"
IMG_SIZE="0"
FS_TYPE="ext2"
DEPLOY_TYPE="file"
DISTRIB="kalilinux"
ARCH="armhf"
SUITE="sana"
MIRROR="http://http.kali.org/kali/"
USER_NAME="android"
USER_PASSWORD="changeme"
SERVER_DNS=""
LOCALE="en_US.UTF-8"
DESKTOP_ENV="xfce"
USE_COMPONENTS="desktop xserver vnc ssh"
STARTUP="ssh vnc"
CUSTOM_SCRIPTS=""
CUSTOM_MOUNTS=""
SSH_PORT="22"
VNC_DISPLAY="0"
VNC_DEPTH="16"
VNC_DPI="75"
VNC_GEOMETRY="1280x800"
VNC_ARGS=""
XSERVER_DISPLAY="0"
XSERVER_HOST="127.0.0.1"
FB_DISPLAY="0"
FB_DPI="100"
FB_DEV="/dev/graphics/fb0"
FB_INPUT="/dev/input/event2"
FB_ARGS=""
FB_FREEZE="none"
<<< status
Updating configuration file ... done
>>> start
Mounting partitions:  
/ ... skip 
/proc ... skip 
/sys ... skip 
/sys/fs/selinux ... skip 
/dev ... skip 
/dev/tty ... skip 
/dev/pts ... skip 
/dev/shm ... skip 
Configuring the container:  
dns ... fail 
mtab ... /data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy: line 1989: can't create /data/local/linux/etc/resolv.conf: nonexistent directory
/data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy: line 1989: can't create /data/local/linux/etc/mtab: nonexistent directory
fail 
Starting services:  
SSH [:22] ... ls: /data/local/linux/etc/ssh/: No such file or directory
chroot: can't execute 'su': No such file or directory
chroot: can't execute 'su': No such file or directory
fail 
VNC [:5900] ... chroot: can't execute 'dbus-daemon': No such file or directory
chroot: can't execute 'su': No such file or directory
fail 
<<< start

**Comment by DotERM** [comment]
Do your kernel supports Loop Device?

**Comment by Steveor** [comment]
It appears the kernel supports Loop since the status/log info above reads: "Loop devices: yes."  Is this a safe assumption? If not, how else would I confirm this?

**Comment by scndthe2nd** [comment]
What rom are you using? I didn't have any luck on my note 3 until I
switched to cm12.1.

Is symlink still a thing? I remember toggling that a lot.

Start off by using a 4 g img file with arch and lxfe/lxce. After thats
confirmed working, then try other stuff.

**Comment by Steveor** [comment]
Now I'm back to square one.   When I start I get the following:

Mounting partitions:  
 / ... fail 
mount: mounting /storage/extSdCard/linux.img on /data/local/linux failed: No such file or directory

The above path is to a 4 GB Sourceforge Kali basic image on my ext2 partition of my external SD card. I have also done dozens of different iterations of settings and preferences, read dozens of forum posts but can't get this to work. I was able to get the aforementioned image working through the Complete Linux Installer app but I couldnt solve a VNC gray screen issue. I have a feeling I'm making a very basic mistake but dont know enough to recognize it.

On the plus side I've learned alot about Linux command line and file structure this past week or so.

**Comment by scndthe2nd** [comment]
oh, youre using the wrong ui. use a different desktop environment

**Comment by Steveor** [comment]
I had it initially set to LXDE.  But then I cycled through all of them and got the same results.

My output:
Mounting partitions:  
+ / ... mount_part root
+ msg -n / ... 
+ echo -n / ... 
+ grep -c  /data/local/linux  /proc/mounts
+ local is_mnt=0
+ [ 0 -eq 0 ]
+ [ -d /data/local/linux ]
+ [ -d /storage/extSdCard/linux.img ]
+ local mnt_opts=rw,relatime
+ mount -o rw,relatime /storage/extSdCard/linux.img /data/local/linux
+ mount: mounting /storage/extSdCard/linux.img on /data/local/linux failed: No such file or directory

I was trying to understand the coding where the error occurs but I'm not a programmer. The hiccup seems to occur on the lines in bold below. I vaguely understand the mounting process. What could cause the error?

mount_part()
{
case "$1" in
root)
	msg -n "/ ... "
	local is_mnt=$(grep -c " ${MNT_TARGET} " /proc/mounts)
	if [ "${is_mnt}" -eq 0 ]; then
		[ -d "${MNT_TARGET}" ] || mkdir -p ${MNT_TARGET}
		[ -d "${IMG_TARGET}" ] && local mnt_opts="bind" || local mnt_opts="rw,relatime"
		**mount -o ${mnt_opts} ${IMG_TARGET} ${MNT_TARGET}
		[ $? -eq 0 ] && msg "done" || { msg "fail"; return 1; }**
	else
		msg "skip"
	fi
;;

**Comment by meefik** [comment]
If you're using SuperSU, can you try to disable the "separate mount namesace" option in SuperSU.

**Comment by Steveor** [comment]
Did that and received the same result. 

What exactly happens when my image target is mounted to the mount target? And what does mnt_opts="bind" do?

**Comment by Steveor** [comment]
I'm in. Whoo hoo. 

I used a back-asswards way to accomplish the installation but it worked. For the sake of other noobs and to document my process in the event I need to retrace my path, I did the following: 

Instead of using the application to download the image I got mine, kalilinux.BASIC.ext4.20131012.zip, from the following link: http://sourceforge.net/projects/linuxonandroid/files/Kali%20Linux/. I formatted my 16GB SD card with Gparted with a 512MB Fat32 partition and a second 14GB ext2 partition that has the following path on my device: /storage/extSdCard. I placed the the unzipped image and renamed it linux.img. In my Android terminal emulator I mounted the SD card with the following command: mount -t ext2 /dev/block/mmcblk1p2 /storage/extSdCard.  

It is at this stage that I was unable to get the partitions to mount. Then per Mr. Skshidlevsky's advice above I disabled the "Mount namespace separation" option in the SuperSU settings on my Android device, rebooted, remounted the SD card in my terminal emulator and voilà, I was able to open Kali via SSH and VNC. The only hitch through VNC was I had to use the password "kalilinux" instead of "toor" or "changeme" which I learned from this post: http://forum.xda-developers.com/showpost.php?p=51705302&postcount=1993 .   

My Linux Deploy configuration:

Linux Deploy version: 1.5.3-174 
Device: SM-T230 
Android: 4.4.2 
Architecture: armv7l 
Kernel: 3.10.0-4357157 
Memory: 48/1319 MB 
Swap: 0/0 MB 
SELinux: yes 
Loop devices: yes 
Support binfmt_misc: no 
Supported FS: cramfs exfat ext2 ext3 ext4 fuseblk msdos vfat  
Mounted system: Kali GNU/Linux 1.0 
Running services:  
* SSH: yes 
* GUI: no 
Mounted parts on Linux:  
* / 
* /proc 
* /sys 
* /sys/fs/selinux 
* /dev 
* /dev/pts 
* /dev/shm 
* /root/.gvfs 
Available mount points:  
* /system: 1.4/2.0 GB (ext4) 
* /cache: 0.2/0.2 GB (ext4) 
* /data: 2.2/4.7 GB (ext4) 
* /efs: 0.0/0.0 GB (ext4) 
* /NVM: 0.0/0.0 GB (ext4) 
* /mnt/shell/emulated: 2.2/4.7 GB (sdcardfs) 
* /data/sdext2: 5.5/14.1 GB (ext2) 
* /mnt/media_rw/extSdCard: 0.5/0.5 GB (vfat) 
* /mnt/secure/asec: 0.5/0.5 GB (vfat) 
* /storage/extSdCard: 5.5/14.1 GB (sdcardfs) 
* /mnt/asec/com.zpwebsites.linuxonandroid-1: 0.0/0.0 GB (ext4) 
* /mnt/asec/orbotix.sphero-1: 0.0/0.0 GB (ext4) 
* /storage/extSdCard: 5.5/14.1 GB (ext2) 
Available partitions:  
fdisk: can't open '/dev/block/loop3'
fdisk: can't open '/dev/block/loop4'
fdisk: can't open '/dev/block/loop5'
fdisk: can't open '/dev/block/loop6'
fdisk: can't open '/dev/block/loop7'
* /dev/block/mmcblk1p1: 536 MB (Win95 FAT32 (LBA)) 
* /dev/block/mmcblk1p2: 15.3 GB (Linux)

Configuration file
DEBUG_MODE="y"
TRACE_MODE="n"
MNT_TARGET="/data/local/linux"
IMG_TARGET="/storage/extSdCard/linux.img"
IMG_SIZE="0"
FS_TYPE="auto"
DEPLOY_TYPE="file"
DISTRIB="kalilinux"
ARCH="armhf"
SUITE="sana"
MIRROR="http://http.kali.org/kali/"
USER_NAME="root"
USER_PASSWORD="toor"
SERVER_DNS=""
LOCALE="en_US.UTF-8"
DESKTOP_ENV="lxde"
USE_COMPONENTS="vnc xserver desktop ssh"
STARTUP="ssh xserver"
CUSTOM_SCRIPTS=""
CUSTOM_MOUNTS=""
SSH_PORT="22"
VNC_DISPLAY="0"
VNC_DEPTH="16"
VNC_DPI="75"
VNC_GEOMETRY="1280x800"
VNC_ARGS=""
XSERVER_DISPLAY="0"
XSERVER_HOST="127.0.0.1"
FB_DISPLAY="0"
FB_DPI="100"
FB_DEV="/dev/graphics/fb0"
FB_INPUT="/dev/input/event2"
FB_ARGS=""
FB_FREEZE="none"

I am unable to install the various Kali tools via  `apt-get install kali-linux -y` because my /etc/apt/sources.list file is out of date and my attempts to replace it with current info has not been successful. But that issue is for another day.
