### ISSUE TITLE
Unable to install BIND9 in debian-jessie

### ISSUE THREAD

**Issue by enekux** [meefik/linuxdeploy#378]
Hello,

I am trying to install BIND9 in debian-jessie but I get the next error:

root@localhost:/home/eneko# apt-get install bind9        
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  bind9utils geoip-database libbind9-90 libdns100 libgeoip1 libisc95 libisccc90 libisccfg90 liblwres90
Suggested packages:
  dnsutils bind9-doc resolvconf ufw geoip-bin
The following NEW packages will be installed:
  bind9 bind9utils geoip-database libbind9-90 libdns100 libgeoip1 libisc95 libisccc90 libisccfg90 liblwres90
0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/3023 kB of archives.
After this operation, 8309 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Preconfiguring packages ...
Selecting previously unselected package libgeoip1:armhf.
(Reading database ... 28665 files and directories currently installed.)
Preparing to unpack .../libgeoip1_1.6.2-4_armhf.deb ...
Unpacking libgeoip1:armhf (1.6.2-4) ...
Selecting previously unselected package libisc95.
Preparing to unpack .../libisc95_1%3a9.9.5.dfsg-9+deb8u2_armhf.deb ...
Unpacking libisc95 (1:9.9.5.dfsg-9+deb8u2) ...
Selecting previously unselected package libdns100.
Preparing to unpack .../libdns100_1%3a9.9.5.dfsg-9+deb8u2_armhf.deb ...
Unpacking libdns100 (1:9.9.5.dfsg-9+deb8u2) ...
Selecting previously unselected package libisccc90.
Preparing to unpack .../libisccc90_1%3a9.9.5.dfsg-9+deb8u2_armhf.deb ...
Unpacking libisccc90 (1:9.9.5.dfsg-9+deb8u2) ...
Selecting previously unselected package libisccfg90.
Preparing to unpack .../libisccfg90_1%3a9.9.5.dfsg-9+deb8u2_armhf.deb ...
Unpacking libisccfg90 (1:9.9.5.dfsg-9+deb8u2) ...
Selecting previously unselected package libbind9-90.
Preparing to unpack .../libbind9-90_1%3a9.9.5.dfsg-9+deb8u2_armhf.deb ...
Unpacking libbind9-90 (1:9.9.5.dfsg-9+deb8u2) ...
Selecting previously unselected package liblwres90.
Preparing to unpack .../liblwres90_1%3a9.9.5.dfsg-9+deb8u2_armhf.deb ...
Unpacking liblwres90 (1:9.9.5.dfsg-9+deb8u2) ...
Selecting previously unselected package bind9utils.
Preparing to unpack .../bind9utils_1%3a9.9.5.dfsg-9+deb8u2_armhf.deb ...
Unpacking bind9utils (1:9.9.5.dfsg-9+deb8u2) ...
Selecting previously unselected package bind9.
Preparing to unpack .../bind9_1%3a9.9.5.dfsg-9+deb8u2_armhf.deb ...
Unpacking bind9 (1:9.9.5.dfsg-9+deb8u2) ...
Selecting previously unselected package geoip-database.
Preparing to unpack .../geoip-database_20150317-1_all.deb ...
Unpacking geoip-database (20150317-1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for systemd (215-17+deb8u2) ...
Setting up libgeoip1:armhf (1.6.2-4) ...
Setting up libisc95 (1:9.9.5.dfsg-9+deb8u2) ...
Setting up libdns100 (1:9.9.5.dfsg-9+deb8u2) ...
Setting up libisccc90 (1:9.9.5.dfsg-9+deb8u2) ...
Setting up libisccfg90 (1:9.9.5.dfsg-9+deb8u2) ...
Setting up libbind9-90 (1:9.9.5.dfsg-9+deb8u2) ...
Setting up liblwres90 (1:9.9.5.dfsg-9+deb8u2) ...
Setting up bind9utils (1:9.9.5.dfsg-9+deb8u2) ...
Setting up bind9 (1:9.9.5.dfsg-9+deb8u2) ...
Adding group `bind' (GID 111) ...
Done.
Adding system user `bind' (UID 106) ...
Adding new user `bind' (UID 106) with group `bind' ...
Not creating home directory `/var/cache/bind'.
wrote key file "/etc/bind/rndc.key"
#
[FAIL] Starting domain name service...: bind9 failed!
invoke-rc.d: initscript bind9, action "start" failed.
dpkg: error processing package bind9 (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up geoip-database (20150317-1) ...
Processing triggers for libc-bin (2.19-18+deb8u1) ...
Processing triggers for systemd (215-17+deb8u2) ...
Errors were encountered while processing:
 bind9
E: Sub-process /usr/bin/dpkg returned an error code (1)

root@localhost:/home/eneko# service bind9 start
[FAIL] Starting domain name service...: bind9 failed!

I have checked for quite a while and I am starting to think that the start of the daemon is failing due to the chroot environment the linux image is "living" in?

I will be checking next documentation and try some things...

https://wiki.debian.org/Bind9#Bind_Chroot

Does anybody have any idea?

Thank you.

**Comment by meefik** [comment]
Add user bind9 to group aid_inet

**Comment by enekux** [comment]
BRAVO @meefik !

why didn't I post the question before... ;)

FYI I am using Linux Deploy within my Android Box MINIX NEO X7 (http://www.minix.us/products/NEOX7.html) and I have managed to install Owncloud Server + Webmin and BIND9 was the last service that I needed to set it up...

Thanks,

**Comment by enekux** [comment]
In my mobile instead I have managed to install owncloud-client over LXDE (at the current state there is official client for android devices to keep files in sync).

I had a problem with GNOME-KEYRING which would not start automatically but I solved it by removing and re-installing lxsession package:

apt-get remove lxsession; apt-get install lxsession
