### ISSUE TITLE
Xserver error

### ISSUE THREAD

**Issue by Steveor** [meefik/linuxdeploy#379]
I`m running Linux Deploy v1.5.3-174 on a Samsung Tab 4 with Prism Barebone v3.5 ROM and attempting to run Kali via Xserver but I get an error stating:

[14:15:25] X Server [127.0.0.1:0] ... stdin: is not a tty
[14:15:25] -su: /root/.xinitrc: No such file or directory

SSH and VNC open Kali and I have Xserver installed and it opens. But the .xinitrc file is not anywhere in my device.  A Google search has not provided any answers.  Is there a way to make my device compatible?

**Comment by Steveor** [comment]
OK, so I figured out the Linux Deploy application is looking for the .xinitrc file in the Kali image and not in the device (duh... I'll try and keep up). It is located at /etc/X11/xinit in my Kali image and it contains the following:

#!/bin/sh
\# /etc/X11/xinit/xinitrc
\#
\# global xinitrc file, used by all X sessions started by xinit (startx)
\# invoke global X session script
. /etc/X11/Xsession

An excerpt from my latest deployment is:  

+ chroot /data/local/linux su - root -c export DISPLAY=127.0.0.1:1; ~/.xinitrc &
+ stdin: is not a tty
+ done 
+ [ 0 -eq 0 ]
+ msg done
+ -su: /root/.xinitrc: No such file or directory

The Xsession portion of the linuxdeploy code is: 

xserver)
	msg -n "X Server [${XSERVER_HOST}:${XSERVER_DISPLAY}] ... "
	gui_started && { msg "skip"; return 0; }
	dbus_init
	**chroot ${MNT_TARGET} su - ${USER_NAME} -c "export DISPLAY=${XSERVER_HOST}:${XSERVER_DISPLAY}; ~/.xinitrc &"**
	[ $? -eq 0 ] && msg "done" || msg "fail"
;;

The relevant variables and values are:

MNT_TARGET="/data/local/linux"
USER_NAME="root"
XSERVER_DISPLAY="1"
XSERVER_HOST="127.0.0.1"

As I understand it, the code in bold changes root to /data/local/linux, changes user to "root" and then executes DISPLAY=127.0.0.1:1 and the contents of .xinitrc, which is the Xsession executable, in the background. Yet something is screwing up. I'm thinking if I swap the variables it will work but I don't know enough about the process to figure this out.

Someone with a bigger brain please help.

**Comment by cloud9350** [comment]
You must reinstall GNU/Linux.
stddn is not tty = not complete install xserver

**Comment by twaik** [comment]
`stdin: is not a tty` is only a warning and can be ignored.
`/root/.xinitrc: No such file or directory` means that install process is not complete. Try to reinstall an image.
