### ISSUE TITLE
Loging loop

### ISSUE THREAD

**Issue by PinkieXDash** [meefik/linuxdeploy#389]
(English is not my native language, so try to not speak so complex...)
I downloaded this Linux Deploy app, installed Ubuntu with one problem that I already fixed with a little help from the internet. So everything should be fine, right? I click the start button, and I see in every line  "done", except of /dev/tty in wich is "skip". And when I try to connect (tried both web and local) it's asking me about password. When I enter the correct one, the porgram starts to connect me again. One program said I am disconnected from my server before I entered my password. Any ideas?

**Comment by cloud9350** [comment]
Please comment log?

Settings -> Debug enable, Trace mode enable, enable logging file, and start

**Comment by PinkieXDash** [comment]
Here is all of log file: 

Updating configuration file ... done
+ PATH=/data/data/ru.meefik.linuxdeploy/files/bin:/data/data/ru.meefik.busybox/files/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
+ printf >>> start

>>> start
+ linuxdeploy -t start
+ container_start
+ [ 0 -eq 0 ]
+ container_mount
+ [ 0 -eq 0 ]
+ container_mount root proc sys selinux dev tty pts shm binfmt_misc custom
+ [ 10 -eq 0 ]
+ msg Mounting partitions: 
+ echo Mounting partitions: 
+ local item
+ mount_part root
+ msg -n / ... 
+ echo -n / ... 
+ is_mounted /data/local/linux
+ local mount_point=/data/local/linux
+ [ -n /data/local/linux ]
Mounting partitions: 
/ ... + grep -q  /data/local/linux  /proc/mounts
+ 
+ return 1
+ [ -d /data/local/linux ]
+ [ -d /storage/sdcard1/linux.img ]
+ local mnt_opts=rw,relatime
+ mount -o rw,relatime /storage/sdcard1/linux.img /data/local/linux
+ [ 0 -eq 0 ]
+ msg done
+ echo done
+ return 0
+ [ 0 -ne 0 ]
+ mount_part proc
+ msg -n /proc ... 
+ echo -n /proc ... 
+ local target=/data/local/linux/proc
+ is_mounted /data/local/linux/proc
+ local mount_point=/data/local/linux/proc
+ [ -n /data/local/linux/proc ]
done
/proc ... + grep -q  /data/local/linux/proc  /proc/mounts
+ 
+ return 1
+ [ -d /data/local/linux/proc ]
+ mount -t proc proc /data/local/linux/proc
done
+ [ 0 -eq 0 ]
+ msg done
+ echo done
+ return 0
+ [ 0 -ne 0 ]
+ mount_part sys
+ msg -n /sys ... 
+ echo -n /sys ... 
+ local target=/data/local/linux/sys
+ is_mounted /data/local/linux/sys
+ local mount_point=/data/local/linux/sys
+ [ -n /data/local/linux/sys ]
/sys ... + grep -q  /data/local/linux/sys  /proc/mounts
+ 
+ return 1
+ [ -d /data/local/linux/sys ]
+ mount -t sysfs sys /data/local/linux/sys
+ [ 0 -eq 0 ]
+ msg done
+ echo done
+ return 0
+ [ 0 -ne 0 ]
+ mount_part selinux
+ selinux_support
+ [ -d /sys/fs/selinux ]
+ return 0
+ msg -n /sys/fs/selinux ... 
+ echo -n /sys/fs/selinux ... 
+ local target=/data/local/linux/sys/fs/selinux
+ is_mounted /data/local/linux/sys/fs/selinux
+ local mount_point=/data/local/linux/sys/fs/selinux
+ [ -n /data/local/linux/sys/fs/selinux ]
done
/sys/fs/selinux ... + grep -q  /data/local/linux/sys/fs/selinux  /proc/mounts
+ 
+ return 1
+ [ -e /sys/fs/selinux/enforce ]
+ cat /sys/fs/selinux/enforce
+ echo 0
+ mount -t selinuxfs selinuxfs /data/local/linux/sys/fs/selinux
+ mount -o remount,ro,bind /data/local/linux/sys/fs/selinux
done
/dev ... + [ 0 -eq 0 ]
+ msg done
+ echo done
+ return 0
+ [ 0 -ne 0 ]
+ mount_part dev
+ msg -n /dev ... 
+ echo -n /dev ... 
+ local target=/data/local/linux/dev
+ is_mounted /data/local/linux/dev
+ local mount_point=/data/local/linux/dev
+ [ -n /data/local/linux/dev ]
+ grep -q  /data/local/linux/dev  /proc/mounts
+ 
+ return 1
+ [ -d /data/local/linux/dev ]
+ [ -e /dev/fd ]
+ [ -e /dev/stdin ]
+ [ -e /dev/stdout ]
+ [ -e /dev/stderr ]
+ mount -o bind /dev /data/local/linux/dev
+ [ 0 -eq 0 ]
+ msg done
+ echo done
+ return 0
+ [ 0 -ne 0 ]
+ mount_part tty
+ msg -n /dev/tty ... 
+ echo -n /dev/tty ... 
+ [ ! -e /dev/tty0 ]
+ msg skip
+ echo skip
+ return 0
+ [ 0 -ne 0 ]
+ mount_part pts
+ msg -n /dev/pts ... 
+ echo -n /dev/pts ... 
+ local target=/data/local/linux/dev/pts
+ is_mounted /data/local/linux/dev/pts
+ local mount_point=/data/local/linux/dev/pts
+ [ -n /data/local/linux/dev/pts ]
+ grep -q  /data/local/linux/dev/pts  /proc/mounts
done
/dev/tty ... skip
/dev/pts ... done
/dev/shm ... + 
+ return 1
+ [ -d /data/local/linux/dev/pts ]
+ mount -o mode=0620,gid=5 -t devpts devpts /data/local/linux/dev/pts
+ [ 0 -eq 0 ]
+ msg done
+ echo done
+ return 0
+ [ 0 -ne 0 ]
+ mount_part shm
+ msg -n /dev/shm ... 
+ echo -n /dev/shm ... 
+ local target=/data/local/linux/dev/shm
+ is_mounted /data/local/linux/dev/shm
+ local mount_point=/data/local/linux/dev/shm
+ [ -n /data/local/linux/dev/shm ]
+ grep -q  /data/local/linux/dev/shm  /proc/mounts
+ 
+ return 1
+ [ -d /data/local/linux/dev/shm ]
+ mount -t tmpfs tmpfs /data/local/linux/dev/shm
done
+ [ 0 -eq 0 ]
+ msg done
+ echo done
+ return 0
+ [ 0 -ne 0 ]
+ mount_part binfmt_misc
+ multiarch_support
+ [ -d /proc/sys/fs/binfmt_misc ]
+ return 1
+ return 0
+ [ 0 -ne 0 ]
+ mount_part custom
+ local disk
+ return 0
+ [ 0 -ne 0 ]
+ return 0
+ [ 0 -ne 0 ]
+ return 0
+ [ 0 -ne 0 ]
+ container_configure dns mtab
+ [ 2 -eq 0 ]
+ container_mounted
+ is_mounted /data/local/linux
+ local mount_point=/data/local/linux
+ [ -n /data/local/linux ]
Configuring the container: 
dns ... + grep -q  /data/local/linux  /proc/mounts
+ 
+ return 0
+ [ 0 -ne 0 ]
+ msg Configuring the container: 
+ echo Configuring the container: 
+ local item
+ configure_part dns
+ msg -n dns ... 
+ echo -n dns ... 
+ set -e
+ [ -z  ]
+ getprop net.dns1
+ local dns1=192.168.43.1
+ getprop net.dns2
+ local dns2=
+ local dns_list=192.168.43.1 
+ [ -z 192.168.43.1 -a -z  ]
+ printf 
+ local dns
+ echo nameserver 192.168.43.1
+ exit 0
+ [ 0 -eq 0 ]
+ msg done
+ echo done
+ return 0
+ configure_part mtab
+ msg -n mtab ... 
+ echo -n mtab ... 
+ set -e
+ rm -f /data/local/linux/etc/mtab
+ sed s|/data/local/linux/*|/|g
+ grep /data/local/linux /proc/mounts
done
mtab ... done
Starting services: 
SSH [:22] ... + exit 0
+ [ 0 -eq 0 ]
+ msg done
+ echo done
+ return 0
+ return 0
+ msg Starting services: 
+ echo Starting services: 
+ local item
+ container_start ssh
+ [ 1 -eq 0 ]
+ msg -n SSH [:22] ... 
+ echo -n SSH [:22] ... 
+ ssh_started
+ local item pidfile pid
+ pidfile=/data/local/linux/var/run/sshd.pid
+ [ -e /data/local/linux/var/run/sshd.pid ]
+ [ -n  -a -e /proc/ ]
+ pidfile=/data/local/linux/run/sshd.pid
+ [ -e /data/local/linux/run/sshd.pid ]
+ cat /data/local/linux/run/sshd.pid
+ pid=21763
+ [ -n 21763 -a -e /proc/21763 ]
+ return 1
+ [ -e /data/local/linux/var/run -a ! -e /data/local/linux/var/run/sshd ]
+ [ -e /data/local/linux/run -a ! -e /data/local/linux/run/sshd ]
+ ls /data/local/linux/etc/ssh/
+ grep key
+ [ -z ssh_host_dsa_key
ssh_host_dsa_key.pub
ssh_host_ecdsa_key
ssh_host_ecdsa_key.pub
ssh_host_ed25519_key
ssh_host_ed25519_key.pub
ssh_host_rsa_key
ssh_host_rsa_key.pub ]
+ local sshd=`which sshd`
+ chroot_exec -u root `which sshd` -p 22
+ unset TMP TEMP TMPDIR LD_PRELOAD LD_DEBUG
+ [ -u = -u ]
+ local username=root
+ shift 2
+ [ 1 -gt 0 ]
+ chroot /data/local/linux /bin/su - root -c `which sshd` -p 22
stdin: is not a tty
done
VNC [:5901] ... + [ 0 -eq 0 ]
+ msg done
+ echo done
+ return 0
+ [ 0 -eq 0 ]
+ container_start vnc
+ [ 1 -eq 0 ]
+ local vncport=5900
+ let vncport=5900+1
+ msg -n VNC [:5901] ... 
+ echo -n VNC [:5901] ... 
+ gui_started
+ local pidfile pid
+ pidfile=/data/local/linux/tmp/xsession.pid
+ [ -e /data/local/linux/tmp/xsession.pid ]
+ [ -n  -a -e /proc/ ]
+ return 1
+ dbus_init
+ [ -e /data/local/linux/run/dbus/pid ]
+ rm -f /data/local/linux/run/dbus/pid
+ [ -e /data/local/linux/var/run/dbus/dbus.pid ]
+ [ -e /data/local/linux/var/run/messagebus.pid ]
+ chroot_exec -u root dbus-daemon --system --fork
+ unset TMP TEMP TMPDIR LD_PRELOAD LD_DEBUG
+ [ -u = -u ]
+ local username=root
+ shift 2
+ [ 1 -gt 0 ]
+ chroot /data/local/linux /bin/su - root -c dbus-daemon --system --fork
stdin: is not a tty
+ [ -e /data/local/linux/tmp/.X1-lock ]
+ [ -e /data/local/linux/tmp/.X11-unix/X1 ]
+ chroot_exec -u User vncserver :1 -depth 16 -geometry 720x1213 -dpi 75 
+ unset TMP TEMP TMPDIR LD_PRELOAD LD_DEBUG
+ [ -u = -u ]
+ local username=User
+ shift 2
+ [ 1 -gt 0 ]
+ chroot /data/local/linux /bin/su - User -c vncserver :1 -depth 16 -geometry 720x1213 -dpi 75 

New 'X' desktop is localhost:1

Starting applications specified in /home/User/.vnc/xstartup
Log file is /home/User/.vnc/localhost:1.log

done
+ [ 0 -eq 0 ]
+ msg done
+ echo done
+ return 0
+ [ 0 -eq 0 ]
+ [ -z ssh vnc ]
+ return 0
+ printf <<< start

<<< start

**Comment by cloud9350** [comment]
Enter default username and password
id : android
password : changeme

**Comment by PinkieXDash** [comment]
It changed nothing. I also tried few other programs and all of them have loop when there is a need of entering password. Also the VNC doesn't work now.

**Comment by PinkieXDash** [comment]
Accidentally deleted linux.img file. Got so angry I decided to install debian instead. Works. No problems, except for missing files and apps (example : xarchiver can't open archives because of missing file).

**Comment by cloud9350** [comment]
@PinkieXDash When you delete ~/.vnc folder, this problem is being addressed. :worried:
