### ISSUE TITLE
Кастомный дистрибутив

### ISSUE THREAD

**Issue by ghost** [meefik/linuxdeploy#390]
Я хочу запустить свой дистрибутив, как я могу это сделать? 
Хочу попытаться запустить RemixOS.

**Comment by cloud9350** [comment]
«Linux Deploy» пока не поддерживает RemixOS.

Я использую переводчик.
Вы можете получить быстрые ответы на английском языке.

**Comment by meefik** [comment]
Можно запустить свой дистрибутив из заранее подготовленного rootfs-архива. Для этого достаточно указать тип установки "RootFS", в качестве адреса зеркала указать путь к этому архиву и запустить установку.

**Comment by cloud9350** [comment]
@meefik Is it possible?

**Comment by meefik** [comment]
@cloud9350
You can run an unsupported distribution, if you manually prepare rootfs archive (.tgz, .tbz2 or .txz).  This archive can be imported into Linux Deploy: Properties -> Distribution -> RootFS, Properties -> Mirror URL -> /path/to/rootfs and run Properties -> Install.

**Comment by cloud9350** [comment]
@meefik Make a note of something :smile:

**Comment by acterhd** [comment]
Remix OS is not RootFS.

2016-01-26 16:47 GMT+08:00 Gureumi <notifications@github.com>:

**Comment by cloud9350** [comment]
@acterhd RemixOS is only avaliable PC.
You can't install RemixOS to Android.

**Comment by cloud9350** [comment]
@acterhd Remix OS is Android ROM.
You can't install Remix OS.
