### ISSUE TITLE
[Arch] non-root daemons must be added to aid_inet to get network access

### ISSUE THREAD

**Issue by fervi** [meefik/linuxdeploy#393]
In Arch Linux (maybe others) we also have this problem
https://github.com/guardianproject/lildebi/issues/6

User must be added to this group, but it isn't. So he doesn't have a connection to internet.
Solution:
groupadd -g 3003 sockets
usermod -G sockets username

**Comment by scndthe2nd** [comment]
nice find

**Comment by meefik** [comment]
You can use this command with your username:
```sh
adduser username
usermod -a -G aid_inet username
```
