### ISSUE TITLE
How to change image size

### ISSUE THREAD

**Issue by harpreet-s** [meefik/linuxdeploy#395]
Hi ,

I installed file with 2GB size. Is it possible to increase size to 4gb ?

**Comment by cloud9350** [comment]
Installation Settings (Download button) -> scroll down -> find image size menu -> change it

**Comment by harpreet-s** [comment]
I have installed it already with 2GB size and in installation type = file.Now I am out of space. I changed the setting you mentioned , image size = 4096 , however still the image file is of only 2 GB. I don't want to install again from fresh.

**Comment by harpreet-s** [comment]
any hint please !!!!

**Comment by meefik** [comment]
For FAT maximum image size 4095 MB.

**Comment by harpreet-s** [comment]
Thanks for the reply. Sorry but I need some clarity.

I have installed Archlinux with file size = 2048 and type = auto. Now complete 2Gb is used and I want to increase size to 4Gb of existing installation. I change size to 4095 and start. But still the file remains 2GB. How can i make it 4GB , thanks in advance.

**Comment by meefik** [comment]
LD is not supported increase size of image file. New image file will be created at the new installation.
For example, manually increase size of file /mnt/sdcard/linux.img on 3000 MB:
```sh
dd if=/dev/zero bs=1048576 count=3000 >> /mnt/sdcard/linux.img
e2fsck -f /mnt/sdcard/linux.img
resize2fs /mnt/sdcard/linux.img
```

**Comment by harpreet-s** [comment]
heartbreaking :(  Lot of effort lost.
Ok will try a new installation !!!!

**Comment by Fiksdal** [comment]
Hi

It looks like I can use those commands to resize the image? But where do I run them? In Terminal Emulator in Android? Or do I have to copy the image to a linux system, then run them on the image, then move it back?

My external SD card is exFAT formated, so it supports large file sizes. Can I put the image there, and thus have a large image?

Will it run slower from the external SD card than from the internal one?

Thanks in advance!

**Comment by casept** [comment]
@Fiksdal , this reply might be a bit late but yes, these commands have to be run on the android device and yes, you can put the image on external storage. Just keep in mind that in android marshmallow you might need to install the "Marshmallow SD Fix" xposed module to grant linuxDeploy the permission to write to the SD Card.

Also, modern version of android use the ext4 filesystem on the internal storage, which has a file size limit of several exabytes.

**Comment by jfhub** [comment]
Hi,
I have 10,66 Go free on my /storage/external_SD card and the linux.img of 2Go is full to 85%....
How can I boost the image size?

Here is what I get on a terminal:
sudo losetup /dev/loop0
/dev/loop0:  [0021]:3089275592  (/storage/external_SD/linux.img

Thanks,

**Comment by cloud9350** [comment]
@jfhub You must recreate system image file (reinstall)

**Comment by jfhub** [comment]
Thanks for answering,
I did that, but was unable to go up to 8Go, as I wanted.  I setup for 4Go.
Regards,
Jack

**Comment by cloud9350** [comment]
@jfhub MicroSD FAT32 format is single file limit 4 GB

**Comment by pks9862728888** [comment]
I have already downloaded Linux img file. It's 5.56gb after extracting and I installed it via reconfigure using Linux deploy. I am using ext sd card as ROM and installed Linux in ext sd card. But I couldn't upgrade it because of low disk space. So what should I do to increase the I'm size and solve the problem?

**Comment by cloud9350** [comment]
@pks9862728888 No. You must delete the file and work with it.

**Comment by pks9862728888** [comment]
I tried to install kali linux as partition on ext sd card ....partition ext2, but while installing there is error
[06:43:30] >>> deploy
[06:43:31] :: Installing bootstrap/rootfs ... 
[06:43:31] Checking installation path ... done
[06:43:31] Making file system ... fail
[06:43:31] <<< deploy
I tried it with ext4 also but same error, so what should I do ? My mobile is intex cloud q11.

**Comment by droided4u** [comment]
The solution is simple first make a copy of your img file when unmounted then run linux and when inside linux terminal
e2fsck -f /location/to/your/linuxcopy.img
resize2fs /location/to/your/linuxcopy.img 3000M

You can change 3000M part to anything you want M is megabyte.

**Comment by ezbik** [comment]
In my case I also had to reboot Android. Because LinuxDeploy doesn't free losetup table. So old image was still bound as a loop device.

**Comment by ianMihura** [comment]
> dd if=/dev/zero bs=1048576 count=3000 >> /mnt/sdcard/linux.img
> e2fsck -f /mnt/sdcard/linux.img
> resize2fs /mnt/sdcard/linux.img

@meefik 

A code recommendation from the author of LD himself
Tried it and worked
You sir are a genious
[bows]

**Comment by danFromTelAviv** [comment]
for clarification : 
1) close the vnc viewer or other client.
2) stop the linux deploy app ( by clicking on the square stop button on top)
3) open adb shell or otherwise reach the android shell.
4) type in the following commands ( as root ) : 
e2fsck -f /mnt/sdcard/linux.img
resize2fs /mnt/sdcard/linux.img 3000M

comments : 
1) replace 3000 with the amount you want of megabytes ( i.e. 10000 will be 10,000 MB )
2) you may be limited by your sd card ( if its fat 32 - 4Gb max for example )

**Comment by pbranly** [comment]
Hi, this is what I did on my Linux Deploy installation on Beelink Android box (should be valid as well for other android boxes)

I made the installation as File with 4Go and 100% was used (with df command). So I increased the file to to  5Go

step one: stop linux deploy  and from android copy Linux.img from internal SDCARD to  external SDCARD
step two: rename Linux.img to Linux_sav.img in the external SDCARD
step three: copy Linux_sav.img from external  sdcard to internal  sdcard (there is surely easier for the same result but with that  procedure you  have a save of your Linux installation!)
step four:  restart Linux deploy (so from the initial Linux.img)
step five: type sudo unchroot
step  six: cd /mnt/sdcard (verify you  find both Linux.img and Linux-sav.img)
step seven: e2fsck -f linux_sav.img (a lot of errors ....type y each time)
resize2fs linux_sav.img 5000M
step eight: stop Linux deploy and from  android, change name of (old) Linux.img to  something else for security. and rename Linux_sav.img to Linux.img
step Nine: start Linux deploy 

et voila ! in terminal mode, the command df will show the 100% changed to a far smaller value

Good luck

Philippe
PS: it can surely be made more simple but my step  by step worked
