### ISSUE TITLE
Add Chromium OS?

### ISSUE THREAD

**Issue by ToastyMod** [meefik/linuxdeploy#400]
Is there a possibility to add Chromium OS for use in a Chroot?
I would love to use it on the framebuffer.

**Comment by scndthe2nd** [comment]
i had thought of doing this before too. Looking over how chrome works, its
not very efficient with its use of resources.

I was much happier when i discovered arch for this purpose. it's my general
use via framebuffer right now. Give me a shout if you need a hand setting
it up.

**Comment by Bodhijesus** [comment]
Hi scndthe2nd, I am actually having that exact need in helping set up arch via framebuffer, would you be able to take a look?:

https://github.com/meefik/linuxdeploy/issues/485
