### ISSUE TITLE
Add Ubuntu Touch?

### ISSUE THREAD

**Issue by ToastyMod** [meefik/linuxdeploy#406]
at cdimage.ubuntu.com there are preinstalled images for Ubuntu Touch on armhf and i386 archs, is it possible to make an installation that downloads the image, mounts it, and then chroots into it?  
It would be pretty cool to use the framebuffer with it and run alongside android.

**Comment by cloud9350** [comment]
Add a test list.

I testing solve framebuffer blackscreen.

**Comment by crushedice2000** [comment]
:+1: for Ubuntu Touch!

**Comment by cloud9350** [comment]
@crushedice2000 I testing framebuffer. Please wait.

**Comment by crushedice2000** [comment]
Don't worry, work slowly and well. :smile: I didn't want to hurry up you.

El mar., 16 feb. 2016 0:33, Gureumi <notifications@github.com> escribió:

> @crushedice2000 <https://github.com/crushedice2000> I testing
> framebuffer. Please wait.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meefik/linuxdeploy/issues/406#issuecomment-184440783>.
>
-- 
Un saludo.
    Helio.

**Comment by cloud9350** [comment]
So late. Now, i downloading ubuntu touch source.

**Comment by ToastyMod** [comment]
I just want to thank everyone. I've never actually used github support-wise so I'm awkwardly surprised at the feedback. :)

**Comment by cloud9350** [comment]
@ToastyMod @crushedice2000
I test ubuntu touch, result is FAIL.
Ubuntu Touch is Require ubuntu kernel.
I can't start framebuffer, VNC, X Server. (all fail output)
SSH is working, but can't get network driver. = No internet.

**Comment by crushedice2000** [comment]
Epic fail! I figured it... However, thank you very much! Your effort was
good.

I tried  few days ago to port it to my SM-T320 and I couldn't get success.
Bad porting documentation. I'll give a second try later...

Thanks anyway! :smile:

El sáb., 20 feb. 2016 5:57, Gureumi <notifications@github.com> escribió:

> @ToastyMod <https://github.com/ToastyMod> @crushedice2000
> <https://github.com/crushedice2000>
> I test ubuntu touch, result is FAIL.
> Ubuntu Touch is Require ubuntu kernel.
> I can't start framebuffer, VNC, X Server. (all fail output)
> SSH is working, but can't get network driver. = No internet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meefik/linuxdeploy/issues/406#issuecomment-186510360>.
>
-- 
Un saludo.
    Helio.

**Comment by ToastyMod** [comment]
What if I tried building Ubuntu Touch from source for Nexus 6P (my device), run it, and then copy the entire fs into a chroot?

**Comment by ToastyMod** [comment]
Off topic: I've also theorized running other Android ROMs in a chroot.

**Comment by cloud9350** [comment]
@ToastyMod You must close this issue. please click Comment and close button.

**Comment by ToastyMod** [comment]
thanks.
