### ISSUE TITLE
Not working on CyanogenMod13 (Clear CM - WIPE, Installed ur Busybox, ToyBox is this problem?)

### ISSUE THREAD

**Issue by NightDawn** [meefik/linuxdeploy#408]
![image](https://cloud.githubusercontent.com/assets/16884241/12824598/3e382d46-cb72-11e5-83a4-8e35271912f5.png)
Look at screenshot

**Comment by cloud9350** [comment]
Please Change Installation type?

**Comment by DienoX** [comment]
I will check it when I back to hause.
Btw. But this it is a bug because i installed new cm and it don't out of the box.

**Comment by cloud9350** [comment]
@DienoX Hmm.. Try it - #386 
And View this - #358

**Comment by NightDawn** [comment]
I surrender it. I now deleted CM 13 from 2 smartphones (Galaxy S5 (G901F) and Galaxy S3 (I9300))
If i got this same problems on 2 different phones so it isnt my fault (fresh CM 13). Just @meefik dont adjust Linux Deploy to newest Android 6.0
I now use Android 5.1 and 5.1 so Linux deploy working (semi working bcs SELinux on G901F and on 2 phones dont working create linux via folder and some other stuff but monting system :C).

@meefik good luck with this problem, 6.0 comming to S5, Note xx Etc. Will nice to makes support Linux  deploy in Android 6.

**Comment by KaliHunter** [comment]
Same issue, Cyanogenmod 13 ks01lte isnt working.... same :C

**Comment by KaliHunter** [comment]
I think repplace applets fix it, in meefik busybox settings check it out ! :D

**Comment by NightDawn** [comment]
I tried it but this dont worked.
I now backed to stock and working xd "Out of The Box"
![image](https://cloud.githubusercontent.com/assets/16884241/12855387/5cf2ad9c-cc3f-11e5-9a9c-84976379cc31.png)

**Comment by KaliHunter** [comment]
Ure from Poland ?

**Comment by NightDawn** [comment]
Ye, I come from Poland but now I live in germany.

**Comment by KaliHunter** [comment]
Witam rodaka :D Mi zadziałało na cmie 13 replace appltets, ale pierw musisz odisntalowac busyboxa i zanstalowac z tą opcją..

**Comment by KaliHunter** [comment]
I wrote that u have to uninstall buysybox first and install it with "replace applets" and its working ! :D

**Comment by DienoX** [comment]
No witam,
Próbowałem, ale wolę poczekać aż meefik to naprawi (ciekawe czemu Google tak nagle na toyboxa przeszedł). Cm 13 ma jeszcze dużo nie doskonałości. 

I tried it but this don't worked for me.

**Comment by new-sashok724** [comment]
Same issue
![screenshot_20160208-132653](https://cloud.githubusercontent.com/assets/8599643/12881991/4267290e-ce5f-11e5-8835-238808cf9e6c.png)

**Comment by Flippylosaurus** [comment]
Still not fixed. Any ideas?

**Comment by haltarkon** [comment]
Same issue
![screenshot_20160216-125101](https://cloud.githubusercontent.com/assets/15276371/13074246/1a047f36-d4ac-11e5-978a-74f8045c9878.png)

**Comment by Flippylosaurus** [comment]
Got it - replace applets with @meefik's BusyBox did the trick.

**Comment by cloud9350** [comment]
Listen All users.
If you use CyagogenMod 13+ or Android L+, and dont't work LinuxDeploy, Please report to me.
Problem name, Android Version.

**Comment by iprokin** [comment]
I confirm reinstalling meefik's BusyBox with "replace applets" option does the trick.

**Comment by haltarkon** [comment]
Thank you, @iprokin . It works for me.

**Comment by hsyarif** [comment]
wow great, thanks guys , the step:
- Uninstall default CM BusyBox, 
- Install meefik BusyBox (from playstore) 
- in meefik BusyBox --> setting - check "Replace Applets" .
- install
- run Linux Deploy... :-)
