### ISSUE TITLE
How to change display driver for Xorg(framebuffer mode)?

### ISSUE THREAD

**Issue by mionec1** [meefik/linuxdeploy#409]
My phone does not support fbdev,how to change other display drivers(for example:msm、ati)?
My GPU is Adreno 220.
Who can tell me? Thanks.

**Comment by cloud9350** [comment]
Nope. You can't change driver.

**Comment by mionec1** [comment]
Why?

**Comment by cloud9350** [comment]
@mionec1 We using chroot GNU/Linux, and not require driver.
and I test ubuntu-drivers command, message "No drivers".

**Comment by mionec1** [comment]
What about fbdev? I cannot use it.What should I do?

**Comment by cloud9350** [comment]
fbdev is Linux FrameBuffer. And I founding solutions.

**Comment by dyharlan** [comment]
YES YOU CAN. I am using a driver called "fbturbo" on my S II and it works quite well. But that's because it has a Mali GPU. (But may work with other devices as well) but since you have an adreno GPU, you may try using freedreno, although you may need to recompile your kernel to support it.

**Comment by southern-dust** [comment]
En...There has an app named "Xserver XSDL",it can be suport in linux deploy on graphics subsystem thus item.

**Comment by southern-dust** [comment]
En...There has an app named "Xserver XSDL",it can be suport in linux deploy on graphics subsystem thus item.
