### ISSUE TITLE
Can't install postgres on Ubuntu 11.10

### ISSUE THREAD

**Issue by rogerwilcofromsq** [meefik/linuxdeploy#41]
I am trying to install postgres 8.4. Error is:

```
# pg_createcluster 8.4 main --start
Creating new cluster (configuration: /etc/postgresql/8.4/main, data: /var/lib/postgresql/8.4/main)...
could not change directory to "/root"
FATAL:  could not create shared memory segment: Function not implemented
DETAIL:  Failed system call was shmget(key=1, size=1507328, 03600).
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/8.4/main"
Error: initdb failed
```

I've tryed this (from here https://github.com/meefik/linuxdeploy/issues/29)

```
sudo -s
mkdir /dev/shm 
mount -t tmpfs /dev/shm 
chmod 777 /dev/shm
```

But without success.

Could You help me, please?

**Comment by Sceleratis** [comment]
I am currently encountering this issue with Kali on my HTC One M83 running Lineage OS.

**Comment by Danct12** [comment]
It sounds like Sys V IPC function is missing from the kernel, I suggest you recompile the kernel with support for `CONFIG_SYSVIPC=y` and try again.

**Comment by twaik** [comment]
https://github.com/meefik/linuxdeploy/issues/13#issuecomment-12946893
