### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by mionec1** [meefik/linuxdeploy#411]
How to open closed lssues?

**Comment by cloud9350** [comment]
Find Close this issue button :smile:

**Comment by mionec1** [comment]
No I want to open issues after I close them.

**Comment by cloud9350** [comment]
@mion Please visit here
http://i.stack.imgur.com/vRuSR.png

Copyright - http://stackoverflow.com/questions/34010565/how-do-i-close-a-github-issue-without-making-a-commit

**Comment by mionec1** [comment]
So much for this.

**Comment by cloud9350** [comment]
@mionec1 :worried:
