### ISSUE TITLE
Root default password doesn't work - linux deploy

### ISSUE THREAD

**Issue by h69pc** [meefik/linuxdeploy#413]
I installed kali in my s6 with linux deploy but cant login as root .... If i set a user in linux deploy i can login with that user but it doesnt have root permission , this user doesnt even have permissions to execute sudo ....... , the default root pass toor doesnt work either.... I tried also choose the user in linux deploy as root but no luck..... , anyone had this problem before....?, is there another other default root password besides toor , thanks for your help :-).
maybe it has something to do with the /etc/init.d/myscript giving an error. ... anyone has suggestions for passwords to log in as root?

**Comment by DotERM** [comment]
Try "changeme", you aren't supposed to login as Root.
