### ISSUE TITLE
sorry

### ISSUE THREAD

**Issue by billym357** [meefik/linuxdeploy#415]

**Comment by cloud9350** [comment]
This is NOT LinuxDeploy issue.
Please search google it.

https://www.google.co.kr/?gfe_rd=cr&ei=BbPBVsPMJ4Gg8wemgrAI&gws_rd=ssl#q=64738+failed:+Permission+denied

**Comment by billym357** [comment]
Sorry

**Comment by cloud9350** [comment]
@billym357 If you solve this issue. please close issue.
