### ISSUE TITLE
Linux Deploy SSH & VCN Fail 

### ISSUE THREAD

**Issue by QuasarMTG** [meefik/linuxdeploy#417]
Hey guys,
i'm having some problems with linux deploy, may you help me please? 
I've attached my mobile status, the end of the installation and what happens if i press the start button. Everything's fine except SSh and VNC, what should i do? 
Thanks for help.

![screenshot_2016-02-14-20-06-30](https://cloud.githubusercontent.com/assets/16956412/13036082/590f2ab8-d35e-11e5-8f60-542c7dc8b7ad.png)
![screenshot_2016-02-14-21-00-19](https://cloud.githubusercontent.com/assets/16956412/13036083/5915b45a-d35e-11e5-90b5-afd1482f2ce4.png)
![screenshot_2016-02-14-21-01-50](https://cloud.githubusercontent.com/assets/16956412/13036084/591b4b86-d35e-11e5-82d3-8d36cc11cad6.png)

**Comment by cloud9350** [comment]
Installation failure. Please reinstall.

**Comment by QuasarMTG** [comment]
Already done a couple of times, always the same error. 
Deploy settings
Distribution: Kali linux
Istallation Path: /sdcard/linux.img
None of the others parameters were changed before installation.

**Comment by cloud9350** [comment]
@QuasarMTG Can you install another GNU/Linux?

**Comment by QuasarMTG** [comment]
I can't, always the same error 'Uknown compressione type'

**Comment by d8k6h2m9** [comment]
@QuasarMTG
Please correct "VCN" to "VNC" in subject.
(Otherwise searching for "VNC" will fail.)

**Comment by cloud9350** [comment]
OoPs, I late. Please update Linux Deploy from Google play store. (Bug fixed)

**Comment by QuasarMTG** [comment]
Really thanks :)
