### ISSUE TITLE
Postgresql install problem in Kali Linux

### ISSUE THREAD

**Issue by Nieto-** [meefik/linuxdeploy#42]
I try to install postgresql in kali linux in my samsung galaxy tab 2 10.1 and when i try to install with apt-get upgrade i recibe the next message:

root@localhost:~# apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue [Y/n]? y
Setting up postgresql-9.1 (9.1.9-1) ...
[....] Starting PostgreSQL 9.1 database server: main[....] The PostgreSQL server failed to start. Please check the log output: 2013-04-24 13:33:29 CDT FATAL: co[FAILot access private key file "server.key": Permission denied ... failed!
 failed!
invoke-rc.d: initscript postgresql, action "start" failed.
dpkg: error processing postgresql-9.1 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of postgresql:
 postgresql depends on postgresql-9.1; however:                                   Package postgresql-9.1 is not configured yet.                                 dpkg: error processing postgresql (--configure):                                 dependency problems - leaving unconfigured                                     Errors were encountered while processing:
 postgresql-9.1
 postgresql
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@localhost:~

some suggest to correct this probblem?

**Comment by newnafis** [comment]
please someone help.........................
root@ghost:~# su postgres -c "/usr/lib/postgresql/9.1/bin/postgres -D /etc/postgresql/9.1/main/" &
[1] 22683
root@ghost:~# 2015-01-17 00:57:07 IST LOG:  could not bind IPv4 socket: Cannot assign requested address
2015-01-17 00:57:07 IST HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2015-01-17 00:57:07 IST LOG:  could not bind IPv6 socket: Cannot assign requested address
2015-01-17 00:57:07 IST HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2015-01-17 00:57:07 IST WARNING:  could not create listen socket for "localhost"
2015-01-17 00:57:07 IST FATAL:  could not create any TCP/IP sockets

**Comment by twaik** [comment]
See https://github.com/meefik/linuxdeploy/issues/942#issuecomment-396513749

**Comment by brokensoul46** [comment]
do-release-upgrade

**Comment by freeload101** [comment]
> do-release-upgrade

Lol? 7 years later ? I use Userland also checkout Java Android Magisk Burp Objection Root Emulator Easy http://JAMBOREE.rmccurdy.com

**Comment by fakerandomguy87** [comment]
i solve it by 

sudo apt-get install metasploit-framework
