### ISSUE TITLE
Nexus 6P problems

### ISSUE THREAD

**Issue by ToastyMod** [meefik/linuxdeploy#424]
Here are some problems I'm having on the 6P (Android 6.0.1)
I appreciate all help.
- Cant framebuffer 
'cat /dev/urandom > /dev/graphics/fb0' command won't show artifacts, outputs "sush: cat: <stdout>: no such device"
- Most/All arm64/aarch64 archs won't run stable/install properly/run properly.
Thanks.

**Comment by cloud9350** [comment]
First, check your fb0 file.
If you enable framebuffer, check weak shake screen.

**Comment by ToastyMod** [comment]
Weak screen shake?

**Comment by cloud9350** [comment]
Yes. Check weak shake screen, or artifacts.

**Comment by ToastyMod** [comment]
I am not seeing any though.

**Comment by cloud9350** [comment]
@ToastyMod Read this
https://github.com/meefik/linuxdeploy/wiki/Framebuffer-notes

**Comment by ToastyMod** [comment]
ill try it thank you.

**Comment by ToastyMod** [comment]
when i use 'cat /dev/random > /dev/graphics/fb0' or 'cat /dev/urandom > /dev/graphics/fb0' i get "sush: cat: <stdout>: No such device"

**Comment by cloud9350** [comment]
Quick question.
You are using ADB or Terminal Emulator?

**Comment by ToastyMod** [comment]
sorry i was away for a while. I alternate between the 2, if i am dealing with framebuffer i usually just use ADB.

**Comment by cloud9350** [comment]
Try Terminal Emulator.

**Comment by ToastyMod** [comment]
I've tried the cat command on both ADB and Terminal Emulator.

**Comment by ToastyMod** [comment]
![screenshot_20160225-182903](https://cloud.githubusercontent.com/assets/10666062/13340478/cc8f332e-dbed-11e5-88a3-4e1189cb66e5.png)

**Comment by ToastyMod** [comment]
the white line at the very top right of the screen is a RAM indicator not a fragment btw

**Comment by cloud9350** [comment]
Please enter this command
cd /dev/graphics
ls -al

And screenshot or paste log here :D
