### ISSUE TITLE
[Hickup?] Starting ssh and vnc fails. No "su" in installation?

### ISSUE THREAD

**Issue by d8k6h2m9** [meefik/linuxdeploy#427]
Edit:
Done Installtion again, this time no problems.

---

Linux Deploy 1.5.6-191
Android 4.1.1
armv71
Debian Jessie armhf 
Image file on VFAT medium.

Installation itself seemed to work flawlessly.
Thanks, nice work till here!

But ssh and vnc can not be started: chroot does not find '/bin/su'.
After digging into it, I am sure that there is no "su" binary in the installation.

(And neither apt-get or aptitude, which I would expect in a Debian system)

**Comment by cloud9350** [comment]
@d8k6h2m9 You must close this issue.

**Comment by d8k6h2m9** [comment]
Hickup?
Done Installtion again, this time no problems.
