### ISSUE TITLE
CyanogenMod 13 cant Install!

### ISSUE THREAD

**Issue by uriel1992** [meefik/linuxdeploy#441]
Hi guys, I install CytanoGenMod 13 (android 6.0.1) and now cant install Kali Linux :( before with Android Lollipop I can install and run Kali Linux :S here debug:

http://pastebin.com/0ePmBsPP

Thx and pls help me :/

**Comment by DotERM** [comment]
Check that you have Internet

**Comment by uriel1992** [comment]
The problem was solved when you install BusyBox
With check "Replace Applets"
