### ISSUE TITLE
Debian testing: kernel too old

### ISSUE THREAD

**Issue by 6ar9** [meefik/linuxdeploy#450]
Hi,
Not really a Linux deploy issue, but anyway I would appreciate your opinion.
Since some months onward, I cannot install Debian testing no more, because it complains a "kernel too old".
My tablet has 3.0.8-perf kernel (Android 4.04). If I install Stable and later upgrade the system, for the same reason some 30 packages (libc the most important one) will not install.

Since no custom roms are available for my old tablet, I cannot upgrade the kernel.
Does it mean that I will never be able to run again Debian Testing on it?

Thanks.

**Comment by cloud9350** [comment]
If your kernel is support Loop device, you can test Debian GNU/Linux.

**Comment by 6ar9** [comment]
Thanks.
The kernel does support Loop. Indeed, I currently run without problems Debian Stable (Jessie) and Ubuntu 15.10.
Some time ago I could run Debian Testing (Stretch) too, but since a certain time, I cannot no more install it.
Don't know if and how it's related to this (Linux Deploy is my first experience of chroot environment, I lack of knowledge), but the problem started approximately when a new kernel was shipped among the upgrades of the Stretch distro. I noticed it because I have Stretch on my Desktop computer.

I supposed that, since Linux deploy uses the Android hardware and resources, my android kernel is now considered "too old" by the current libc of the Stretch distribution.

Any clue?

**Comment by cloud9350** [comment]
Your kernel is old.
At least kernel version 3.2.
You can try another GNU/Linux or upgrade kernel.
The name of your device?

**Comment by 6ar9** [comment]
It's a ZTE v71a.
I flashed on it a rom of the V9 model, that is a little more recent than the v71a, and it's compatible.

(Thread here:
http://forum.xda-developers.com/showthread.php?t=1629630&page=92)

**Comment by cloud9350** [comment]
You can test Debian Squeeze, Ubuntu 10.10, etc.. (2012 year)

**Comment by 6ar9** [comment]
Ok. Thanks.

**Comment by fervi** [comment]
@6ar9
Or just install Arch.

Please close this issue
