### ISSUE TITLE
"Filesystem... Fail" error, can't install anything.

### ISSUE THREAD

**Issue by ToastyMod** [meefik/linuxdeploy#452]
I've tried installing Arch, Ubuntu, and Debian, but they all get up to "Filesystem... Fail" and then the "<<< install".
I'm running Cyanogenmod 13, I was able to install on my AOSP ROM before.

**Comment by ToastyMod** [comment]
Edit: For Debian installation, the error is "Retrieving Release" and then "<<< install"

**Comment by cloud9350** [comment]
Pleases change Installation type.

**Comment by ToastyMod** [comment]
It

**Comment by ToastyMod** [comment]
I tried using Directory as the installation type, it still just abruptly says <<< install... Here is the full output:

[23:50:38] Updating configuration file ... done
[23:50:38] >>> install
[23:50:38] sh: <stdin>[4]: /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory
[23:50:38] <<< install
[23:53:06] Updating configuration file ... done
[23:53:06] >>> install
[23:53:06] sh: <stdin>[4]: /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory
[23:53:06] <<< install

**Comment by ToastyMod** [comment]
Never mind. The busybox wasn't installed correctly.

**Comment by ToastyMod** [comment]
It still didn't work when I changed installation type to directory. Here is the output:

[00:05:07] Updating configuration file ... done
[00:05:07] >>> install
[00:05:07] Checking installation path ... done
[00:05:07] Mounting partitions: 
[00:05:07] / ... done
[00:05:07] Installing Arch Linux distribution: 
[00:05:07] Repository: http://mirror.archlinuxarm.org/armv7h/core
[00:05:07] Preparing for deployment ... done
[00:05:07] Retrieving packages list ... done
[00:05:08] Retrieving base packages: 
[00:05:08] filesystem ... fail
[00:05:08] <<< install

**Comment by cloud9350** [comment]
Settings -> Debug -> Debug mode enable, Trace mode enable, and paste log here.

**Comment by ToastyMod** [comment]
Updating configuration file ... done
+ PATH=/data/user/0/ru.meefik.linuxdeploy/files/bin:/system/xbin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin 
+ printf $'>>> install\n'
>>> install
+ linuxdeploy -t install
+ container_install
+ container_prepare
+ container_mounted
+ is_mounted /data/local/linux
+ local mount_point=/data/local/linux
+ [ -n /data/local/linux ]
+ grep -q  /data/local/linux  /proc/mounts
Checking installation path ... + 
+ return 1
+ msg -n Checking installation path ... 
+ echo -n Checking installation path ... 
+ [ -e /storage/emulated/0/linux.img -a ! -f /storage/emulated/0/linux.img ]
+ msg done
+ echo done
+ [ file = file ]
+ local file_size=0
+ [ -f /storage/emulated/0/linux.img ]
done
+ stat -c %s /storage/emulated/0/linux.img
+ file_size=4293918720
+ [ 0 -eq 0 ]
+ dirname /storage/emulated/0/linux.img
+ local dir_name=/storage/emulated/0
+ stat -c %s -f /storage/emulated/0
+ local block_size=4096
+ stat -c %a -f /storage/emulated/0
+ local available_size=176029
+ let available_size=(4096*176029)+4293918720
+ let DISK_SIZE=(5014933504-5014933504/10)/1048576
+ [ 4304 -gt 4095 ]
+ DISK_SIZE=4095
+ [ 4095 -lt 512 ]
+ let file_size=4293918720/1048576
+ [ 4095 != 4095 ]
+ [ file = file -o file = partition ]
+ local fs fs_support
+ grep -c ext4 /proc/filesystems
+ [ 1 -gt 0 ]
+ fs_support=ext4
+ break
+ [ -z ext4 ]
+ [ auto = auto ]
+ FS_TYPE=ext4
+ msg -n Making file system (ext4) ... 
+ echo -n Making file system (ext4) ... 
Making file system (ext4) ... + losetup -a
+ grep -c /storage/emulated/0/linux.img
+ local loop_exist=0
+ grep -c /storage/emulated/0/linux.img /proc/mounts
+ local img_mounted=0
+ [ 0 -ne 0 -o 0 -ne 0 ]
+ mke2fs -qF -t ext4 -O ^has_journal /storage/emulated/0/linux.img
ext2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /storage/emulated/0/linux.img is mounted.
done
Mounting partitions: 
/ ... + [ 0 -eq 0 ]
+ msg done
+ echo done
+ [ file = directory ]
+ [ file = ram ]
+ return 0
+ [ 0 -ne 0 ]
+ container_mount root binfmt_misc
+ [ 2 -eq 0 ]
+ msg Mounting partitions: 
+ echo Mounting partitions: 
+ local item
+ mount_part root
+ msg -n / ... 
+ echo -n / ... 
+ is_mounted /data/local/linux
+ local mount_point=/data/local/linux
+ [ -n /data/local/linux ]
+ grep -q  /data/local/linux  /proc/mounts
+ 
+ return 1
+ [ -d /data/local/linux ]
+ [ -d /storage/emulated/0/linux.img ]
+ local mnt_opts=rw,relatime
+ mount -o rw,relatime /storage/emulated/0/linux.img /data/local/linux
done
Installing Arch Linux distribution: 
+ [ 0 -eq 0 ]
+ msg done
+ echo done
+ return 0
+ [ 0 -ne 0 ]
+ mount_part binfmt_misc
+ multiarch_support
+ [ -d /proc/sys/fs/binfmt_misc ]
+ return 1
+ return 0
+ [ 0 -ne 0 ]
+ return 0
+ [ 0 -ne 0 ]
+ msg Installing Arch Linux distribution: 
+ echo Installing Arch Linux distribution: 
+ local basic_packages=filesystem acl archlinux-keyring attr bash bzip2 ca-certificates coreutils cracklib curl db e2fsprogs expat findutils gawk gcc-libs gdbm glibc gmp gnupg gpgme grep keyutils krb5 libarchive libassuan libcap libgcrypt libgpg-error libgssglue libidn libksba libldap libsasl libssh2 libtirpc linux-api-headers lzo ncurses nettle openssl pacman pacman-mirrorlist pam pambase perl pinentry pth readline run-parts sed shadow sudo tzdata util-linux xz which zlib
+ get_platform armv7h
+ local arch=armv7h
+ [ -z armv7h ]
+ echo arm
+ local platform=arm
+ [ arm = intel ]
+ local repo=http://mirror.archlinuxarm.org/armv7h/core
+ local cache_dir=/data/local/linux/var/cache/pacman/pkg
+ msg Repository: http://mirror.archlinuxarm.org/armv7h/core
+ echo Repository: http://mirror.archlinuxarm.org/armv7h/core
+ msg -n Preparing for deployment ... 
+ echo -n Preparing for deployment ... 
+ set -e
+ cd /data/local/linux
+ mkdir etc
Repository: http://mirror.archlinuxarm.org/armv7h/core
Preparing for deployment ... + echo root:x:0:0:root:/root:/bin/bash
+ echo root:x:0:
+ touch etc/fstab
+ mkdir tmp
+ chmod 01777 tmp
+ mkdir -p /data/local/linux/var/cache/pacman/pkg
done
Retrieving packages list ... + exit 0
+ [ 0 -eq 0 ]
+ msg done
+ echo done
+ msg -n Retrieving packages list ... 
+ echo -n Retrieving packages list ... 
+ wget -q -O - http://mirror.archlinuxarm.org/armv7h/core/
+ sed -n /<a / s/^.*<a [^>]*href="\([^\"]*\)".*$/\1/p
+ awk -F/ {print $NF}
+ sort -rn
+ local pkg_list=
+ [ 0 -eq 0 ]
+ msg done
+ echo done
+ msg Retrieving base packages: 
+ echo Retrieving base packages: 
+ local package
+ msg -n filesystem ... 
+ echo -n filesystem ... 
done
Retrieving base packages: 
filesystem ... + echo 
+ grep -m1 -e ^filesystem-[[:digit:]].*\.xz$ -e ^filesystem-[[:digit:]].*\.gz$
fail
+ local pkg_file=
+ test 
+ msg fail
+ echo fail
+ return 1
+ printf $'<<< install\n'
<<< install
+ exit 0

**Comment by cloud9350** [comment]
Install meefik's busybox.
``` grep -m1 -e ^filesystem-[[:digit:]]..xz$ -e ^filesystem-[[:digit:]]..gz$ fail ```

**Comment by ToastyMod** [comment]
I'm on mobile, I'll close this issue tomorrow, thank you.

**Comment by cloud9350** [comment]
You can close issue in mobile.
Find close button. (If you not find, try PC view)

**Comment by ellingtonsantos** [comment]
Hi! I have the same problem. I've installed meefik busybox but got the same error.

**Comment by ellingtonsantos** [comment]
I found the error. At cli.sh, line 1521, wget -q -O - "${repo}/" was returning empty. remove -q and all got working.

**Comment by cloud9350** [comment]
@ellingtonsantos You must install meefik's busybox.
```https://github.com/meefik/linuxdeploy/blob/398a52becda6b85b743b5893438097f086f75d26/assets/all/share/cli.sh#L1521```

**Comment by ToastyMod** [comment]
Everything's good.

**Comment by PFCKrutonium** [comment]
I am getting this same issue, and I am using meefik's busybox.

**Comment by pattex16** [comment]
I am getting this too, using meefik's busybox on android 9
