### ISSUE TITLE
Run Linux Deploy on host on an SSH server?

### ISSUE THREAD

**Issue by ToastyMod** [meefik/linuxdeploy#461]
Is it possible to add a way to run Linux Deploy's commands to another computer on an SSH server?
Example:
Linux Deploy on Phone, Linux PC on SSH server.
Linux Deploy sends commands to Linux PC to automatically create Chroot on Linux PC.

**Comment by twaik** [comment]
You can just use https://github.com/meefik/linuxdeploy-cli/ on PC.
