### ISSUE TITLE
No kernel modules on Arch Linux

### ISSUE THREAD

**Issue by kewp** [meefik/linuxdeploy#468]
I've installed Arch Linux on my Samsung Pocket Neo (S5310). Boots fine but no kernel modules are loaded.

```
android@localhost ~]$ lsmod
Module                  Size  Used by
dhd                   394048  0
VoiceSolution          70110  0
[android@localhost ~]$
```

Any ideas how I diagnose this ?
Also bizarrely the kernel seems to be custom compiled ....

```
[android@localhost ~]$ uname -r
3.0.17-ATOMIC_kernel_by_karthick_mostwanted@xda-g261460f-dirty
```

Thanks.

**Comment by harpreet-s** [comment]
Because in your kernel all modules are inbuild , not loadable.

**Comment by kewp** [comment]
Can you tell because of the word ATOMIC ?

**Comment by harpreet-s** [comment]
Because that's how my phone's custom kernel is compiled. When I load stock kernel loadable modules are available but with custom kernel nothing loadable.

**Comment by kewp** [comment]
Any suggestions how I might fix this ? I'm trying to get access to an external camera which need uvcvideo

**Comment by harpreet-s** [comment]
you will need help from kernel developer to add the module you want in kernel , either inbuild or loadable. Nothing can be done from Linux deploy side.

**Comment by kewp** [comment]
I'll try contact him. I found him on XDA.

Do you know how this custom kernel ended up on my phone ? My settings pointed to the arm arch mirror, so it should be the same kernel for everyone, right ?

**Comment by harpreet-s** [comment]
Not possible to install kernel through Linux Deploy. It works in chroot environment. 

You installed a custom ROM which has this kernel or somebody manually flashed this kernel to your phone. No way to get kernel installed automatically !!!

**Comment by kewp** [comment]
Oh yes, I see now ! When I look at my phone settings the kernel is the same ! (when I installed cyanogenmod).

Thanks for the info. Helped a lot.
