### ISSUE TITLE
Postgresql Error

### ISSUE THREAD

**Issue by kenevil1** [meefik/linuxdeploy#474]
Whenever I try to start postgresql it displays showing that it hasn't created any clusters yet.
So I proceed to create a cluster through 'pg_createcluster 9.5 main'.
But it proceeds to give the error:
'FATAL: could not create shared memory segment: Function not implemented
DETAIL: Failed system call was shmget(key=1, size=40,03600).
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/9.5/main"
Error: initdb failed'
I have no clue on solving this.

**Comment by twaik** [comment]
See https://github.com/meefik/linuxdeploy/issues/112#issuecomment-42767990
