### ISSUE TITLE
VNC and SSH fail

### ISSUE THREAD

**Issue by Aimal2342** [meefik/linuxdeploy#478]
Installed img from Linux deploy
Log files are;

Updating configuration file ... done
>>> start
Mounting partitions: 
/ ... done
/proc ... done
/sys ... done
/sys/fs/selinux ... done
/dev ... done
/dev/tty ... skip
/dev/pts ... done
/dev/shm ... done
/proc/sys/fs/binfmt_misc ... done
Configuring the container: 
dns ... done
mtab ... done
Starting services: 
SSH [:22] ... ls: /data/local/linux/etc/ssh/: No such file or directory
FATAL: kernel too old
FATAL: kernel too old
fail
VNC [:5900] ... FATAL: kernel too old
FATAL: kernel too old
fail
<<< start

**Comment by vc5** [comment]
same problem
Can I ask how you solved this？

**Comment by Aimal2342** [comment]
Haven't solved it. Accepted defeat

**Comment by winic57** [comment]
这意味着你的手机Android系统的版本过低了，可以试试降低发布版的版本，或者升级手机的Android系统版本。
It mean your Android system kernel too old

**Comment by lyc8503** [comment]
@winic57 
感谢winic57,问题已经解决!
I have same problem. winic57 gave the write answer. That's because the android kernel is too old.
I just install Debian 7 on Android 4.0 successfully!
