### ISSUE TITLE
[Let's say solved] Can't manage to start GUI

### ISSUE THREAD

**Issue by HikamiSoft** [meefik/linuxdeploy#480]
I installed Kali Linux on my Note 3 and my Onda V891, following the "kali linux mini documentation". The installation went **great**. I'm able to connect to my chroot by **SSH** (i'm using ConnectBot) or start the Kali shell typing <code> su </code> and <code> /data/data/ru.meefik.linuxdeploy/files/bin/linuxdeploy shell </code> on my Android Terminal. The problem is that i can't figure out how to run the GUI.
I tried using **VNC**: 
in Linux deploy i set VNC as graphycs subsystem, then i started some VNC apps trying to connect to <code>localhost:5900 </code>, and on every single app i get a grey screen. I tried from another device (obviusly with the right IP), but the result is the same: **Grey screen**.
So i tried using **XServer**. During the installation of the .img i added the x server component. The steps were:
- Start linux deploy container.
- Open XServer DSL
- SSH by ConnectBot

then i tried different commands, like <code>export DISPLAY=:0 && startlxde</code>, <code>export DISPLAY=:0 startlxde</code> , <code>export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1:4712</code> and so on. When i use the startlxde command it says <code>startlxde not found</code>. 
All this commands were type from root (<code>sudo -i</code>). 

_How can i have a working GUI? Halp pls_

**Comment by HikamiSoft** [comment]
# Actually i solved yesterday.
__*I will keep it open, so people can add things to explain it better.*__

I missed some basic knowledge about XServer, VNC, [Desktop environments](https://wiki.archlinux.org/index.php/Desktop_environment), [Window managers](https://wiki.archlinux.org/index.php/Window_manager), [Display manage](https://wiki.archlinux.org/index.php/display_manager)r  and so on (Yeah, i'm noob).

After a bit of hours spent searching for the web, i finally got a working GUI. 
First of all, you need to **downlaod** some packages that doesn't come with the installation of Kali linux (and other distros, i guess):

<code> sudo apt-get install xorg openbox lxdm </code>

*Actually you don't need all these packages to just start an simple LXDE session, but if you're going to use different Window Manger / DE, chances are that you need them.*

**Xorg** is needed in order to have a working VNC session (*check that you have installed tightvncserver, or whatever is called*).

You should also have alredy installed **lxde** if you chosen LXDE as DE in Linux Deploy Settings. 

Now, we have different ways to make it work.

## Using LXDM
We can use just the LXDM display manager, and edit the **xstartup** file that is *called everytime we start a vncserver*

<code>
vncserver 
</code> <-- To create the xstartup file, if it's the first time you use vncserver
<code>
nano /root/.vnc/xstartup
</code>

and add 

<code> startlxde & </code>
<code>
lxterminal &
</code>

In a few words, lxterminal starts the LXDE terminal, and startlxde starts the LXDE interface.

## Using lxsession

Lxsession should be something related to XORG package, i guess.
So, if we downloaded LXDE and XORG, we can edit the xstartup file like that.

<code>
vncserver 
</code> <-- To create the xstartup file, if it's the first time you use vncserver
<code>
nano /root/.vnc/xstartup
</code>

and add 

<code> /usr/bin/lxsession -s LXDE & </code>
<code>
lxterminal &
</code>

the *-s* is the name of the interface we want to start.

**You can find other useful pages on the ArchLinux wiki. Have fun, and if you have to add something, pls, do!**

**Comment by mirfatif** [comment]
> We can use just the LXDM display manager, and edit the xstartup file that is called everytime we start a vncserver
So we can start Display Manager / Login Manager in chroot? Though it's pointless, but I couldn't make slim work.
