### ISSUE TITLE
Linux Deploy not respecting Busybox path setting

### ISSUE THREAD

**Issue by parkerlreed** [meefik/linuxdeploy#494]
I installed Busybox to /su/xbin and updated the path in Linux Deploy settings. It only detects Busybox at /system/xbin

1.5.6-192

**Comment by meefik** [comment]
1) Update the permissions of /su/xbin:
```sh
chmod 755 /su
chmod 755 /su/xbin
```
2) Run Linux Deploy -> Settings -> Update ENV.

**Comment by parkerlreed** [comment]
Ahh thanks. That worked/

**Comment by parkerlreed** [comment]
I'm running into this again. Busybox Pro installed to /su/bin, permissions are 755, I updated the path, and then hit update env. It still prints "Requires an installed BusyBox"

Nexus 5X 6.0.1 MTC19V SuperSU 2.74

**Comment by parkerlreed** [comment]
Looks like this may be a Busybox install issue. Will repoen if need be.

````
I chose to install to /su/bin. When I go to /su/bin in a terminal and run (as root) "busybox ls" I get this printed

/su/bin/busybox[1]: cat:: not found

Any idea what might be causing this? cat is a normal command.
````

Email I sent to Stericson
