### ISSUE TITLE
no input in frame buffer mode w/ debian wheezy /wo android UI

### ISSUE THREAD

**Issue by JasonNPitt** [meefik/linuxdeploy#52]
Hi-

I've go the graphics for framebuffer mode working but I can't get any input working.  I've tried /dev/input/event0 event1 event2  mouse0  and event*.   I've also tried using an external keyboard and mouse but nothing.  Is there some trick to getting this to work?  I had to disable the android UI to get the graphics to work, but now I can see it but can't do anything.

**Comment by twaik** [comment]
You can try to build https://github.com/meefik/xorg-input-mtev . It supports almost all Android touchscreens.
