### ISSUE TITLE
Arch Linux installation stops at base services

### ISSUE THREAD

**Issue by mwo13** [meefik/linuxdeploy#554]
Hello,
I tried to install Arch Linux. Everything works fine until the configuration of the base services. Here the installation stops. Starting the instance gives me SSH: fail VNC: fail.

**Comment by DienoX** [comment]
I had the same problem. This was due to very old kernel version. How to fix it? I replaced the phone for newer model

**Comment by mwo13** [comment]
Thank you for the response. 
Yes, you are right. I just tried to reanimate my Nexus 7 2012. I also installed Arch via rootfs archive and got “Kernel to old” errors while updating the system. I'm closing this issue.
