### ISSUE TITLE
Getting Audio in chroot

### ISSUE THREAD

**Issue by dojoko55** [meefik/linuxdeploy#56]
Thank you for this wonderful app. Love it so far. This is not really an issue, but I'm curious as to how to get sound working so I would have something like ice weasel running gnash in the background while I read something else. Practically I'm trying to get around Android's multitasking deficiency with the help of your app :-). So far I've got alsa installed but its not working. I'm also running androidVNC, so I'm unsure if that's the problem. Can you please post a guide on how to enable this, or include a script to configure it automatically in LinuxDeploy?

**Comment by okumedia** [comment]
After select the custom mount directory, do I run installation again from start?

**Comment by okumedia** [comment]
What directory do I mount for  Sony Xperia Z Tablet?

**Comment by cepreu2github** [comment]
Pretty good workaround:
https://androidforums.com/threads/how-to-getting-audio-working-inside-a-chroot.924537/
It is about getting audio using PulseAudio network transparency. How to setup PA to stream audio at TCP port and play it on Android using regular application from PlayMarket - Simple Protocol Player.

**Comment by okumedia** [comment]
Tried that before. Didn't work for me.

**Comment by okumedia** [comment]
Is it possible to for alsa-utils to work? I want to run Ardour. My device keeps restarting while trying, like something is clashing with Android System Audio.

**Comment by anonimo82** [comment]
Okumedia, I have the same issue. Look at my post here: https://github.com/meefik/linuxdeploy/issues/1071
