### ISSUE TITLE
chroot can't execute '/system/bin/sh'

### ISSUE THREAD

**Issue by bert003** [meefik/linuxdeploy#569]
Rooted phone - Busybox is installed in /system/xbin

Installed ubuntu - trusty - armhf - 3072MB - /storage/emulated/0/linux.img

everything installed fine - container started well and vnc as well with user android

Cannot sudo su - (SET PERM ROOT error) so I opened Terminal Emulator and:

`su`
`cd /data/data/ru.meefik.linuxdeploy/files/bin`
`./linuxdeploy shell`

and I get : `chroot can't execute '/system/bin/sh' - no such file or directory`

**Comment by bert003** [comment]
Solved by restarting phone... have no explanation though but problem is solved.

**Comment by xuekai** [comment]
intall android4.1.2
