### ISSUE TITLE
howto kill framebuffer?

### ISSUE THREAD

**Issue by mercianary** [meefik/linuxdeploy#57]
How do you exit when using the frame buffer?
The only way I can do it is hold the power button or pull the battery.

**Comment by diabl0w** [comment]
@meefik when using a framebuffer and just xorg, what is a clean way to exit? for example, I have the android UI set to Pause and after being done with xterm and typing "exit" (effectively logging out of X) I just get a black screen with a cursor and no responsiveness.

shouldn't this be triggering linuxdeploy to do some kind of reboot or resume system ui?

**Comment by twaik** [comment]
In the latest version use DE's logout function to close framebuffer session.
