### ISSUE TITLE
W: Failure while installing base Packages Kali Rolling 

### ISSUE THREAD

**Issue by Sultannn** [meefik/linuxdeploy#582]
**Galaxy S3 with SuperSU# 
16GB 4GB= USED 12GB=FREE
Latest Linux Deploy is installed
Latest BusyBox is installed
Everything has been installed. after one hours of releasing-retrieving-validating and unpacking packages, this comes out** 

![screenshot_2016-09-13-16-25-08](https://cloud.githubusercontent.com/assets/22173225/18479239/f761d858-79dc-11e6-8367-0413080f5672.png)

**Comment by Sultannn** [comment]
It seems that the issue is with rolling. I used sana and it worked.
If you want to use Sana, use this URL: http://old.kali.org/kali/

**Comment by ghosted17** [comment]
I can confirm happening with me too on rolling, tried a few different mirrors too. Hope this will be fixed too as i know many would rather use rolling

**Comment by meefik** [comment]
Fixed in version 2.0: https://github.com/meefik/linuxdeploy/releases/tag/2.0.0

**Comment by Sultannn** [comment]
Thank you meefik. If there is anything could help you, I would do that.

**Comment by ghosted17** [comment]
TY
