### ISSUE TITLE
Version 2.0.0 beta2 / Can't install any distribution with chroot or proot

### ISSUE THREAD

**Issue by meltdown03** [meefik/linuxdeploy#585]
Trying to get kali-rolling installed.
If  I use chroot method (I am rooted.) I get:
'>>>deploy
<<<deploy'
This happens no matter which distribution I try.

If I use proot, the install finishes in a few seconds without ever downloading the packages.
example:
'>>>deploy
: : Installing bootstrap/Ubuntu
: : Configuring core/mnt . . .
: : Configuring core/net . . .
<<<deploy'

I'm using File as the image type, fyi.
I have meefik busybox as well.

**Comment by meefik** [comment]
Please put here full log (enable debug mode and trace mode).

**Comment by meltdown03** [comment]
[output.txt](https://github.com/meefik/linuxdeploy/files/477949/output.txt)

**Comment by meefik** [comment]
PRoot can be works only with installation type - directory and installation path - ${ENV_DIR} (e.g. ${ENV_DIR}/rootfs/linux). Variable ${ENV_DIR} - /data/data/ru.meefik.linuxdeploy/env.
Supports only ARMv7 and x86 architecture.

**Comment by meefik** [comment]
If operating environment not working:
Install [BusyBox](https://github.com/meefik/busybox/releases) in /system/xbin. Try to change "Settings -> PATH variable" to /system/xbin and run "Settings - > Update ENV".
