### ISSUE TITLE
Linux Deploy notification icon reappearing after exit

### ISSUE THREAD

**Issue by ApertureAndroid** [meefik/linuxdeploy#586]
Linux Deploy 2.0.0 beta 2
How to reproduce:
1. Stop Linux Deploy
2. Slide out the left menu and hit exit
3. Swipe Linux Deploy from the Task Overview (also known as Recents) screen

The notification icon will come back and will not go away until Linux Deploy is force stopped from the Android settings.

**Comment by mionec1** [comment]
I have the same problem on my phone.

**Comment by ghosted17** [comment]
Same problem, seems to restart after screen it off. I checked settings and can't see anything enabled that would trigger this

**Comment by ApertureAndroid** [comment]
Solved on the newest Play Store update.
https://github.com/meefik/linuxdeploy/commit/1f3b81f8e00abd7b2716cbaa7bab9c9b21bf12db

**Comment by TrueBers** [comment]
Version 2.6.0-258.
Xiaomi Mi 6, lineage OS 16.0 latest nightly build.
The issue still remains.

**Comment by meefik** [comment]
@Iscle please comment on the issue?

**Comment by Iscle** [comment]
Doesn't seem like an issue created by me, but will look into it. I was able to reproduce this on Evolution X 10.0

Expect a reply in 5 or 6 hours.
