### ISSUE TITLE
How to cooperate with android apps

### ISSUE THREAD

**Issue by ucy74** [meefik/linuxdeploy#589]
Is this possible to operate with working android apps from inside chroot?

**Comment by meefik** [comment]
You can manage applications in Android through the command "am" from "unchroot".
Run/open Linux Deploy app:
```sh
unchroot am start -n ru.meefik.linuxdeploy/.MainActivity
```
Show or hide notification in Android (only in Linux Deploy 2.0):
```sh
unchroot am broadcast -a ru.meefik.linuxdeploy.BROADCAST_ACTION --user 0 --es "info" "Hello World!"
unchroot am broadcast -a ru.meefik.linuxdeploy.BROADCAST_ACTION --user 0 --es "alert" "Hello World!"
unchroot am broadcast -a ru.meefik.linuxdeploy.BROADCAST_ACTION --user 0 --esn "hide"
```

**Comment by ucy74** [comment]
I was found another piece of info on Your blog: [http://meefik.ru/blog/2015/09/14/linuxdeploy-android/](url)

**Comment by infiniti008** [comment]
Я использую Lenovo K910. Контейнер с ubuntu 14.04. При использовании unchroot с параметрами кое что не работает. 
Команда запущенная из контейнера: unchroot getprop ro.product.model  работает
Команда : unchroot am broadcast -a ru.meefik.linuxdeploy.BROADCAST_ACTION --user 0 --es "info" "Hello World!"  не работает.
Также как и любое другое действие с am не работает.
Подскажи как исправить или что делать?

**Comment by twaik** [comment]
Исправлено в последней версии.
