### ISSUE TITLE
/tmp dir on ram?

### ISSUE THREAD

**Issue by illtown** [meefik/linuxdeploy#590]
I need to have /tmp in my archlinux to be on ram (it's on disk now, and that's annoying), how can I do that?
Modifying cli.sh?

**Comment by meefik** [comment]
Run this command in container:
```sh
mount -t tmpfs tmpfs /tmp
```

**Comment by illtown** [comment]
Ok, this is a manual way, and how to automate it (I need to mount it before anything is written there, as you can guess)?
Using fstab/mtab didn't help for me, should I use "custom script" instead?

**Comment by illtown** [comment]
Solved with fstab and 'custom init script' with mount -a in it.
