### ISSUE TITLE
Linux deploy (kali linux)  couldn't download packages

### ISSUE THREAD

**Issue by JustGr00ve** [meefik/linuxdeploy#599]
Can someone please help me,  I've been trying to install kali linux from linux deploy but i keep getting couldn't download packages for almost everything.  It's really confusing I've tried changing dns to 8.8.8.8 but still nothing

**Comment by sahruldotid** [comment]
Change Mirror URL to http://old.kali.org/kali/

**Comment by jhonkim422** [comment]
@JustGr00ve just change your Mirror URL/source path to " http://http.kali.org/kali/ " hope this help you and you're welcome

**Comment by l1thal** [comment]
Thanks. This fixed it.
