### ISSUE TITLE
Debian Cinnamon Desktop

### ISSUE THREAD

**Issue by ghost** [meefik/linuxdeploy#605]
Anyone knows how to change the desktop to cinnamon ?

**Comment by meefik** [comment]
Install packages:
```
apt-get install desktop-base x11-xserver-utils xfonts-base xfonts-utils cinnamon
```
Change file ~/.xsession (user home):
```
XKL_XMODMAP_DISABLE=1
export XKL_XMODMAP_DISABLE
cinnamon
```

**Comment by AnguisCaptor** [comment]
I tried this with debian armhf but the desktop failed to load, grey screen

**Comment by meefik** [comment]
Without graphics acceleration Cinnamon does not work, so it is not officially supported as Gnome and KDE.

**Comment by AnguisCaptor** [comment]
In VM's I often run cinnamon in software mode which do not have acceleration either, not sure how to "force" that on

**Comment by Aeres-u99** [comment]
The procedure for using tiling wm ; will it be same as using cinnamon ?
