### ISSUE TITLE
What's the password of "su" in ssh ?

### ISSUE THREAD

**Issue by ghost** [meefik/linuxdeploy#609]
hi
there are a lot of password we need !! in ssh , in vnc , ...
how I can find out that passwords ?

**Comment by rezapayne** [comment]
and because of that , I can't use apt-get  :((((

**Comment by Megaeloelo** [comment]
You must use : "sudo passwd root" then you change password of su, vnc password is "changeme" and ssh password is "changeme".

**Comment by meefik** [comment]
Connect to container via CLI (from Android terminal, telnet or web browser) and change password by "passwd" command. By default password shown in "Linux Deploy -> Properties".

**Comment by gturrini** [comment]
the easiest way to have a root shell is "sudo -i".
it will start an interactive SUDO shell session
