### ISSUE TITLE
Automatic Startup Delay - The container is not mounted because SDCard takes time to mount - (Add a Startup Delay) 

### ISSUE THREAD

**Issue by rkkoszewski** [meefik/linuxdeploy#618]
Hi,

I have a issue with the Automatic Startup of Linux Deploy. Once android boots up, Linux Deploy starts automatically, but fails to read the linux.img file as the SDCard doesn't seems to be mounted at the time it wants to start.

It would be really awesome if you could add a selectable Timeout for the automatic start, to let android mount all SD cards and drives and then start the Linux Container.

A simple Thread.sleep should do the trick.

Greetings and thanks for the awesome software.

**Comment by rkkoszewski** [comment]
Here is a possible implementation: https://github.com/meefik/linuxdeploy/pull/626

@meefik , any chance that you could compile a signed APK? I somehow cannot compile it because it says "Env variable" could not be updated and it would be really helpful if I could update the APK on my android server without having to loose all the configurations.

Greetings.

**Comment by meefik** [comment]
@rkkoszewski Thanks for this patch, I'll add it soon.

**Comment by rkkoszewski** [comment]
Just saw the updated Linux Deploy in the Play store with the delay in it. Works just neat. Thanks.
