### ISSUE TITLE
shell execution problem

### ISSUE THREAD

**Issue by irvine37** [meefik/linuxdeploy#625]
anyone can 
help me with this? 

: / $ /data/data/ru.meefik.linuxdeploy/bin/linuxdrploy shell

it always said 

: line 5' :  'cant open /data/data/ru.meefik.linuxdeploy/env/cli.sh

**Comment by irvine37** [comment]
u0_a87@Flare S3 Power:/ $
u0_a87@Flare S3 Power:/ $ telnet 127.0.0.1 5023

Entering character mode
Escape character is '^]'.


Linux Deploy armv7l /dev/pts/13
~/data/ru.meefik.linuxdeploy/env $ cd /
/ $ /data/data//ru.meefik.linuxdeploy/bin/linuxdeploy shell
:: Mounting partitions:
/data/data/local/mnt ... skip
:: Configuring core/mnt ...
:: Configuring core/net ...
Kali GNU/Linux Rolling [running via Linux Deploy]
chroot: can't change root directory to '/data/local/mnt': Operation not permitted
/ $ apt-get update
/data/data/ru.meefik.linuxdeploy/bin/sh: apt-get: Permission denied
/ $

**Comment by irvine37** [comment]
please help me

**Comment by meefik** [comment]
Root permissions is required. Run commands via su:
```
$ su
# linuxdeploy shell
```

**Comment by irvine37** [comment]
thank youvery much . i figure it out this morning.. any thanks again for responding
