### ISSUE TITLE
Is it possible to start Linux Deploy from command line?

### ISSUE THREAD

**Issue by rkkoszewski** [meefik/linuxdeploy#630]
Hi, 

This is not a bug, just a question.

**Is it possible to start a Linux Deploy Container using Android Command line?**

I've seen on the Wiki for Installing Kali Linux this:
```
su 
/data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy shell
```

But the "linux" folder doesn't exist there.

Is there any other way to start a Linux Deploy Container (Debian) using ADB or something else?

Greetings and thanks

**Comment by meefik** [comment]
Use command:
```
 /data/data/ru.meefik.linuxdeploy/bin/linuxdeploy shell -u root
```

**Comment by rkkoszewski** [comment]
Thanks @meefik.
Work like a charm!! :)
