### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by HaX5am** [meefik/linuxdeploy#635]
it show 
">>> deploy"
"<<< deploy"

**Comment by meefik** [comment]
Install [BusyBox](https://github.com/meefik/busybox/releases) in /system/xbin. Try to change "Settings -> PATH variable" to /system/xbin and run "Settings - > Update ENV".

**Comment by HaX5am** [comment]
nothing change

**Comment by meefik** [comment]
Enable "Settings -> Trace mode" and put logs here.

**Comment by HaX5am** [comment]
its cant make file system

**Comment by meefik** [comment]
Set an image size to 2000 MB.

**Comment by HaX5am** [comment]
thx

**Comment by HaX5am** [comment]
is running
