### ISSUE TITLE
Can't start any database services

### ISSUE THREAD

**Issue by Fahim-Ferdous** [meefik/linuxdeploy#638]
After the new update, I'm having this problem:
root@localhost:~# service postgresql start
[....] Starting PostgreSQL 9.4 database server: main[....] The PostgreSQL server failed to start. Please check the log output: 2016-11-02 15:04:00 BDT [7701-1] LOG: could not create IPv6 socket: Permission denied 2016-11-02 15:04:00 BDT [7701-2] LOG: could not create IPv4 socket: Permission denied 2016-11-02 15:04:00 BDT [7701-3] WARNING: could not create listen socket for "localhost" 2016-11-02 15:04:00 BDT [7701-4] FATAL: coul[FAIL create any TCP/IP sockets ... failed!
 failed

**Comment by meefik** [comment]
Add users "mysql postgres www-data" and other in parameter "Properties -> Privileged users" space separated. And run "Menu -> Configure" after that.

**Comment by c769214** [comment]
Yes! this works on mysql issue like : 

ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

@meefik  @Fahim-Ferdous 

please close this issue so make more people knows that.

**Comment by MasterPlexus** [comment]
Hi, I've the same error at the moment, and I'm not that clear for the solution. I've added the users root, MySQL and the local main user once to group aid_inet, and also enter them in the privileged user property, and rerun the config. But still can not start the mysql-Server and the error "could not create IPv4 socket: Permission denied"-error in mysql log. Nor in system start or run manually /var/sbin/mysqld (as su root or with sudo, no change) ...

So any other suggestions maybe?
Thanks

**Comment by MasterPlexus** [comment]
I thought I was able to add the mentioned privileges (aid_inet), but it is nor possible with the property "priviligeted Users", this is after one step back, and that re accessing the property back to the previous content. And also I can not add users to groups with usermod ( grep 'aid_inet' /etc/group brings only the local user).  I'm not sure what I'm doing wrong.

**Comment by MasterPlexus** [comment]
OK, I found it. sudo usermod -aG aid_inet mysql ... Bevore I had also other aid_* groups wich are not existing also part of the add, which blocks the adding. Now I'm able to start the server.
Thanks, could be stay as closed ;)
