### ISSUE TITLE
how to enable scripts at boot time after installation ?

### ISSUE THREAD

**Issue by Tarsopilami** [meefik/linuxdeploy#639]
Hi - I would like seafile server to launch on boot.
Tried update-rc.d like this 

https://manual.seafile.com/deploy/start_seafile_at_system_bootup.html

 but it did not work.

How can I enable scripts at boot time, after installation ?
thank you.

**Comment by meefik** [comment]
Set path to script (e.g. /etc/init.d/seafile-server) in "Properties -> Init -> Init system -> run-parts -> Init settings -> Init path".

**Comment by Tarsopilami** [comment]
Thank you :) !  Will try this as soon as I get my hands on the machine.
