### ISSUE TITLE
Can't run X11 apps.

### ISSUE THREAD

**Issue by marmistrz** [meefik/linuxdeploy#642]
Configured my container to use the X11 graphics system with DISPLAY 0. Then, in the ssh-ed container: 
`DISPLAY=:0 mnemosyne`.

This fails with `mnemosyne: cannot connect to X server :0`

**Comment by meefik** [comment]
On display :0 must be run X Server (e.g. X Server XSDL).

**Comment by deb75** [comment]
Do you mean we have to install an X server inside linuxdeploy ? Which Xorg driver should be then used ?

**Comment by twaik** [comment]
XServer XSDL is a separate Android app which starts X server on :0.
