### ISSUE TITLE
Slowdown on SSH

### ISSUE THREAD

**Issue by Tarsopilami** [meefik/linuxdeploy#645]
with Lock Screen, Lock WIFI & CPU wakelock enabled, there are still moments where the response of SSH connection to container slows down to a crawl.  Even on a local network.  When the screen is turned back on, speed picks up instantly.  When SSHing from WAN, this makes access sometimes very difficult.    Is there an option to prevent this ?

**Comment by Tarsopilami** [comment]
The issue has been resolved by changing OS Android 5.1.1 > 6.0.1.

**Comment by bashir-abdelwahed** [comment]
I am still havin this issue on android 6.0.1. I tried to deactivate wifi save mode using `sudo iw dev wlan0 set power_save off` I also tried to disable battery optimization for every single application on the phone. it didn't change the slowness
