### ISSUE TITLE
terminal app

### ISSUE THREAD

**Issue by ghost** [meefik/linuxdeploy#649]
Hi,

If i try to start terminal this message appears:

Error when starting terminal!

Why?

**Comment by RikuKawai** [comment]
Do you have [Terminal Emulator](https://play.google.com/store/apps/details?id=jackpal.androidterm&hl=en) installed?

**Comment by Pyzuriaka** [comment]
The terminal is set, and the error remained. What to do?

**Comment by OliverLew** [comment]
Terminal emulator is installed, and I can run the terminal command (default is "telnet 127.0.0.1 5023") directly in the terminal emulator app.
But when I click the "Terminal" button in thr drawer, there ia the message. Don't know why. I am using android 7.0 on nexus 6 and apps are up-to-date.

**Comment by XenRo** [comment]
Same here. Samsung A5 2016 on mm.

**Comment by hckr1123581321** [comment]
Had the same problem. Solved. Thought it might be that the terminal emulator app was not installed. Installed it but the problem still remained. I then went to the linux deploy app permissions in which there was a new option to allow linux deploy to access the teminal. When I enabled that the terminal option in linux deploy started working :)

**Comment by kimo-azzam** [comment]
i can't find linux deploy app permissions ??
Duplicate of @hckr1123581321 #

**Comment by hckr1123581321** [comment]
@kimo-azzam : Try Settings -> apps -> linux deploy -> permissions ->  Additional permissions -> run commands in terminal
Im on nougat on a note 5, i just tap and hold on the linux deploy homescreen app icon for a drop down to appear in which i can select app info -> permissions -> additional permissions -> run commands in terminal. Hope it helps :)

**Comment by kimo-azzam** [comment]
@hckr1123581321 
i'm on android kitkat but i solved it :)

**Comment by rayfoss** [comment]
Strange, I get telnet not found. It seems to not come with 8.1

**Comment by twaik** [comment]
Fixed in latest version.
