### ISSUE TITLE
System crash when stopping container linux deploy v2.0 

### ISSUE THREAD

**Issue by TeHashX** [meefik/linuxdeploy#658]
LD worked fine on Odroid C2, Android 5.1.1, Debian Jessie until I upgraded to v2.0 when I lost all my settings, no problem with this but with new installation my Odroid crash every time I stop the container, if I reboot the device, after logo, I get "Android is optimising apps..."
I don't have the log because I reinstalled android and LD v1.xx and working fine again.
Anyone else facing this issue?

**Comment by TeHashX** [comment]
I tried on another device Odroid XU4, android 7 and I get the same issue. I enabled "sysv" as Init system and when I stop the container, android will crash and soft reboot.

**Comment by TeHashX** [comment]
Here is definitely wrong because I installed on HTC 10, android v6 and same issue again, if I choose run-parts it works but sysv will crash the phone.
Also, I enabled Logging but can't find output.log

**Comment by splinter86** [comment]
I have this same issue. LG Spirit H440, android 5.0.1.

**Comment by TeHashX** [comment]
Hmm, same crash on Xiaomi Mi5 :(

**Comment by TeHashX** [comment]
Sorry for posting again but after December 2016 update I get the same system crash, can you have a look?

**Comment by Jbbs** [comment]
Same problem: on a Blackview BV5000, when I stop the container, android will crash and soft reboot.

Try with 

               sudo update-rc.d -f sendsigs remove

worked for me :o)

**Comment by softwarecreations** [comment]
I'm getting a system crash when stopping the container.
The container is Debian Jessie dir chroot.
Samsung Galaxy Tab 10.1 N8000
Android 4.4.2
Kernel 3.0.31
Root: Phh's SuperUser

Solution:
Don't stop the container. Just leave it running permanently.
I can shut down the tablet, no problem.

**Comment by NHellFire** [comment]
It's not a crash, one of the distro's init scripts is killing all processes on stop. Solution is to run:
```
sudo update-rc.d -f sendsigs remove
```

Also doesn't affect Ubuntu bionic, as that script doesn't exist anymore.

**Comment by softwarecreations** [comment]
@NHellFire thanks!
Where should I run that command?
Do you mean I run that inside the container, to stop it?
I tried doing that now, and it didn't work. I ran the command and nothing happened.

```
#Nothing appeared in in /var/log
dmesg
kern.log
syslog
faillog
debug
```

I'm using sysv as the init system by the way. I don't think this problem was occurring when I was using run-parts.

**Comment by NHellFire** [comment]
You need to run that inside the container. Only needs to be ran once, it
just disables running that script.
