### ISSUE TITLE
cli.sh not in git repository

### ISSUE THREAD

**Issue by CyberShadow** [meefik/linuxdeploy#673]
Hello,

The environment setup script (cli.sh) doesn't seem to be included in this repository.

As a result, when building Linux Deploy from source, the resulting APK does not include this script.

Please add the file so that it's possible to build a working APK from source, and contribute improvements to this script.

**Comment by springbov** [comment]
I may just be confused as how the repositories work, but it seems like it is at least somehow.
[https://github.com/meefik/linuxdeploy/tree/cli](https://github.com/meefik/linuxdeploy/tree/cli)

**Comment by CyberShadow** [comment]
Ah, OK. It's in its own branch, which is a bit unusual. Is there a link somewhere to it?

**Comment by springbov** [comment]
I found this link by doing a google search, I didn't see it anywhere in this repository.

**Comment by meefik** [comment]
https://github.com/meefik/linuxdeploy-cli
