### ISSUE TITLE
Using the device Wireless Card Monitor Mode

### ISSUE THREAD

**Issue by zerokewl88** [meefik/linuxdeploy#68]
I was wondering, is there a way we can use the Device WLAN0 in Monitor Mode?
To do this, we would have to connect to the Device over USB ? (we can't connect via VNC and Use the WLAN0 card.. is what i mean) ?? Is this possible at all?

Or can we add another USB Dongle, will the Linux Deploy System work with a USB Connected WiFi Dongle ? 

I wanted to try use airmon-ng but it comes with a Error   mon0:ERROR while getting interface flags: No such device.

Also inside the Kali Linux, i saw ther Chipset is Unknown, how can we resolve this also ?

**Comment by FacepalmMute** [comment]
Anyone find a method get it to work?
Smartphone(opo/rooted) <= otg-usb adapter <= Ralink Wlan dongle(rt5370)
lsusb : works, shows me the Wlan dongle
lsmod : ERROR ../libkmod/libkmod-module.c:1638 ..
iwconfig: shows me that only wlan0 and p2p0 are up, both are not the Wlan dongle

(linux deploy 1.5.5-189/bb 1.24.1-meefik)
Driver is definitely installed (via firware-ralink or wireless-tools)

**Comment by think2011** [comment]
Anyone find a method get it to work?

**Comment by scndthe2nd** [comment]
i haven't.

**Comment by hochbau** [comment]
I think you need a custom kernel like nethunter (or build your own) which supports your wireless device.

**Comment by twaik** [comment]
Looks like it is not a Linux Deploy issue. Try to contact the vendor to get Monitor Mode working.
