### ISSUE TITLE
command "lsmod" is not working on kali-rolling.

### ISSUE THREAD

**Issue by shadow1163** [meefik/linuxdeploy#681]
Hello,
I have installed kali-rolling used Linux-deploy, it work on my Redmi Note3. I want to add a wireless network adapter into kali. So, I need to install wireless card driver on it. But, I used command "lsmod", some error occurred.
log:
libkmod: ERROR ../libkmod/libkmod-module.c:1655 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory
uname -r
3.10.61+
How should I to deal with it?

**Comment by Darth-plagueis** [comment]
What you are trying to do requires a lot ,a lot of hassle.
You need to compile Redmi note 3 kernel and whatever drivers you are trying to insert.a simple thing like picking up modules from your Linux computer and inserting it via modproble or insmod won't work.
It took almost a month for me to achieve this.

**Comment by shadow1163** [comment]
Thanks for your reply.
I just want to use my wireless network adapter in kali. And I try to compile the driver on Redmi Note3 kernel, it was failed because of Linux kernel headers' file was not installed. Maybe the way is not achieve。
