### ISSUE TITLE
linuxdeploy offline?

### ISSUE THREAD

**Issue by irvine37** [meefik/linuxdeploy#697]
is it possible to install kali image via linuxdeploy offline mode or let say from my recently downloaded image? file

**Comment by irvine37** [comment]
up

**Comment by irvine37** [comment]
up

**Comment by irvine37** [comment]
up

**Comment by cloud9350** [comment]
Yes, you can.
Use RootFS Installation type.

Install properties -> Distribution -> Set RootFS
Source path -> select your kali linux image file. (must use tar.gz)
