### ISSUE TITLE
question

### ISSUE THREAD

**Issue by deb75** [meefik/linuxdeploy#700]
Hello,

This is not an issue, it is a question (I do not know where to find help).

I would like to run some debian X applications on my android tablet through linuxdeploy.

I do not understand exactmy how to do it.

Ideally, I would like to install a custom window manager (awesome), is it possible ?
I guess, I can ssh to linuxdeploy, than install it with apt-get, but is it enough ?
Also, what is the best graphic system ? VNC ? X11 ?

Thanks in advance for your help.

and many thanks for this nice app

**Comment by cloud9350** [comment]
VNC is best graphics system.

**Comment by deb75** [comment]
Thanks for your answeer.

I used it together with LXDE.

It works with the realvncviewer android app (I want to use some linux prog on android) but text is awfully too small on the galaxy note 10.1.

Do you know how to make the desktop appear well on android screen ? (1560x1600)

Do you know how to increase the size of the LXDE desktop ?

**Comment by cloud9350** [comment]
@deb75 Use "VNC Viewer for Android" app.
This app support touch pen and more controller.

**Comment by deb75** [comment]
Thanks for the advice.

I would like to install an alternate window manager (awesome). Do you think it is possible ?
How should I proceed ?

Regards

**Comment by cloud9350** [comment]
1. Yeah, this application is active and working.
2. Use the apt command to install.
apt-get install awesome
