### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Demicro** [meefik/linuxdeploy#703]
>>> deploy
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/env/cli.sh: line 1104: grep: Permission denied
<<< deploy

I have meefik  busybox
Install button ----> permission  denied 
Configure button ------> permission denied

**Comment by hijinio** [comment]
Do you have root access?

**Comment by Demicro** [comment]
Yes, l have root 
I take the output.log from /data/user/.........

**Comment by cloud9350** [comment]
I reinstall application, reinstall os, but not solve this problem.

**Comment by meefik** [comment]
Please install [BusyBox](https://github.com/meefik/busybox/releases) in /system/xbin. Try to change "Settings -> PATH variable" to /system/xbin and run "Settings - > Update ENV". Also image size set up to 2047 MB (busybox mke2fs limitation).

**Comment by Demicro** [comment]
Busybox /su/xbin

Now

:02:55] ## bootstrap/rootfs : do_install && do_configure
[11:02:55] :: Installing bootstrap/rootfs ... 
[11:02:55] Checking installation path ... done
[11:02:55] Making new disk image (2000 MB) ... 1+0 records in
[11:02:55] 1+0 records out
[11:02:55] 1048576 bytes (1.0MB) copied, 0.012559 seconds, 79.6MB/s
[11:02:55] done
[11:02:55] Making file system ... done
[11:02:55] Mounting partitions: 
[11:02:55] / ... done
[11:02:55] /proc ... done
[11:02:55] /sys ... done
[11:02:55] /sys/fs/selinux ... done
[11:02:55] /dev ... done
[11:02:55] /dev/pts ... done
[11:02:55] /dev/shm ... done
[11:02:56] /dev/net/tun ... done
[11:02:56] Importing rootfs from tar.gz archive ... wget: bad address 'hub.meefik.ru'
[11:02:56] tar: invalid magic
[11:02:56] tar: short read
[11:02:56] fail
[11:02:56] <<< deploy

**Comment by meefik** [comment]
Which version of BusyBox installed?
Required 1.25.1-meefik or 1.26.2-meefik.

**Comment by Demicro** [comment]
21:04] ## core/mnt : do_start
[11:21:04] :: Configuring core/mnt ... 
[11:21:04] /data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: eval: line 1: can't create /data/local/mnt/etc/mtab: nonexistent directory
[11:21:04] ## core/net : do_start
[11:21:04] :: Configuring core/net ... 




directory
[11:23:23] /data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: eval: line 1: can't create /data/local/mnt/etc/group: nonexistent directory
[11:23:23] grep: /data/local/mnt/etc/passwd: No such file or directory
[11:23:23] /data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: eval: line 1: can't create /data/local/mnt/etc/passwd: nonexistent directory
[11:23:23] grep: /data/local/mnt/etc/group: No such file or directory
[11:23:23] sed: /data/local/mnt/etc/group: No such file or directory
[11:23:23] ## core/sudo : do_install && do_configure
[11:23:23] :: Configuring core/sudo ... 
[11:23:23] grep: /data/local/mnt/etc/sudoers: No such file or directory
[11:23:23] chmod: /data/local/mnt/etc/sudoers: No such file or directory
[11:23:23] /data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy: eval: line 1: can't create /data/local/mnt/etc/sudoers: nonexistent directory
[11:23:23] chmod: /data/local/mnt/etc/sudoers: No such file or directory
[11:23:23] ## core/unchroot : do_install && do_configure
[11:23:23] :: Configuring core




Busybox 1.26.2 meefik and stericson

**Comment by Demicro** [comment]
46:39] chroot: can't execute '/bin/su': No such file or directory

**Comment by cloud9350** [comment]
I'm solve this problem :)
Use another kernel. (Don't use stock kernel)

**Comment by spchamp** [comment]
On some Android platforms, there may be a 'grep' command located elsewhwere under the pathnames listed in $PATH – such as /system/bin/grep – in addition to the 'grep' command installed by Meefik's BusyBox distro – such as at /system/xbin/grep. At the user's option, one may wish to run 'which grep' in an ordinary terminal emulator, to see which grep command is being located first by the respective shell command interpreter. One may wish to rename the "Dysfunctioning grep", to accomodate the grep installed with the respective BusyBox installation process.

**Comment by carver2** [comment]
![_20180405015029](https://user-images.githubusercontent.com/18192504/38324777-d265724c-3873-11e8-9779-a0cae802c83c.png)
![_20180405015039](https://user-images.githubusercontent.com/18192504/38324778-d2ae23a2-3873-11e8-95db-8e3a33576970.png)
![_20180405015045](https://user-images.githubusercontent.com/18192504/38324779-d2f2edac-3873-11e8-8842-1a078e0dbcf1.png)
![_20180405015051](https://user-images.githubusercontent.com/18192504/38324780-d336e2aa-3873-11e8-8ed0-3fb38f6977e9.png)

**Comment by carver2** [comment]
![_20180405015029](https://user-images.githubusercontent.com/18192504/38324843-fc13998e-3873-11e8-96bf-f6c9e3c6789b.png)
![_20180405015039](https://user-images.githubusercontent.com/18192504/38324844-fc5a3f60-3873-11e8-9201-eb58c6cc881c.png)
![_20180405015045](https://user-images.githubusercontent.com/18192504/38324845-fc9f6c3e-3873-11e8-9cee-98a4b40e4a38.png)
![_20180405015051](https://user-images.githubusercontent.com/18192504/38324846-fce4192e-3873-11e8-921d-1c4c661f345b.png)

**Comment by carver2** [comment]
Settings of linux deploy:
![1](https://user-images.githubusercontent.com/18192504/38325481-a9e5336e-3875-11e8-8f25-d3b213a52c24.png)
Properties:
![2](https://user-images.githubusercontent.com/18192504/38325511-befb1098-3875-11e8-8a9f-1fc65ac815f2.png)
![3](https://user-images.githubusercontent.com/18192504/38325516-c2c91dfa-3875-11e8-856e-4e10a0ad4140.png)
![4](https://user-images.githubusercontent.com/18192504/38325520-c7df7532-3875-11e8-8a16-f91611898043.png)
![5](https://user-images.githubusercontent.com/18192504/38325535-d178959c-3875-11e8-9306-33135b10f659.png)
remote connection:
![6](https://user-images.githubusercontent.com/18192504/38325631-15bd7b96-3876-11e8-8fd8-e1ed11f2e415.jpg)
![7](https://user-images.githubusercontent.com/18192504/38325634-190fb00c-3876-11e8-8d35-792a5e13aeda.png)
Hope this can help you

**Comment by carver2** [comment]
### **Settings of linux deploy:**
![1](https://user-images.githubusercontent.com/18192504/38325697-5da8825c-3876-11e8-9cb3-ea429f571161.png)

### **Properties:**
![2](https://user-images.githubusercontent.com/18192504/38325721-6bfd3f14-3876-11e8-9e83-ee40234c967f.png)
![3](https://user-images.githubusercontent.com/18192504/38325729-74b3ed06-3876-11e8-9a80-6747c99d9470.png)
![4](https://user-images.githubusercontent.com/18192504/38325735-79508ea0-3876-11e8-8e22-25050df0d551.png)
![5](https://user-images.githubusercontent.com/18192504/38325740-7d26e84e-3876-11e8-8f0c-a85da866843a.png)

### **remote conntection:**
![6](https://user-images.githubusercontent.com/18192504/38325757-86cc78fa-3876-11e8-8ca7-630812d23e7d.jpg)
![7](https://user-images.githubusercontent.com/18192504/38325766-8aff8214-3876-11e8-8a41-d0674211be8e.png)
*Hope this can help you*

**Comment by adiack** [comment]
@carver2  this helps thanks. A common mistake poeple do also is downloading the wrong busybox, there are several busybox programs out there make sure you download the one from @meefik

**Comment by tsumansapkota** [comment]
> 

Setting the Installation Path to ENV_DIR, as shown, solved my problem (in Android 10). Directory installation also works inside the ENV_DIR.
Thanks @carver2

**Comment by skythe83** [comment]
Changing install directory to ${ENV_DIR}/rootfs/linux has also helped me, thanks @carver2 
It fails to properly install on /storage/emulated/0/linux using lineageos 18.1 on a oneplus one.

**Comment by Random-Person-RR** [comment]
> ### **Settings of linux deploy:**
> 
> ![1](https://user-images.githubusercontent.com/18192504/38325697-5da8825c-3876-11e8-9cb3-ea429f571161.png)
> ### **Properties:**
> 
> ![2](https://user-images.githubusercontent.com/18192504/38325721-6bfd3f14-3876-11e8-9e83-ee40234c967f.png) ![3](https://user-images.githubusercontent.com/18192504/38325729-74b3ed06-3876-11e8-9a80-6747c99d9470.png) ![4](https://user-images.githubusercontent.com/18192504/38325735-79508ea0-3876-11e8-8e22-25050df0d551.png) ![5](https://user-images.githubusercontent.com/18192504/38325740-7d26e84e-3876-11e8-8f0c-a85da866843a.png)
> ### **remote conntection:**
> 
> ![6](https://user-images.githubusercontent.com/18192504/38325757-86cc78fa-3876-11e8-8ca7-630812d23e7d.jpg) ![7](https://user-images.githubusercontent.com/18192504/38325766-8aff8214-3876-11e8-8a41-d0674211be8e.png) _Hope this can help you_

holy crap, thanks
