### ISSUE TITLE
Failed retrieval of release and packages. https://https.kali.org/kali works through browser but not through deploy.

### ISSUE THREAD

**Issue by berrysamson** [meefik/linuxdeploy#708]
Hi guys, I'm having issues with downloading kali release and packages. Busybox is installed, I can retrieve them through browser but deploy returns "Retrying failed download of http://http.kali.org/kali/dists/kali-rolling/main/binary-armhf/Packages.gz" several times and then eventually displays "E: Couldn't download dists/kali-rolling/main/binary-armhf/Packages".  I've been through the threads and tried it all but no luck.
![screenshot_2017-01-22-18-00-12](https://cloud.githubusercontent.com/assets/25283834/22184605/d25db34a-e0cc-11e6-9fa3-063d9b5d0d48.png)
![screenshot_2017-01-22-18-00-28](https://cloud.githubusercontent.com/assets/25283834/22184606/d9abc5e2-e0cc-11e6-8785-33a81017a7b0.png)
![screenshot_2017-01-22-18-01-02](https://cloud.githubusercontent.com/assets/25283834/22184607/dec1a196-e0cc-11e6-9b14-4ebf5a3b758a.png)

I've been hunting for a fix for a few days now to no avail. 

Anyone have any idea to a solution?

**Comment by meefik** [comment]
The bug in busybox wget:
https://git.busybox.net/busybox/commit/?id=a6f8651911716d1d1624712eb19e4f3608767c7e

**Comment by berrysamson** [comment]
Hello Meefik, thanks for your reply. 
Whats the best way to implement this on my android? Terminal emulator then git clone? 
Thanks again.

**Comment by meefik** [comment]
I prepared a fix:
https://github.com/meefik/busybox/releases/tag/1.26.2
Linux Deploy will update later.

**Comment by berrysamson** [comment]
Perfect! You are a saint.
Thankyou.

**Comment by sunilsong** [comment]
Hello Meefik,
![screenshot_2017-02-09-16-21-50](https://cloud.githubusercontent.com/assets/11643156/22779924/c1f45aec-eee4-11e6-8e1c-ba34414e8a56.png)

I am stuck here, can you help me ?

**Comment by ironman665** [comment]
what should i do with the busy box apk and source code... should i replace my existing apk with that..? and what about source code.zip.. plz reply anyone.. thanks in advance

**Comment by Rakitic** [comment]
Meefik,,how do I use your fix. I'd really use some help
