### ISSUE TITLE
SSH server not accessible via 3/4G connection?

### ISSUE THREAD

**Issue by ngoonee** [meefik/linuxdeploy#711]
My chroot install is accessible from ssh clients on my phone and from other machines on a LAN via the wifi IP. However when I'm not on wifi, I can't seem to access my SSH server via my 3G/4G connection. I'm using a port number above 1024.

**Comment by Anan5a** [comment]
Because the device isn't on internet. You can only access it via LAN.

**Comment by ngoonee** [comment]
Pretty sure the device IS on Internet, as I'm able to connect to the Internet. From further searching it seems ISPs generally block incoming traffic, so that's likely the cause here.
