### ISSUE TITLE
LinuxDeploy /dev/loop0 not /dev/block/loop0?

### ISSUE THREAD

**Issue by MiscellaneousMemphian** [meefik/linuxdeploy#717]
LD is trying to mount a loop that is not on my device block i have a few permission issues as well i have made steady progress over the almost past 2 weeks but the last few days i have been dancing around the same issues. i believe i also have an issue with between the 2 busy boxes the i can not get the right symlink actions and location right to work together might be the bottom line issue.
Im on an galaxy S4 stock root lolli 6.0.1 latest LD wont read my system period so i am using version 1.5.3-174 
![screenshot_2017-02-03-18-56-10](https://cloud.githubusercontent.com/assets/25539909/22614534/ca533a82-ea48-11e6-934c-e59e2cecfe67.png)
![screenshot_2017-02-03-18-54-47](https://cloud.githubusercontent.com/assets/25539909/22614537/d927e800-ea48-11e6-9d95-7caef2432a94.png)
![screenshot_2017-02-03-18-56-29](https://cloud.githubusercontent.com/assets/25539909/22614539/e13f0b40-ea48-11e6-9d0d-dabf410fac00.png)

seems i only have one problem at the moment which is mounting on device loop /mnt/loop0 
/dev/loop0 on /data/local/linux failed: invalid argument 
ok there is an issue with fdisk ive been entering commands in the terminal it will not allow me to open any loop devices
got vnc to say connecting...furthest ive made it yet im going to go in tweak some stuff and see if i can finnally get my Kali to boot after almost 2 weeks...i changed img. location to /storage instead of mount im still getting the dd error though...
dd if=/dev/zero of=/storage/extSdCard/linux.img bs=1048576 seek=3999 count=1
[15:46:27] dd: /storage/extSdCard/linux.img: Invalid argument
As of 1/6/17 still having the loop problem as well as mke2fs not being able to execute with the invalid option -t error 
![screenshot_2017-02-06-15-47-35](https://cloud.githubusercontent.com/assets/25539909/22667842/1a2cb172-ec84-11e6-8fca-3e85d412a405.png)
![screenshot_2017-02-06-15-47-41](https://cloud.githubusercontent.com/assets/25539909/22667859/25703a36-ec84-11e6-9513-20f23890221e.png)

it would be nice to get some assistance from a protege` or somebody to help me out being as the mke2fs command has obviously been scripted wrong if useage commands are displays after LD attemped to execute it.. just saying...

**Comment by MiscellaneousMemphian** [comment]
semms seems i only have one problem at the moment which is mounting on device loop /mnt/loop0

**Comment by MiscellaneousMemphian** [comment]
fixed this issue myself ill close it now

**Comment by meefik** [comment]
https://github.com/meefik/linuxdeploy/issues/727

**Comment by vliapis** [comment]
> fixed this issue myself ill close it now

fixing something w/o informing how you fixed it, is as good as a dead cat in a house infested with rats.
