### ISSUE TITLE
cannot install arch linux

### ISSUE THREAD

**Issue by khumarahn** [meefik/linuxdeploy#730]
Hi, I cannot install the arch linux distribution. It looks like the packages are downloaded, but pacman does not run, and /home/android is not created. There are no error messages. 

I am on 2.0.1-217. Installation of debian works fine.

**Comment by khumarahn** [comment]
I tried to understand what is wrong, and turned on the debug option. With it, I see the "FATAL: kernel too old" message. My kernel is 3.0.*,  and I don't see a way to update it, because the device is old.

Probably this is not a problem with linux deploy.

**Comment by khumarahn** [comment]
I tried to install gentoo. It downloads and unpacks stage3, but then can't sync portage, not being able to resolve `rsync.gentoo.org`. Though I can ping `rsync.gentoo.org` from the terminal.

**Comment by srakitnican** [comment]
If Arch is using glibc 2.24 or newer then the minimum requirement is kernel version 3.2 see: https://github.com/meefik/linuxdeploy/issues/780
