### ISSUE TITLE
is it possible to use linux deploy for full i386 chroot-container ?

### ISSUE THREAD

**Issue by pzlingo** [meefik/linuxdeploy#732]
I just wonder, as qemu should emulate well i386 on most devices. There are apps like limbo which can be used to emulate complete i386-environments. I mean a full i386-environment on ARM, not i386-cromebook or similar. 

When I tried to set architecture on linux deploy to i386 and started, the app freezed. I am running ARMv7

So before spending much more hours to test linux deploy, does anyone have any experiences related to install a full i386-linux-environment (not by using add-architecture or similar) ?

**Comment by ebeat21** [comment]
Did you have try using phone with intel architecture like zenfone

**Comment by pzlingo** [comment]
No, but I know that with intel architecture it would work.
After some investigation I understood that it is not because of linux deploy, as it offers just a container, the problem seems to be that even if I enable i386 architecture under ARM, that some instructions are not interpreted correctly, resulting in application errors.
Thank you.
