### ISSUE TITLE
GUI X11

### ISSUE THREAD

**Issue by deb75** [meefik/linuxdeploy#733]
I first installed linux debian 9 with VNC graphic subsystem.

I would like to try the X11 subsystem. So I modified the linux properties and launched the configuration.

But there is no X server running so far, when I connect through ssh, I do not see any X server running. Nevertheless, the $HOME/.xsession is read as the window manager complains there is no display.

Which step did I miss to make use of the X11 GUI ?

Thanks for your help.

Regards

**Comment by deb75** [comment]
I answeer to myself.

If I install the app Xserver Xsdl and if, inside linux-deploy debian I launch
DISPLAY=localhost:0 emacs

where :0 is the display address of the Xserver, will it work ? (I cannot test for the moment)

**Comment by tberghuis** [comment]
Thanks @deb75. Setting DISPLAY variable worked for me, I was having trouble running synergy I was getting XInputExtension missing error.

**Comment by deb75** [comment]
These questions I asked earlier are the just the manifestation of my complete misunderstanding about the subject. Installing X-server sdl and setting linux-deploy gui method just made it without effort.

But I am glad, my question helped you.
