### ISSUE TITLE
error in vnc viewer

### ISSUE THREAD

**Issue by svralkar30** [meefik/linuxdeploy#739]
The port on which computer is listening for connection could not be contacted

**Comment by svralkar30** [comment]
Give me solution please

**Comment by CodeDem** [comment]
Hey svralkar30 ,

Please be more descriptive with your error and if possible help with a screen shot attachment
also which port number you are using?

**Comment by joaopa00** [comment]
That is a well known problem. This a duplicate of bug #694

There, you will find a workaround to fix the problem. Anyway, it would be nice that this bug is fixed in Linuxdeploy

**Comment by findmenowzero** [comment]
This is not a bug
Check the settings aginst this 
https://github.com/meefik/linuxdeploy/wiki/Installing-Kali-Linux-Guide
