### ISSUE TITLE
[Question] Port Forwarding 

### ISSUE THREAD

**Issue by Dirkstaal** [meefik/linuxdeploy#742]
Hi 
I am running kali-rolling on my android i want to know if it is possible to port forward from my router directly to the linux i am running ?

**Comment by ja9adeesh** [comment]
yes it is possible if you are on wifi. 
you can login to routers settings and add port forwarding rule

    external port: 2222  
    internal ip: <your mobile private ip>
    internal port: 22 (for ssh)

so now you can access your mobile linux ssh through public ip on port 2222
same way you can forward any port
