### ISSUE TITLE
Various

### ISSUE THREAD

**Issue by scargill** [meefik/linuxdeploy#749]
Great piece of software but without docs...

So got it running with Debian..

Can you access any SD Card in the phone?
Is there a way to access the various phone devices from Debian - like the GPS or other sensors?

**Comment by cloud9350** [comment]
You can access SD Card and Internal memory.
Step by step
1. Go install settings -> Mounts -> Enable -> Mount points -> insert text this
/sdcard:sdcard or /storage/sdcard1:sdcard1
2. Now, you can access SD Card/internal memory to home directory/sdcard.

You can access sensors. Use im-sensors

**Comment by anandcu3** [comment]
@scargill  Were you able to access the sensors from Debian.
