### ISSUE TITLE
What is the initial script in the img file created by Linux Deploy?

### ISSUE THREAD

**Issue by zhangew** [meefik/linuxdeploy#75]
Dear Meefik，

I'm trying to use LinuxonAndroid's ubuntu.sh to start the img file created by Linux Deploy, But when the ubuntu.sh executing /root/init.sh, it said that the file does not exist, I think it might be the filename's sake.

So, would you like to tell me what is the initial script which should be executed first?

Thank you!

**Comment by twaik** [comment]
Linux Depeloy does not use init.sh or any other script inside container to start the system services. It starts services directly. See https://github.com/meefik/linuxdeploy-cli
