### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Anan5a** [meefik/linuxdeploy#750]
![screenshot_2017-03-16-13-20-08](https://cloud.githubusercontent.com/assets/16373480/23986069/7dc0ccb0-0a4c-11e7-966e-53d2dfa28f5f.png)
Installation was failed with above error. Please help me

**Comment by Anan5a** [comment]
@meefik What is password for root?

**Comment by meefik** [comment]
You can use sudo command for root access, also you can be set root password at command: sudo passwd root﻿

**Comment by Anan5a** [comment]
Thanks. I did it. :) I also solved the vnc problem .
