### ISSUE TITLE
how to connect serial device via OTG

### ISSUE THREAD

**Issue by YangTakeshi** [meefik/linuxdeploy#752]
i cant find my serial device from /dev，such as ttyS0。does linux deploy support serial devices？

**Comment by cloud9350** [comment]
OTG support but you device is strong.

**Comment by yk727228981** [comment]
whats strong means

**Comment by cloud9350** [comment]
@yk727228981 Either the installation might be wrong or the errors might have occurred.
Because without the dev folder, LinuxDeploy does not work.

**Comment by E000001** [comment]
@cloud9350 , @yk727228981 : I have the same issue. Installed Debian Jessie. Dev folder is presented. lsusb shows me a connected device, but there are no changes in dev folder. So no new item in dev after I firstly plug my device(Arduino) to my phone.

**Comment by baronleonardo** [comment]
I have the same issue exactly like @E000001 
I'm trying reaching my arduino from my OTG connection. but I couldn't find its path!

**Comment by E000001** [comment]
@baronleonardo I am still fighting with it :) But it seems bad :(
No driver is loaded when I connect Arduino to Phone's USB. See Bus02 Port1 Dev 2 below:

`root@localhost:/lib# lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=msm_hsusb_host/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Vendor Specific Class, Driver=, 12M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=msm_hsic_host/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Vendor Specific Class, Driver=diag_bridge, 480M
    |__ Port 1: Dev 2, If 1, Class=Vendor Specific Class, Driver=hsic_sysmon, 480M
    |__ Port 1: Dev 2, If 2, Class=Vendor Specific Class, Driver=ks_bridge, 480M
    |__ Port 1: Dev 2, If 3, Class=Vendor Specific Class, Driver=mdm_bridge, 480M
    |__ Port 1: Dev 2, If 4, Class=Vendor Specific Class, Driver=qc_csvt, 480M
    |__ Port 1: Dev 2, If 5, Class=Vendor Specific Class, Driver=mdm_bridge, 480M
    |__ Port 1: Dev 2, If 6, Class=Vendor Specific Class, Driver=rmnet_usb, 480M
    |__ Port 1: Dev 2, If 7, Class=Vendor Specific Class, Driver=rmnet_usb, 480M
    |__ Port 1: Dev 2, If 8, Class=Vendor Specific Class, Driver=rmnet_usb, 480M

root@localhost:/lib# lsusb
libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Function not implemented
Bus 002 Device 002: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 05c6:904c Qualcomm, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

`
It is possible to communicate with Arduino from Android OS. Seems, that they are using /dev/bus/usb/002/002 (002/002 in my case, may be different on your device)

I tried to install FTDI drivers, but I am lame :) So It is not working. Maybe added drivers in kernel are needed.

**Comment by twaik** [comment]
Not actually LD issue. Your Android kernel should support devices you are trying to connect.
