### ISSUE TITLE
Install in SD card

### ISSUE THREAD

**Issue by Anan5a** [meefik/linuxdeploy#756]
I've an sdcard of 16GB . How do i install kali on it? The directory and partition installation failed .And the image size  stucks on 4GB :(
## Please help

**Comment by cloud9350** [comment]
Use Installation type to "Partiton"

**Comment by Anan5a** [comment]
Tried that but no change. The process stopped after extracting core packages :(

**Comment by cloud9350** [comment]
@Anan5a First, You must format sdcard to ext4 filesystem.

**Comment by Anan5a** [comment]
ok trying .

**Comment by cloud9350** [comment]
If u solve this issue, please close

**Comment by Anan5a** [comment]
BTW it didn't solved.
Installation stop after extracting base packages
