### ISSUE TITLE
VNC GIVES ERROR USING KALI LINUX {ANDROID}

### ISSUE THREAD

**Issue by findmenowzero** [meefik/linuxdeploy#774]
Rx

I had some using Kali Linux when connect through VNC they give error=port is not listening over WiFi and data 

Error ssh not done 
I am check all the ports to connect but nothing happend help me to figure what is going on with VNC or their is some prob during installation plz help me out 
![screenshot_2017-04-26-02-21-41-638_ru meefik linuxdeploy](https://cloud.githubusercontent.com/assets/28023198/25407519/34aa14a4-2a28-11e7-8894-f1b9f7dcb30d.png)
![screenshot_2017-04-26-02-22-26-099_ru meefik linuxdeploy](https://cloud.githubusercontent.com/assets/28023198/25407537/41c6c39e-2a28-11e7-8222-24a9aefe29b3.png)
![screenshot_2017-04-26-02-22-59-663_com realvnc viewer android](https://cloud.githubusercontent.com/assets/28023198/25407544/48cac24e-2a28-11e7-9260-6090a2dec675.png)

**Comment by findmenowzero** [comment]
Hai admin plz some good helpfull ans iam tried this for many time and their always the error of this not some times grey screen but this time is some kind of port error plz help me out

**Comment by creited** [comment]
I have this same problem. I was able to build Ubuntu and Debian, but Kali always fails. It seems like the Install process is not going forward as there is no "Hit... url" "Get ... url" and other processes I see when installing other distros. Its finishing the install process with "Retrieving" and "Validating" commands.

It says at the very bottom lines:
.
.
.
I: Retrieving zlibg (version)
I: Validating zlibg (version)
E: Couldn't download packages: liblz4-1 libusb-0.1-4 libuuid1
<<< deploy

After this, when I hit Start, it says SSH fails but VNC ... done.

But if i hit status it says all those services are stopped.

**Comment by Somebodyhura** [comment]
Check wiki for (Installing Kali Linux Guide) I shooted some troubles there

**Comment by findmenowzero** [comment]
Hai my prob is solved use this 
https://github.com/meefik/linuxdeploy/wiki/Installing-Kali-Linux-Guide

**Comment by Somebodyhura** [comment]
@findmenowzero
Glad to hear my wiki is helpful ;)

Close the thread then
