### ISSUE TITLE
Check Filesystem Before mounting it

### ISSUE THREAD

**Issue by Jerry981028** [meefik/linuxdeploy#783]
Running fsck before mounting (if img and partition installation type is used) is essential to prevent damage to the file system.
Please add this function in the cli. At least there should be an option to toggle it.

**Comment by Somebodyhura** [comment]
I have been using Kali Linux as partition for long time now and I got no problems with damages to filesystem.
Never heard of it anyway...
How about using "fuck" command it in the Linux terminal?

**Comment by Somebodyhura** [comment]
I meant "fsck"

...


Sorry

**Comment by Jerry981028** [comment]
Sometimes I shut down the phone without stopping the container. (or shut down but didn't unmount.) 
However, fsck should only be executed before the partition is mounted.
Adding one line in the script can solve the problem.
`e2fsck -p /dev/loop0`

**Comment by Jerry981028** [comment]
#785 @meefik Please check if it is compatible with all the devices.
For me, it works like a charm.[](url)

**Comment by Jerry981028** [comment]
@Somebodyhura Actually there is a `fuck` command.
https://github.com/nvbn/thefuck

**Comment by Somebodyhura** [comment]
@Jerry981028 
😂 LOL 
That command is useful for me...
