### ISSUE TITLE
Kali Linux installation on external sdcard

### ISSUE THREAD

**Issue by Punkystone01** [meefik/linuxdeploy#784]
So, i tried to install the image file of Kali Linux in my external sdcard but i got many issues. I searched for that issues but i didnt find a right conclusion. So now i want to know what is the correct way to install Kali linux on a external sdcard. Thanks :)

note: if i install it on internal storage it works perfectly fine but i dont have so much free space.

sry for bad english :/

**Comment by irvine37** [comment]
create a partition ext2
