### ISSUE TITLE
Manually selecting the graphical environment

### ISSUE THREAD

**Issue by fervi** [meefik/linuxdeploy#786]
Hello.

I have noticed a problem with which I can not help myself. It's about choosing a graphical environment. There are options in the settings from the list of pairs, but I want to test others that are not on the list - like Enlightenment (This list does not work for me anyway). Where should I add an entry to launch the Xserver XSDL, such as Enlightenment (enlightenment_start)?

For now, I do it manually from the console, but it's a little frustrating.

**Comment by Jerry981028** [comment]
'do it manually from the console' , that's the best way.

**Comment by Jerry981028** [comment]
Check this https://github.com/meefik/linuxdeploy/blob/cli/include/graphics/x11/deploy.sh
You may need to run this command `man xinit`

**Comment by fervi** [comment]
Ok, just this command
export DISPLAY=${X11_HOST}:${X11_DISPLAY}; ~/.xinitrc

Doesn't work (in my phone). So i put beforce .xinitrc
export DISPLAY=:0

And now works, thanks
