### ISSUE TITLE
Sudo is not working on other users than root in arch

### ISSUE THREAD

**Issue by Error1000** [meefik/linuxdeploy#797]
So i installed arch and then i logged in to it as root to make a new user,and then when i tried using sudo on that new user it says:
[newuser@localhost /]# sudo
sudo: PERM_ROOT: setresuid(0, -1, -1): Permission denied
sudo: unable to initialize policy plugin

But when i run it on root it says:

[root@localhost /]# sudo
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] file ...
I have uncommented the line %wheel ALL=(ALL) ALL and i have added the new user in the group wheel.

I have tried several thing to try to solve this issue but i can't solve it.
BTW: To make the new user i used the command: useradd -m -g users -G wheel -s /bin/bash newuser
Oh and if I try to run su on the new user account and type my password it says authentification failure.
So can anybody please help me,I am running Android 6.2.

**Comment by dargow** [comment]
You need to add a new user to the sudo group.
Use this command for create reating new users:
adduser username && adduser username sudo

**Comment by Error1000** [comment]
It says: bash: adduser: command not found
So i tried using useradd and it just shows me the help page of useradd.
I don't think that's how the command is supposed to work.
