### ISSUE TITLE
Can't ssh into Deployment

### ISSUE THREAD

**Issue by TheT3ngu** [meefik/linuxdeploy#799]
Hey Guys,
ive installed arch Linux and everything went fine. If  I start Deploy, it sets up an SSH-Server which accepts connections. But what are my credentials? The username/password-combination I put in the settings don't work. Please help.

**Comment by Error1000** [comment]
I believe that linux deploy doesn't use the account you set for ssh , it makes a new one called android with i believe the same password as you set int the settings.

**Comment by TheT3ngu** [comment]
Thanks, I found my mistake - SwiftKey added space bars behind my username+password. That was the problem. God, I hate touch-keyboards. Thank you for your help!
