### ISSUE TITLE
Does this work well on a class 6 micro sdcard?

### ISSUE THREAD

**Issue by prahladyeri** [meefik/linuxdeploy#805]
I know that you recommend a class-10 sdcard, but just wanted to know about this. I have a rooted Mi Pad tablet with NVIDIA Tegra processor and a 2GB RAM. I have installed a 32GB sdcard on it, but its a class6. Just wanted to know whether a debian+xfce is workable on a class6, or do you absolutely need a class10?

**Comment by Anan5a** [comment]
Yes. Even on class 4 cards but you need to do partition installation. I used a 8GB class 4 card earlier but now I have 32GB class 10 card

**Comment by prahladyeri** [comment]
Thanks for the info @Anan5a !
