### ISSUE TITLE
Arch Linux VNC errors out when using XFCE

### ISSUE THREAD

**Issue by parkerlreed** [meefik/linuxdeploy#807]
![screenshot from 2017-06-21 20-28-43](https://user-images.githubusercontent.com/841440/27412130-776e9750-56c0-11e7-93d5-96fbd30f2862.png)
![screenshot from 2017-06-21 20-28-49](https://user-images.githubusercontent.com/841440/27412131-776ecdf6-56c0-11e7-83e9-584d9dd24edc.png)

Everything else runs fine. Install went great and I can ssh in. The console log on the phone shows that it started dbus, then ssh, then VNC. Note 3 running 7.1.2

**Comment by parkerlreed** [comment]
Changing ~/.xsession from

````
startxfce4
````

to

````
exec dbus-run-session xfce4-session
````

lets it work.

![screenshot from 2017-06-21 20-46-29](https://user-images.githubusercontent.com/841440/27412449-b8c9d906-56c2-11e7-8517-f086cd641be8.png)

**Comment by HoshiYamazaki** [comment]
It appears under Arch Linux but your solution seems to fix it.
