### ISSUE TITLE
Nginx port 80 isn't accessible to Android host

### ISSUE THREAD

**Issue by brooksbl** [meefik/linuxdeploy#808]
So now that I have everything set up, I installed nginx but can't get the port 80 on nginx to work from the Android host. From the command line, I can ping 127.0.0.1 and all the pings succeed. What configuration do I need to set to make the service visible to the Android host in the same way port 22 is?

**Comment by twaik** [comment]
LD is not a virtual machine. All opened ports are visible to Android.
