### ISSUE TITLE
Very slow communication of ttyACM0 on Debian

### ISSUE THREAD

**Issue by Dramaretchi** [meefik/linuxdeploy#818]
Hello,

Please, I need your help, looks like this is a Linux configuration problem.
I have a software that runs on Raspberry that uses an IR USB dongle and works flawlessly without delay in response (works instantly) even if I send a lot of signals.

Let's start:
I've installed the latest Linux Deploy (2.0.2) on Android 6.0.
Later, I've installed Debian (tested Jessie and Wheezy) with armhf architecture.

I've installed the software on Debian (same as I do on my Raspberry)... and this is what happens:

1) I open my web app that has an RCU layout on my PC.
2) I press a button and the USB IR dongle sends the command (1-second of delay, almost normal).
3) I press another button and the USB IR dongle sends the command but takes 2-3 seconds to execute.
4) I press another button and the USB IR dongle sends the command but takes about 15-20 seconds to execute.
5) If I wait about 20-30 seconds between each command, works instantly.

What should be wrong? a problem with the serial port on Linux? or Android?
CPU (quad core), mem (2GB) and free disk space (2GB) it's ok.

Please, your help will be appreciated, I spend 3 full days without success.

**Comment by Dramaretchi** [comment]
I've fixed the problem adding extra time to serial api.

**Comment by WilsonBradley** [comment]
Also seeing lag in kali. Was alright before.

Can you elaborate on ;
"I've fixed the problem adding extra time to serial api."

Not sure what that means or how to look into that.
