### ISSUE TITLE
Reboot system from chroot container

### ISSUE THREAD

**Issue by Khang-Hoang** [meefik/linuxdeploy#822]
When I type reboot command It's return "Running in chroot, ignoring request." How can I solved it

**Comment by mionec1** [comment]
You can reboot your phone.
And you cannot use "shutdown" command either.

**Comment by meefik** [comment]
You can use unchroot for run commands from Android:
```sh
unchroot am start -a android.intent.action.REBOOT
```
or
```sh
unchroot svc power reboot
```

**Comment by GunKneeNeon** [comment]
> 
> ```shell
> unchroot am start -a android.intent.action.REBOOT
> ```
> 
> or
> 
> ```shell
> unchroot svc power reboot
> ```

Is it safe to reboot/shutdown the phone this way without affecting processes currently running in linux? I was wondering if this would give me a corrupted file(ex: .zsh_history) next time when I re-enter the system.

**Comment by danielbisar** [comment]
I think the easiest way to "reboot" the chroot env is:
- disconnect the client (ssh/vnc)
- click the stop button in the linux deploy app
- click the start button

Regarding the fear of a corrupt image: if in doubt additionally run the command `sync` as the first step.
