### ISSUE TITLE
why using vnc got a error and the mouse is 'x'

### ISSUE THREAD

**Issue by zengming00** [meefik/linuxdeploy#826]
![_20170718095020](https://user-images.githubusercontent.com/5255081/28297132-d7805230-6b9e-11e7-85ae-dc545b63ca9b.jpg)

**Comment by meefik** [comment]
You need to clear the "Polkit agent" field via "LXsession configuration".

![screenshot_2015-10-03-23-33-04](https://user-images.githubusercontent.com/1306682/28312638-7cdb5690-6bbc-11e7-9f25-2f60bff739f4.jpg)

http://4pda.ru/forum/index.php?showtopic=378043&view=findpost&p=43416527

**Comment by zengming00** [comment]
@meefik it works
`sudo mv /usr/bin/lxpolkit /usr/bin/lxpolkit_old`
but the mouse still 'x'

**Comment by zengming00** [comment]
when run once `lxappearance` command , the mouse Return to normal

**Comment by vandhern** [comment]
![screenshot from 2018-01-14 04-17-52](https://user-images.githubusercontent.com/35408745/34910323-327f15b6-f8aa-11e7-8a0d-3b7d96467180.png)
Hello.... this is vnc bug.

Open xstartup file inside .vnc folder and add "xsetroot -cursor_name left_ptr". Re-start linux deploy :)
