### ISSUE TITLE
s3 mini - archlinux Frambuffer problem

### ISSUE THREAD

**Issue by mkr848** [meefik/linuxdeploy#83]
Frambuffer problem
Im having the same problem screen gose black ..but when I tried lxde due to the cpu freq meter gage refreshing my screen keep blanking with the cpu meter even if the black screen gose off
I guess its a refreshing rate thing because the screen had no change keeps black if any movment happen it will appear on the screen

**Comment by twaik** [comment]
Please, try to reproduce the bug on the latest version of LD. 
Also you can try to use "Force refresh" option.

**Comment by twaik** [comment]
Looks like that bug was fixed in the latest LD release.
