### ISSUE TITLE
已弃用

### ISSUE THREAD

**Issue by funnypro** [meefik/linuxdeploy#833]
如题

**Comment by manhong2112** [comment]
呃。。首先請問你是？。。

關於翻譯，其實我建議直接fork然後發pull request。。然後甚麼是終端入口？。。還有說真的我英文也不怎樣。。@ 我真不太好。。

**Comment by manhong2112** [comment]
em... anyway i just try my best to translate...
=
in short, he is asking for permission to correct some mistake in Chinese translation and upload on Coolapk (an app market in China). 
Also the terminal entry of Linux Deploy is not compatible with NeoTerm which probably because Linux Deploy is using old implement.
Lastly there was an ANR happened.

**Comment by funnypro** [comment]
@manhong2112  

就是Linux Deploy右上角有一个选项，是进入终端，不过据说它使用的方式是旧的

那个fork后发pull request的话，我应该是翻译arsc后再去pull request吗？

直接@ 你的确是冒昧了……

**Comment by manhong2112** [comment]
@funnypro 

有源碼就直接翻譯源碼啊，干嘛特去碰arsc

/app/src/main/res/values-zh/strings.xml

**Comment by funnypro** [comment]
@manhong2112 尴尬

**Comment by funnypro** [comment]
@manhong2112 翻译后发现了一个尴尬的事情

values-zh/strings.xml相比values/strings.xml而言
values-zh/strings.xml缺失了不少内容，而且values-zh/strings.xml的排版也很乱……

所以我需要把values-zh/strings.xml的内容复制到values/strings.xml并且不打乱它的排序
因此完全翻译可能需要更久的时间

**Comment by manhong2112** [comment]
@funnypro 
順序沒所謂的，另外排版直接用xml formatter之類的就好。。

**Comment by funnypro** [comment]
@manhong2112 

看起来我翻译完一大半了，zh改成了zh_CN

不知道繁体字谁来翻译呢……

如果合并了代码，那么简中翻译应该是彻底完成了

**Comment by funnypro** [comment]
@manhong2112 
我可能高估我的进度和我自己了……

目前看来我翻译完成了三分之一

而且感觉自己离近视又双叒叕近了一步

**Comment by funnypro** [comment]
@manhong2112 

初步的汉化已经完成，接下来应该是修正和改进机翻结果……

而且有一个地方太迷了……

像“复制”、“取消”、“确定”之类的东西在xml我都没有找到……

顺便问一下，语言切换在软件重启后才会生效这个情况，在大多数软件都会出现吗？

**Comment by manhong2112** [comment]
@funnypro 
你有源碼！你可以看layout.xml找到來源的！

至於那個，應該至少需要重新載入一次Activity，其他我就不肯定了

**Comment by funnypro** [comment]
@manhong2112 我在layout目录找不到任何关于Cancel的内容

我可能是个废人了

**Comment by funnypro** [comment]
@manhong2112 

而且我这边翻译完后，用AIDE再编译软件并安装，出现了不少bug……

我大概应该炸库再分一次后下载后试一次吧……

**Comment by manhong2112** [comment]
@funnypro 
搜了一下，cancel貌似是直接用android.R.string.cancel，應該已經自帶翻譯了

**Comment by funnypro** [comment]
@manhong2112 然而并没有自带翻译……
