### ISSUE TITLE
Ssh and vnc client won't start 

### ISSUE THREAD

**Issue by mantaikas9** [meefik/linuxdeploy#838]
I have installed busybox, terminal emulator, Ubuntu. In Linux deploy terminal won't open saying error while opening terminal. When I press start it loads and says ssh and vnc failed.

**Comment by mantaikas9** [comment]
Nvm got it to work.

**Comment by AliHaide001** [comment]
@mantaikas9

Can you tell me how you sort it out?
Please.

I am in the same problem
