### ISSUE TITLE
Cant get sound to work.

### ISSUE THREAD

**Issue by Aeysir** [meefik/linuxdeploy#867]
I was looking over this to try to find out how to get audio to work but I got confused.
https://github.com/meefik/linuxdeploy/issues/223

I was interested in radosd's comment 
 but I don't understand how to do this " first - find out which of the devices in /proc/asound/card0/ is used for playing audio via speaker. I started playing tuneinradio stream from android - then grep -v closed"

specifically the grep -v part, does anyone know how I am supposed to use it in that context

**Comment by dyharlan** [comment]
I agree, his tuto was kind've confusing..
