### ISSUE TITLE
Linux Deploy running out space when installing packages?

### ISSUE THREAD

**Issue by Root-voidX** [meefik/linuxdeploy#875]
Hey, So I installed Debian Jessie on my rooted Nexus 7. Installing is flawless and i went into the configuration menu and states specifically to use a 10GB image for Debian. After installing and updating all core packages, when I go try to install some packages bash exits with an error saying no more space, even though the total installing size wasn't even 1GB. Anyone know where I went wrong? 

Thanks

**Comment by JTRealms** [comment]
Make sure you actually have 10GB free. Also I recommend running in "directory" mode which will share all free space between Linux and android.

The reason being, the nexus 7 is very IO constrained and the "loop mount" used by the image method has a lot of overhead that cripples performance on these devices.

**Comment by Root-voidX** [comment]
Yes so far after switching to directory its working. I'll let you know if other issue arises. For now I am going to close this issue.

**Comment by zhanghuasong831** [comment]
can you tell me how to install in "directory", when i use it , i always get failure

**Comment by meefik** [comment]
Android partitions are not suitable for installing Linux distributions in the directory.
/sdcard usually have FAT filesystem and mounted with "nosuid,nodev,noexec". 
/data mounted with "nosuid,nodev".
The directory mode can be used with "proot" installation, but it works correctly only on Android 4..
