### ISSUE TITLE
Oneplus 3T (aarch64) + Archlinux + VNC: it doesn't start!

### ISSUE THREAD

**Issue by notorand-it** [meefik/linuxdeploy#878]
Device: ONEPLUS A3003
Android: 7.1.2
Architecture: aarch64
Kernel: 3.18.31-lineageos-gfbd3d5f
Memory: 337/5738 MB
Swap: 0/0 MB
SELinux: yes
Loop devices: yes
Support binfmt_misc: no
Supported FS: ext2 ext3 ext4 f2fs fuseblk msdos vfat
Busybox: v\.27.2-meefik

Application: v2.0.3-227

Ubuntu Xenial: works.
Archlinux: doesn't work with:

extra/dbus ... fail
graphics/vnc ... fail

Is this an issue with the ArchLinux itself or is it some incompatibility with Deploy Linux?

**Comment by dje4321** [comment]
Can you provide us a output with debug mode enabled?

**Comment by notorand-it** [comment]
[output.log](https://github.com/meefik/linuxdeploy/files/1513185/output.log)

I see there's some errors but have no clue on how to fix them.

**Comment by dje4321** [comment]
https://github.com/meefik/linuxdeploy/issues/880

I had the same issue :D

**Comment by dje4321** [comment]
Linux deploy as been updated and should have fixed the bug. Can you confirm and close this issue?
