### ISSUE TITLE
Arch Linux libidn2.so.0 is missing

### ISSUE THREAD

**Issue by dje4321** [meefik/linuxdeploy#880]
Trying todo a install of archlinux and im running into errors with pacman not finding libidn2.so.0. It appears to not exsist in the install system.

Options
https://hastebin.com/runajivisu.nginx
Error Log
https://hastebin.com/hocahajoya.bash

**Comment by meefik** [comment]
Fixed in version 2.0.4-228

**Comment by dje4321** [comment]
sweet. just need to wait on the update then :D 
Thanks

**Comment by notorand-it** [comment]
So, it's Deploy Linux, not arch?

**Comment by dje4321** [comment]
Yes. Just wait for the app to be updated and all should be good

**Comment by notorand-it** [comment]
Understood.

**Comment by dje4321** [comment]
Go ahead and close your issue
