### ISSUE TITLE
Linux Deploy automatic start up at android boot

### ISSUE THREAD

**Issue by pbranly** [meefik/linuxdeploy#890]
Hi
I need to have the Linux started on Android boot

I have ticked the specific configuration field inthe linux deploy parameters and even tried to  increased the timer but Linux never starts when I restart by  android box.

Each time I have to go to linux deploy  menu and tick "Start"

Is there any  way to find a trace in order to understnd what / where is the issue ?

thank you  by advance

Regards

Philippe

**Comment by TCerbz** [comment]
It will start the chroot environment, instead of running the Linux Deploy app. 
Try running ssh or vnc without opening the Linux Deploy app, if it can, that means running fine

**Comment by pbranly** [comment]
No it does not start anything. If if ssh, it does not work
And when I run the Linux deploy it shows that it is waiting to click on the start
Then it works
For information I have 2 identical android box. On one it is working fine (when I go to the Linux deploy menu, 8t shows that the start worked alone
On the other one, it does not 
Surely a big difference ...... somewhere 
Regards
PHILIPPE

**Comment by TCerbz** [comment]
If using the phone it works fine...

**Comment by pbranly** [comment]
On one of my 2 box it works as well
So the issue is to understand why it does not on the other box.
Any advice ?any log ?to look at 
Thank you by advance
Phil

**Comment by TCerbz** [comment]
Happy new year too ...
does your android box support init.d?
maybe as an alternative, you can try to create an autostart script and save it in `/system/etc/init.d/`

**Comment by TCerbz** [comment]
Happy new year, too ...
does your android box support init.d?
Maybe as an alternative, you could try creating an autostart script and saving it in `/system/etc/init.d/`

**Comment by TCerbz** [comment]
Happy new year, too ...
does your android box support init.d?
Maybe as an alternative, you can try creating an autostart script and saving it in `/system/etc/init.d/`

**Comment by pbranly** [comment]
Hi

I have re-installed my android from scratch and it is working
I assume I broke something before
Thank you  for your help
Regards
Philippe
