### ISSUE TITLE
Question, Not Issue - Starting/Stopping a container from the command line.

### ISSUE THREAD

**Issue by whitedavidp** [meefik/linuxdeploy#899]
Hello and thanks for this great app.

I am wanting to use Tasker and other apps to backup my install file for Linux Deploy. It seems that it may be best to stop Linux Deploy while this is happening. Is there some good way, from a rooted command line, to stop and restart the container? I wonder about using the activity manager stop/start service on ru.meefik.linuxdeploy.ExecService. But I am not sure that this is the right way to go.

Thanks for all.

**Comment by whitedavidp** [comment]
BTW - it seems I can start LinuxDeploy using the command shown here <https://github.com/meefik/linuxdeploy/issues/630>:

/data/data/ru.meefik.linuxdeploy/bin/linuxdeploy shell -u root

But still wonder about stopping it. Thanks

**Comment by meefik** [comment]
You can be use this command for stop and unmount current container:
```sh
/data/data/ru.meefik.linuxdeploy/bin/linuxdeploy stop -u
```
For mount and start:
```sh
/data/data/ru.meefik.linuxdeploy/bin/linuxdeploy start -m
```
If enable the option "Settings -> Use CLI" and update Env, then you can be use command "linuxdeploy" without full path.

**Comment by whitedavidp** [comment]
Thanks so very much!

**Comment by eusoubrasileiro** [comment]
Thank you! Still works
