### ISSUE TITLE
install deploying then nothing.

### ISSUE THREAD

**Issue by HsPanda** [meefik/linuxdeploy#920]
trying to install debian (or any other linux for that matter) onto my external sd card
i have the pathway set as ${EXTERNAL_STORAGE}/linux.img 
click install, then all i get is : 

">>>deploy
<<<deploy"

and nothing? i feel like i'm doing something wrong but not sure exactly what?

**Comment by HsPanda** [comment]
solved it

**Comment by Seriell** [comment]
how did you solve it?

**Comment by joaoeduardo** [comment]
I have the same problem on Samsung Galaxy Tab 3 7.0 (SM T210) with android 4.4.2.

**Comment by Seriell** [comment]
I also have this problem (which is why i was asking for the solution) on my Teclast X80 Pro (x86 tablet, Android 5)
