### ISSUE TITLE
Linux Deploy not working on x86 at all

### ISSUE THREAD

**Issue by SakiiCode** [meefik/linuxdeploy#921]
I'm trying to install a distro to my x86 tablet (Chuwi hi8 pro) but for some reason nothing works, no error messages.
![screenshot_2018-02-18-09-55-59](https://user-images.githubusercontent.com/13037299/36350148-13ce0992-1493-11e8-9bc9-b12affb00060.png)

It should be compatible

**Comment by Seriell** [comment]
I have the same problem on my Teclast X80 Pro E3E9 (x86_64 tablet)

**Comment by Seriell** [comment]
I have the same problem on my Teclast X80 Pro E3E9 (x86_64 tablet)

**Comment by SakiiCode** [comment]
Solved by updating to Android 6.0.1 LineageOS. The problem might be related to unsupported loop devices.

**Comment by Seriell** [comment]
What android version/ROM were you on previously? (Only asking because this happens on my device and not sure why)

**Comment by SakiiCode** [comment]
I was on "standard" android 5.1

Make sure you installed busybox and you have loop devices enabled in the status section

**Comment by Seriell** [comment]
aight, thanks for the pointers!

-
Sent with Gmail on Huawei Y6 2017
