### ISSUE TITLE
How do I get input in framebuffer?

### ISSUE THREAD

**Issue by invalidsudo** [meefik/linuxdeploy#930]
I managed to get LXDE running on fb0 with my Galaxy S8 in Arch Linux, but it's useless when I can't do anything with it. [This](https://pastebin.com/eMR45J3S) is the result of `cat /proc/bus/input/devices`. Help? I already installed mtev.

**Comment by dyharlan** [comment]
Install and use evtest to determine which is your touchscreen, then reply

**Comment by dyharlan** [comment]
Yes you can, though if you just want to have an onscrren kbd, use onboard. But if you want to have kb&m make sure you dont pull it off in the middle of the xsession,  else it will crash. Im kind've surprised framebuffer still works on newer devices. Could you take pictures of it or a video?

**Comment by InvalidSudo** [comment]
You mean "pull it off" as in disconnecting, right?
I'll post a video demonstration soon. I too am surprised it works, probably helps that Sony is pretty open (shame on their camera DRM though) and I have SELinux set to permissive for the DRM fix.

**Comment by dyharlan** [comment]
Yeah, disconnecting it nay crash X.

**Comment by InvalidSudo** [comment]
I completely forgot to post a video, sorry! [Here it is:](https://photos.app.goo.gl/WZ4z7tKNSZDscMFC9)

**Comment by UnlimitedLord** [comment]
Hey, i wanted to ask, are you using stock rom? I need help, because when i try fb0 as framebuffer it just reboots. Any solution?
I am using Stock ROM with TGPKernel, trying to install debian stretch but no success
