### ISSUE TITLE
Installation failed in Android 8 (proot)

### ISSUE THREAD

**Issue by salvomic** [meefik/linuxdeploy#939]
hi,
I'm operating in the same wi-fi network with two Android devices, trying to installing Linux Deploy with proot in a directory (both tablet haven't root access):
• in an Android 7 tablet the installation starts from the repository
`http://ftp.debian.org/debian` but then it fails with this error lines:
`W: Failure while configuring required packages.`
`W: See //debootstrap/debootstrap.log for details (possibly the package passwd is at fault)`
• in the Android 8 tablet the installation doesn't continue at all and returns this error:
`Retrieving Release`
`E: Failed getting release file http://ftp.debian.org/debian/dists/stretch/Release`

Are there errors in my tablet's configuration or with Oreo (Android 8) system?

Salvo

**Comment by salvomic** [comment]
Please, help: no solution?

**Comment by steppers** [comment]
Yep, I'm having the same issue here on Galaxy S8 Android 8.0:

E: Failed getting release file http://ports.ubuntu.com/dists/xenial/Release

**Comment by salvomic** [comment]
Oreo in Huawei Mediapad M5: with new version and "Linux profile" I still get the error
`E: Failed getting release file http://ftp.debian.org/debian/dists/stretch/Release`
with Debian_arm profile it is install but then I get always errors with `dbus` and `vnc`.
Any help, please?

**Comment by salvomic** [comment]
still the same errors, also with the new release...

**Comment by meefik** [comment]
Unfortunately proot doesn't work correctly with Android Areo

**Comment by taichichuan** [comment]
I can confirm that neither Ubuntu Trusty or Xenial will not install on Google Pixel 2XL w/ 128 GBs of flash.  Both of them fail.  I've included the debootstrap.log in case that helps.
[debootstrap.log](https://github.com/meefik/linuxdeploy/files/2362971/debootstrap.log).

However, bionic succeeds.
