### ISSUE TITLE
Framebuffer on Razr XT910

### ISSUE THREAD

**Issue by llvasconcellos** [meefik/linuxdeploy#94]
Hi! First of all: Incredible work. It really speed up things a lot! I like it so much I wan't to offer to translate it to Brazilian Portuguese (other countries will understand as well). What do you think?

My image is Ubuntu 13.10.

Now to my problem: I would be perfect if I could run linux gui on framebuffer. I have a Rooted Motorola JellyBean Stock ROM with safestrap recovery. I use stock because of the HDMI out and webtop features.

When I start Linux Deploy in debug I recieve the following messages: 

``` sh
Frame Buffer ... Failed to start message bus: failed to bind socket /var/run/dbus/system_bus_socket no such file or directory

-su: xinit: command not found
```

Do you know what this means? I've tried other configurations like Video device fb0, fb1, fb2 (the only 3 files on /dev/graphics/) and display 0,1 and 2. Also set DPI to 256 as i found my phone screen is. No luck, I only see the black screen.

Thanks!

**Comment by eMPee584** [comment]
uhmm.. sorry if I misunderstand this but.. has anyone gotten anything to display on this device's framebuffer, not via VNC? because I am trying to bring up wayland on a xt984 without any success so far..

**Comment by llvasconcellos** [comment]
@eMPee584 Use XServer XSDL. It works fine!

**Comment by eMPee584** [comment]
@llvasconcellos: no, it does not work fine as a wayland client, only as an XServer.
So noone has actually been able to bring up a working framebuffer? _**saaaaaad**_

**Comment by llvasconcellos** [comment]
@eMPee584 Sorry, I didn't realized you need it to work with Wayland. Just out of curiosity, why Wayland? Can't you use X11?

**Comment by eMPee584** [comment]
My inquiry was not about actually using linux deploy, I was just googling for getting this device's framebuffer up.
I want to port a wayland-based distro onto it, but I only get a black framebuffer, and I was hoping someone had actually got this to work. Seems not. _**saaaaaaaaa**_ :sob:

**Comment by llvasconcellos** [comment]
@eMPee584 maybe you could talk to the people that ported the Xserver to android. Good Luck!

**Comment by eMPee584** [comment]
Thanks, but that is a normal android app, wayland would need lower level access without a full android framework.. :thinking:
