### ISSUE TITLE
How to install MySQL or MongoDB on chroot ? Thanks

### ISSUE THREAD

**Issue by SeananTQ** [meefik/linuxdeploy#942]
Hello every one. My english is poor . 
And，No one can solve this problem in my national forum
So ....Please help me.Thanks

**My situation is like this:**
When I installed the database, The terminal displays these messages

`Running in chroot , ignoring requset.`

Then I get an error when I start the database.

`ERROR 2002 (HY000): Can't connect to local MySQL server through  socket '/var/run/mysqld/mysqld.sock' (2)`

or

`No directory, logging in with HOME=/`

**Please teach me,How to install MySQL or MongoDB on chroot ?** 

and I use ubuntu linux

Thanks

**Comment by zouyq** [comment]
`sudo usermod -a -G aid_inet,aid_net_raw mysql`
