### ISSUE TITLE
Can't install 64bit archtetures

### ISSUE THREAD

**Issue by RyuunosukeDS3** [meefik/linuxdeploy#945]
Everytime i try one of those it gives me an error, last time while trying to install arm64 i got "chroot can't execute '/debootstrap/debootstrap' no such file or directory"  and i got this one while trying to install amd64: "E: Invalid Release file, no entry for main/binary-amd64/Packages"

I'm trying it using a galaxy win 2 SM-G360BT for this.
Thanks for your amazing work man, keep this up.

**Comment by RyuunosukeDS3** [comment]
I have no idea... where do i check?

**Comment by meefik** [comment]
What is this distribution? Debian, Ubuntu, Kali?

**Comment by RyuunosukeDS3** [comment]
I was trying to use ubuntu

**Comment by meefik** [comment]
Xenial?

**Comment by meefik** [comment]
From repo http://arcive.ubuntu.com/ubuntu/ ?

**Comment by meefik** [comment]
Architecture armhf also does not work?

**Comment by RyuunosukeDS3** [comment]
i think i tried all of em, yes from this repo, and yes armhf worked just fine

**Comment by meefik** [comment]
> amd64: "E: Invalid Release file, no entry for main/binary-amd64/Packages"
I checked it on my device, it works. There may be some problems with the repository or access to it..

> "chroot can't execute '/debootstrap/debootstrap' no such file or directory"
Maybe your firmware Android (kernel) supports only 32-bit?

**Comment by RyuunosukeDS3** [comment]
Yeah, thats what i thought as well... anyway i was going to use it to host a discord bot, but i got a VPS so i guess its fine, thanks tho!
