### ISSUE TITLE
How can i clone / make a backup?

### ISSUE THREAD

**Issue by mabusdogma** [meefik/linuxdeploy#946]
Hello, now I have a nice working Debian OS on my Linux Deploy, with all I need... How can I make a backup, like an *.img file of what I have in case that something happen?

**Comment by pbranly** [comment]
Hi
Just stop your Linux and from android make a copy of the file Linux.img somewhere else 
Phil

**Comment by meefik** [comment]
Also you can use commands for export and import rootfs:
```
linuxdeploy export /sdcard/linux-rootfs.tgz
```
```
linuxdeploy import /sdcard/linux-rootfs.tgz
```
