### ISSUE TITLE
>>>>>deploy <<<<<deploy only shows when installing

### ISSUE THREAD

**Issue by gelonautics** [meefik/linuxdeploy#955]
Using meefik's busybox only shows
>>>>>deploy
<<<<<deploy

But when i use stericson's busybox. Linux deploy works but it shows that ar can't be found. Can you help me about this? Because I've tried the "fixes" that is here but nothing works

**Comment by XeGrox** [comment]
Try osm0sis' BusyBox located at the first post[](https://forum.xda-developers.com/showthread.php?t=2239421)

**Comment by bthornemail** [comment]
Try going into app settings and enabling storage permissions

**Comment by twaik** [comment]
Looks like that is already solved in the latest release.
