### ISSUE TITLE
Postgresql 10 permission denied

### ISSUE THREAD

**Issue by dragroot** [meefik/linuxdeploy#956]
root@localhost:~# service postgresql start
[....] Starting PostgreSQL 10 database server: main[....] Error: /usr/lib/postgresql/10/bin/pg_ctl /usr/lib/postgresql/10/bin/pg_ctl start -D /var/lib/postgresql/10/main -l /var/log/postgresql/postgresql-10-main.log -s -o -c config_file="/etc/postgresql/10/main/postgresql.conf" exited with status 1: 2018-05-13 19:32:40.494 IST [23566] FATAL: could not access private key file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied 2018-05-13 19:32:40.499 IST [23566] LOG: database system is shut down pg_ctl: could not start server Exami[FAILe log output. ... failed!
 failed!

**Comment by twaik** [comment]
See https://github.com/meefik/linuxdeploy/issues/112#issuecomment-42767990
