### ISSUE TITLE
Unchroot / reboot does not work anymore

### ISSUE THREAD

**Issue by pbranly** [meefik/linuxdeploy#962]
Hi

I used to use sudo  unchroot then reboot to reboot the whole android box remotly
I does not work any more.
When typing "sudo unchroot" i get a "once:"
and the command reboot does not make anything

What is this "once" session ?

Thank you by advance

Regards
Philippe

**Comment by Danct12** [comment]
"once" is your device hostname. And you can still reboot by /system/bin/reboot while in unchroot.

**Comment by pbranly** [comment]
Danct12
Thank you . It works to reboot the Linux part 
I make 
sudo unchroot
su
reboot

And obviously the Linux restarts

But I want to restart the whole Android host. And it was working in the past.
It is sometimes convenient as I mainly use my android Box remotely and sometimes, the Android part cannot be VNC accesses while the Linux part can
Regards
Phil

**Comment by meefik** [comment]
You can use the following commands.

For Android reboot:
```
unchroot am start -a android.intent.action.REBOOT
```

For Android shutdown:
```
unchroot am start -a android.intent.action.ACTION_REQUEST_SHUTDOWN
```

**Comment by pbranly** [comment]
Hi 
The answer from the first command is just
Aborted
So it does not work
Regards

Envoyé de mon iPad
