### ISSUE TITLE
Access denided to listen ports for services

### ISSUE THREAD

**Issue by gorcer** [meefik/linuxdeploy#97]
Hi, 

I use Ubuntu on Android 4, Xperia Arc S

After i installed mysql on  ubuntu i found some problem:
"sudo service mysql start" - return nothing
in log's i found error - dont have permission to listen ports.
But if i run it manualy "sudo mysqld" - it's work fine.

Simmilar problem with jenkins.

**Comment by twaik** [comment]
See #638
