### ISSUE TITLE
wish add switch for boot auto change selinux mode

### ISSUE THREAD

**Issue by zixijian** [meefik/linuxdeploy#975]
The new version2.10
Disabled auto changing SELinux mode
Prevent the linuxdeploy app boot from starting on some Andoid phone,if i disabled selinux on phone,it will affect the ota update。
and i used the phone redmi note 4x，the xiaomi phone now open selinux on default。
so now，when i reboot my phone，i need setenforce 0 first，so i can start linuxdeploy...

**Comment by meefik** [comment]
Unfortunately, Google's security policy clearly prohibits changing the SELinux mode on Android.

**Comment by zixijian** [comment]
however，linuxdeploy still very usefull on a Android phone。there is have some app can help set SElinux permissive or set it in shell，and i now give up ota update to disable SElinux，i wish linuxdeploy do more better😁 The Linux has been popularized by linuxdeploy ，in china，a lot people use it。
