### ISSUE TITLE
No session for pid (lxsession pid)

### ISSUE THREAD

**Issue by shiftyshady** [meefik/linuxdeploy#978]
On Ubuntu 16.04 with default settings (chroot, ubuntu, armhf, xenial, file, ext4, POSIX, enabled INIT, init system: run-parts, GUI: enabled, VNC, LXDE), I get error "No session for pid XXXX" at start up. The pid corresponds to lxsession
I have to click on OK to finish booting.

This error seems quite common in Linux distros, but the solutions suggested in a number of different sites (e.g. disabling apparmor, editing files that do not exist here) are not useful.

**Comment by meefik** [comment]
See #826

**Comment by shiftyshady** [comment]
I had seen the 4pda post, but I don't even have lxpolkit. Apt-get installed lxpolkit, lxsession and changed window manager to openbox-lxde (it was openbox), but same results. Renamed lxpolkit, same. I still get the session error when I run: startlxde

**Comment by shiftyshady** [comment]
![screenshot](https://user-images.githubusercontent.com/30387970/44045236-d086307a-9f1f-11e8-8de8-c44989bc5aa7.png)

**Comment by meefik** [comment]
At me works so:
```sh
mv /usr/bin/lxpolkit /usr/bin/lxpolkit.bak
```

**Comment by piadam** [comment]
Seems like: rm /etc/xdg/autostart/lxpolkit.desktop
was not enough...

mv /usr/bin/lxpolkit /usr/bin/lxpolkit.ORIG
did the trick for me!

**Comment by RenaKunisaki** [comment]
Neither of these have fixed it for me.

**Comment by Gabriel-Python-Archlinux** [comment]
> Parece que: rm /etc/xdg/autostart/lxpolkit.desktop não foi suficiente...
> 
> mv /usr/bin/lxpolkit /usr/bin/lxpolkit.ORIG fez o truque para mim!

Thanks your method works for min on archlinux lxde
