### ISSUE TITLE
Failed to install linux xenial i386 on Android 5.0. can't execute "/debootstrap/debootstrap" No such file or directory

### ISSUE THREAD

**Issue by lyc8503** [meefik/linuxdeploy#991]
I tried to install Ubuntu 16.04 armhf on my Huawei Phone.It succeeded.
However, when I want to install the Ubuntu 16.04 i386 on the same machine with the same config.
It failed while installing.
DEBUG Info: 
##core/net :do_install && do_configure
Configuring core/net...
chroot: can't execute '/debootstrap/debootstrap' No such file or directory

I tried to ignore the error and boot, it says "chroot: can't execute '/bin/su' No such file or directory."
It seems that a complete installion is interrupted.

I wonder why this will happen and how to solve the problem?
I have worked on this for more than five hours and I still have no way to solve it. :(

Thanks in advance! Have a good day.
ps. Also sorry for my English.

**Comment by meefik** [comment]
You can install x86 architecture on ARM device only if the binfmt_misc module is supported in the kernel.

**Comment by lyc8503** [comment]
What should I do to enable the binfmt_misc module?
Should I recompile Android kernel and flash it into my phone?
or can I just use qemu on my PC to install Linux on an image file and then copy to my phone and boot to bypass the problem?

**Comment by Danct12** [comment]
Recompile the Android kernel with binfmt_misc support and flash it to the phone.

**Comment by lyc8503** [comment]
@Danct12 Thanks a lot! I am going to give it a try.
